static EXTENSIONS: phf::Map<&'static str, &[&str]> =
::phf::Map {
    key: 3213172566270843353,
    disps: ::phf::Slice::Static(&[
        (0, 17),
        (0, 0),
        (0, 2),
        (0, 11),
        (0, 52),
        (0, 4),
        (0, 2),
        (0, 0),
        (0, 357),
        (0, 49),
        (0, 854),
        (0, 13),
        (0, 654),
        (0, 0),
        (0, 3),
        (0, 3),
        (0, 281),
        (0, 233),
        (0, 6),
        (0, 158),
        (0, 11),
        (0, 8),
        (0, 1),
        (0, 0),
        (0, 0),
        (0, 175),
        (3, 635),
        (1, 589),
        (0, 0),
        (0, 12),
        (0, 75),
        (0, 25),
        (0, 38),
        (0, 4),
        (0, 4),
        (1, 876),
        (0, 0),
        (0, 135),
        (0, 3),
        (0, 378),
        (0, 5),
        (0, 1),
        (0, 142),
        (0, 197),
        (0, 137),
        (0, 31),
        (0, 60),
        (0, 0),
        (0, 27),
        (0, 147),
        (0, 208),
        (0, 10),
        (0, 331),
        (0, 38),
        (2, 35),
        (0, 0),
        (0, 6),
        (0, 50),
        (0, 119),
        (0, 11),
        (0, 248),
        (0, 180),
        (0, 152),
        (0, 1),
        (0, 5),
        (0, 0),
        (0, 15),
        (0, 541),
        (0, 836),
        (0, 44),
        (0, 245),
        (0, 5),
        (0, 17),
        (0, 19),
        (0, 507),
        (0, 3),
        (0, 0),
        (0, 24),
        (1, 97),
        (0, 448),
        (0, 34),
        (2, 781),
        (0, 18),
        (0, 87),
        (0, 20),
        (0, 405),
        (0, 1),
        (0, 7),
        (0, 2),
        (0, 10),
        (0, 46),
        (0, 1),
        (0, 39),
        (0, 41),
        (0, 133),
        (1, 921),
        (0, 835),
        (0, 698),
        (12, 195),
        (0, 170),
        (5, 1119),
        (0, 1099),
        (0, 170),
        (0, 804),
        (0, 37),
        (0, 11),
        (0, 7),
        (0, 49),
        (0, 128),
        (0, 1),
        (0, 53),
        (0, 278),
        (0, 264),
        (0, 11),
        (0, 0),
        (0, 13),
        (4, 192),
        (0, 9),
        (0, 67),
        (0, 1),
        (0, 295),
        (0, 118),
        (0, 151),
        (0, 63),
        (8, 383),
        (0, 1033),
        (0, 101),
        (0, 1),
        (4, 539),
        (0, 0),
        (0, 5),
        (1, 266),
        (0, 933),
        (0, 292),
        (0, 196),
        (2, 262),
        (1, 871),
        (0, 166),
        (0, 0),
        (0, 223),
        (0, 4),
        (0, 249),
        (2, 581),
        (0, 164),
        (0, 264),
        (0, 259),
        (0, 5),
        (0, 16),
        (0, 1),
        (7, 963),
        (0, 75),
        (0, 68),
        (0, 449),
        (0, 62),
        (0, 637),
        (25, 989),
        (0, 5),
        (2, 42),
        (0, 1045),
        (0, 128),
        (0, 149),
        (0, 7),
        (0, 23),
        (0, 3),
        (0, 119),
        (0, 10),
        (0, 681),
        (0, 2),
        (0, 29),
        (20, 1069),
        (0, 968),
        (13, 843),
        (0, 114),
        (3, 957),
        (1, 371),
        (8, 1033),
        (0, 1),
        (0, 1068),
        (0, 64),
        (0, 132),
        (0, 80),
        (11, 833),
        (0, 0),
        (14, 762),
        (0, 119),
        (15, 336),
        (1, 795),
        (0, 141),
        (1, 906),
        (2, 385),
        (0, 24),
        (2, 913),
        (0, 24),
        (0, 96),
        (0, 2),
        (2, 499),
        (0, 0),
        (0, 197),
        (0, 95),
        (1, 30),
        (0, 19),
        (0, 42),
        (0, 306),
        (0, 15),
        (0, 1),
        (1, 676),
        (0, 439),
        (2, 397),
        (0, 13),
        (2, 567),
        (0, 567),
        (3, 1139),
        (10, 68),
        (1, 393),
        (0, 777),
        (6, 1035),
        (0, 2),
        (0, 495),
        (8, 671),
        (0, 75),
        (0, 67),
        (0, 143),
        (0, 654),
        (0, 342),
        (5, 1079),
        (0, 191),
        (0, 49),
        (4, 454),
        (11, 399),
        (1, 364),
        (61, 713),
        (0, 3),
    ]),
    entries: ::phf::Slice::Static(&[
        ("make", &["Makefile"]),
        ("cfc", &["ColdFusion CFC"]),
        ("i3", &["Modula-3"]),
        ("bzl", &["Starlark"]),
        ("feature", &["Gherkin"]),
        ("mkdn", &["Markdown"]),
        ("mumps", &["M"]),
        ("asmx", &["ASP"]),
        ("pm6", &["Raku"]),
        ("spc", &["PLSQL"]),
        ("mtml", &["MTML"]),
        ("iol", &["Jolie"]),
        ("bdy", &["PLSQL"]),
        ("krl", &["KRL"]),
        ("yaml", &["YAML"]),
        ("hs-boot", &["Haskell"]),
        ("ui", &["XML"]),
        ("rake", &["Ruby"]),
        ("7", &["Roff", "Roff Manpage"]),
        ("psd1", &["PowerShell"]),
        ("mdwn", &["Markdown"]),
        ("wxi", &["XML"]),
        ("json", &["JSON"]),
        ("mcmeta", &["JSON"]),
        ("sss", &["SugarSS"]),
        ("doh", &["Stata"]),
        ("cljs", &["Clojure"]),
        ("htm", &["HTML"]),
        ("fea", &["OpenType Feature File"]),
        ("pxi", &["Cython"]),
        ("mkfile", &["Makefile"]),
        ("frm", &["VBA"]),
        ("ps1", &["PowerShell"]),
        ("dae", &["COLLADA"]),
        ("p8", &["Lua"]),
        ("cabal", &["Cabal Config"]),
        ("dircolors", &["dircolors"]),
        ("urdf", &["XML"]),
        ("lasso", &["Lasso"]),
        ("cljs.hl", &["Clojure"]),
        ("iml", &["XML"]),
        ("pwn", &["Pawn"]),
        ("pmod", &["Pike"]),
        ("wlt", &["Mathematica"]),
        ("nsi", &["NSIS"]),
        ("fsproj", &["XML"]),
        ("soy", &["Closure Templates"]),
        ("veo", &["Verilog"]),
        ("ssjs", &["JavaScript"]),
        ("mkii", &["TeX"]),
        ("gs", &["GLSL", "Gosu", "Genie", "JavaScript"]),
        ("graphqls", &["GraphQL"]),
        ("rei", &["Reason"]),
        ("ivy", &["XML"]),
        ("xsp.metadata", &["XPages"]),
        ("wixproj", &["XML"]),
        ("raw", &["Raw token data"]),
        ("cpy", &["COBOL"]),
        ("mjml", &["XML"]),
        ("for", &["Formatted", "Forth", "Fortran"]),
        ("depproj", &["XML"]),
        ("em", &["EmberScript"]),
        ("asciidoc", &["AsciiDoc"]),
        ("cwl", &["Common Workflow Language"]),
        ("plist", &["OpenStep Property List", "XML Property List"]),
        ("csh", &["Tcsh"]),
        ("emacs", &["Emacs Lisp"]),
        ("ktm", &["Kotlin"]),
        ("scss", &["SCSS"]),
        ("sage", &["Sage"]),
        ("sublime-settings", &["JSON with Comments"]),
        ("sexp", &["Common Lisp"]),
        ("tmSnippet", &["XML Property List"]),
        ("sparql", &["SPARQL"]),
        ("mcfunction", &["mcfunction"]),
        ("sls", &["SaltStack", "Scheme"]),
        ("lasso8", &["Lasso"]),
        ("ditamap", &["XML"]),
        ("f77", &["Fortran"]),
        ("scm", &["Scheme"]),
        ("vssettings", &["XML"]),
        ("less", &["Less"]),
        ("bib", &["BibTeX"]),
        ("E", &["E"]),
        ("pt", &["XML"]),
        ("com", &["DIGITAL Command Language"]),
        ("lsp", &["NewLisp", "Common Lisp"]),
        ("sublime_session", &["JSON with Comments"]),
        ("model.lkml", &["LookML"]),
        ("mdpolicy", &["XML"]),
        ("jsonc", &["JSON with Comments"]),
        ("pl", &["Perl", "Raku", "Prolog"]),
        ("do", &["Stata"]),
        ("b", &["Brainfuck", "Limbo"]),
        ("tmLanguage", &["XML Property List"]),
        ("diff", &["Diff"]),
        ("rnh", &["RUNOFF"]),
        ("ls", &["LoomScript", "LiveScript"]),
        ("pike", &["Pike"]),
        ("cjsx", &["CoffeeScript"]),
        ("ashx", &["ASP"]),
        ("gv", &["Graphviz (DOT)"]),
        ("factor", &["Factor"]),
        ("stan", &["Stan"]),
        ("tmPreferences", &["XML Property List"]),
        ("hy", &["Hy"]),
        ("prefs", &["INI"]),
        ("cfml", &["ColdFusion"]),
        ("6pl", &["Raku"]),
        ("sed", &["sed"]),
        ("har", &["JSON"]),
        ("ahkl", &["AutoHotkey"]),
        ("tf", &["HCL"]),
        ("mmk", &["Module Management System"]),
        ("h", &["C++", "Objective-C", "C"]),
        ("adb", &["Ada"]),
        ("d-objdump", &["D-ObjDump"]),
        ("gts", &["Gerber Image"]),
        ("r2", &["Rebol"]),
        ("ant", &["XML"]),
        ("mkiv", &["TeX"]),
        ("glf", &["Glyph"]),
        ("sublime-commands", &["JSON with Comments"]),
        ("dtx", &["TeX"]),
        ("jscad", &["JavaScript"]),
        ("flux", &["FLUX"]),
        ("rbxs", &["Lua"]),
        ("cake", &["CoffeeScript", "C#"]),
        ("xslt", &["XSLT"]),
        ("proj", &["XML"]),
        ("y", &["Yacc"]),
        ("cbl", &["COBOL"]),
        ("nb", &["Text", "Mathematica"]),
        ("dof", &["INI"]),
        ("eclxml", &["ECL"]),
        ("clj", &["Clojure"]),
        ("mat", &["Unity3D Asset"]),
        ("1m", &["Roff", "Roff Manpage"]),
        ("forth", &["Forth"]),
        ("als", &["Alloy"]),
        ("creole", &["Creole"]),
        ("dats", &["ATS"]),
        ("pyde", &["Python"]),
        ("di", &["D"]),
        ("sc", &["SuperCollider", "Scala"]),
        ("maxproj", &["Max"]),
        ("ccproj", &["XML"]),
        ("pprx", &["REXX"]),
        ("asm", &["Motorola 68K Assembly", "Assembly"]),
        ("scala", &["Scala"]),
        ("f08", &["Fortran"]),
        ("glsl", &["GLSL"]),
        ("csdef", &["XML"]),
        ("escript", &["Erlang"]),
        ("properties", &["Java Properties", "INI"]),
        ("ur", &["UrWeb"]),
        ("rex", &["REXX"]),
        ("SchDoc", &["Altium Designer"]),
        ("g", &["GAP", "G-code"]),
        ("fxml", &["XML"]),
        ("jbuilder", &["Ruby"]),
        ("md", &["Markdown", "GCC Machine Description"]),
        ("rbw", &["Ruby"]),
        ("tu", &["Turing"]),
        ("gbo", &["Gerber Image"]),
        ("nsh", &["NSIS"]),
        ("pkb", &["PLSQL"]),
        ("ndproj", &["XML"]),
        ("m3", &["Modula-3"]),
        ("smt", &["SMT"]),
        ("rego", &["Open Policy Agent"]),
        ("toc", &["TeX", "World of Warcraft Addon Data"]),
        ("asn", &["ASN.1"]),
        ("cirru", &["Cirru"]),
        ("ring", &["Ring"]),
        ("php3", &["PHP"]),
        ("toml", &["TOML"]),
        ("rebol", &["Rebol"]),
        ("rpy", &["Python", "Ren\'Py"]),
        ("builds", &["XML"]),
        ("hack", &["Hack"]),
        ("jison", &["Jison"]),
        ("glslv", &["GLSL"]),
        ("volt", &["Volt"]),
        ("yap", &["Prolog"]),
        ("sublime-completions", &["JSON with Comments"]),
        ("PrjPCB", &["Altium Designer"]),
        ("rbi", &["Ruby"]),
        ("prisma", &["Prisma"]),
        ("ftl", &["FreeMarker"]),
        ("6pm", &["Raku"]),
        ("kts", &["Kotlin"]),
        ("qbs", &["QML"]),
        ("fish", &["fish"]),
        ("xtend", &["Xtend"]),
        ("4dm", &["4D"]),
        ("mud", &["ZIL"]),
        ("omgrofl", &["Omgrofl"]),
        ("1", &["Roff", "Roff Manpage"]),
        ("xqm", &["XQuery"]),
        ("hc", &["HolyC"]),
        ("desktop.in", &["desktop"]),
        ("vrx", &["GLSL"]),
        ("thy", &["Isabelle"]),
        ("gaml", &["GAML"]),
        ("boot", &["Clojure"]),
        ("ts", &["XML", "TypeScript"]),
        ("sublime-workspace", &["JSON with Comments"]),
        ("blade.php", &["Blade"]),
        ("ps", &["PostScript"]),
        ("tese", &["GLSL"]),
        ("pyw", &["Python"]),
        ("chpl", &["Chapel"]),
        ("_js", &["JavaScript"]),
        ("ox", &["Ox"]),
        ("tfstate", &["JSON"]),
        ("mkvi", &["TeX"]),
        ("monkey2", &["Monkey"]),
        ("eex", &["HTML+EEX"]),
        ("ne", &["Nearley"]),
        ("natvis", &["XML"]),
        ("xul", &["XML"]),
        ("pl6", &["Raku"]),
        ("apacheconf", &["ApacheConf"]),
        ("pluginspec", &["Ruby", "XML"]),
        ("chem", &["Pic"]),
        ("al", &["Perl"]),
        ("cr", &["Crystal"]),
        ("zone", &["DNS Zone"]),
        ("gbr", &["Gerber Image"]),
        ("ct", &["XML"]),
        ("dll.config", &["XML"]),
        ("pep", &["Pep8"]),
        ("vbproj", &["XML"]),
        ("pck", &["PLSQL"]),
        ("njk", &["HTML+Django"]),
        ("sml", &["Standard ML"]),
        ("sig", &["Standard ML"]),
        ("bb", &["BlitzBasic", "BitBake"]),
        ("p6", &["Raku"]),
        ("kml", &["XML"]),
        ("pbi", &["PureBasic"]),
        ("shproj", &["XML"]),
        ("gshader", &["GLSL"]),
        ("libsonnet", &["Jsonnet"]),
        ("ol", &["Jolie"]),
        ("ly", &["LilyPond"]),
        ("pyi", &["Python"]),
        ("udo", &["Csound"]),
        ("riot", &["Riot"]),
        ("pd_lua", &["Lua"]),
        ("lagda", &["Literate Agda"]),
        ("psgi", &["Perl"]),
        ("kojo", &["Scala"]),
        ("mako", &["Mako"]),
        ("tmCommand", &["XML Property List"]),
        ("edc", &["Edje Data Collection"]),
        ("dsp", &["Faust", "Microsoft Developer Studio Project"]),
        ("abnf", &["ABNF"]),
        ("abap", &["ABAP"]),
        ("ps1xml", &["XML"]),
        ("cgi", &["Perl", "Python", "Shell"]),
        ("ijs", &["J"]),
        ("numpy", &["NumPy"]),
        ("bibtex", &["BibTeX"]),
        ("ex", &["Elixir"]),
        ("sjs", &["JavaScript"]),
        ("xrl", &["Erlang"]),
        ("pony", &["Pony"]),
        ("gdb", &["GDB"]),
        ("vcxproj", &["XML"]),
        ("matah", &["Stata"]),
        ("liquid", &["Liquid"]),
        ("muf", &["MUF"]),
        ("mdoc", &["Roff", "Roff Manpage"]),
        ("lpr", &["Pascal"]),
        ("mata", &["Stata"]),
        ("roff", &["Roff"]),
        ("fsh", &["GLSL"]),
        ("pub", &["Public Key"]),
        ("mtl", &["Wavefront Material"]),
        ("nasl", &["NASL"]),
        ("asn1", &["ASN.1"]),
        ("n", &["Roff", "Nemerle"]),
        ("xojo_script", &["Xojo"]),
        ("os", &["1C Enterprise"]),
        ("ins", &["TeX"]),
        ("h++", &["C++"]),
        ("wdl", &["wdl"]),
        ("iced", &["CoffeeScript"]),
        ("sh.in", &["Shell"]),
        ("pkgproj", &["XML"]),
        ("scrbl", &["Racket"]),
        ("rockspec", &["Lua"]),
        ("sublime-project", &["JSON with Comments"]),
        ("rktd", &["Racket"]),
        ("lua", &["Lua"]),
        ("c-objdump", &["C-ObjDump"]),
        ("gpt", &["Gerber Image"]),
        ("awk", &["Awk"]),
        ("blade", &["Blade"]),
        ("meta", &["Unity3D Asset"]),
        ("cob", &["COBOL"]),
        ("hh", &["C++", "Hack"]),
        ("no", &["Text"]),
        ("cproject", &["XML"]),
        ("mg", &["Modula-3"]),
        ("pxd", &["Cython"]),
        ("zeek", &["Zeek"]),
        ("admx", &["XML"]),
        ("urs", &["UrWeb"]),
        ("bison", &["Bison"]),
        ("xht", &["HTML"]),
        ("ooc", &["ooc"]),
        ("nimrod", &["Nim"]),
        ("opal", &["Opal"]),
        ("tfvars", &["HCL"]),
        ("bro", &["Zeek"]),
        ("xzap", &["ZAP"]),
        ("markdown", &["Markdown"]),
        ("rdoc", &["RDoc"]),
        ("rno", &["Roff", "RUNOFF"]),
        ("tcc", &["C++"]),
        ("yaml-tmlanguage", &["YAML"]),
        ("pfa", &["PostScript"]),
        ("aux", &["TeX"]),
        ("prw", &["xBase"]),
        ("vhw", &["VHDL"]),
        ("c++", &["C++"]),
        ("tpl", &["Smarty"]),
        ("sqf", &["SQF"]),
        ("hxml", &["HXML"]),
        ("druby", &["Mirah"]),
        ("pyt", &["Python"]),
        ("inl", &["C++"]),
        ("tps", &["PLSQL"]),
        ("6", &["Roff", "Roff Manpage"]),
        ("sh", &["Shell"]),
        ("brd", &["Eagle", "KiCad Legacy Layout"]),
        ("builder", &["Ruby"]),
        ("anim", &["Unity3D Asset"]),
        ("kicad_wks", &["KiCad Layout"]),
        ("gms", &["GAMS"]),
        ("tl", &["Type Language"]),
        ("vb", &["Visual Basic .NET"]),
        ("php5", &["PHP"]),
        ("pde", &["Processing"]),
        ("hic", &["Clojure"]),
        ("pot", &["Gettext Catalog"]),
        ("axd", &["ASP"]),
        ("desktop", &["desktop"]),
        ("xojo_code", &["Xojo"]),
        ("nanorc", &["nanorc"]),
        ("bsl", &["1C Enterprise"]),
        ("j", &["Jasmin", "Objective-J"]),
        ("thrift", &["Thrift"]),
        ("3x", &["Roff", "Roff Manpage"]),
        ("spec", &["RPM Spec", "Ruby", "Python"]),
        ("exs", &["Elixir"]),
        ("dlm", &["IDL"]),
        ("xojo_toolbar", &["Xojo"]),
        ("fnc", &["PLSQL"]),
        ("cfm", &["ColdFusion"]),
        ("phpt", &["PHP"]),
        ("pan", &["Pan"]),
        ("rabl", &["Ruby"]),
        ("gst", &["Gosu"]),
        ("elm", &["Elm"]),
        ("emberscript", &["EmberScript"]),
        ("rhtml", &["RHTML"]),
        ("psc1", &["XML"]),
        ("eml", &["EML"]),
        ("shader", &["GLSL", "ShaderLab"]),
        ("zs", &["ZenScript"]),
        ("svelte", &["Svelte"]),
        ("intr", &["Dylan"]),
        ("mao", &["Mako"]),
        ("jinja", &["HTML+Django"]),
        ("nse", &["Lua"]),
        ("cs", &["Smalltalk", "C#"]),
        ("nf", &["Nextflow"]),
        ("ms", &["MAXScript", "Roff", "Unix Assembly"]),
        ("nim.cfg", &["Nim"]),
        ("prolog", &["Prolog"]),
        ("ston", &["STON"]),
        ("frag", &["GLSL", "JavaScript"]),
        ("sublime-menu", &["JSON with Comments"]),
        ("flex", &["JFlex"]),
        ("eye", &["Ruby"]),
        ("emacs.desktop", &["Emacs Lisp"]),
        ("eam.fs", &["Formatted"]),
        ("html.hl", &["HTML"]),
        ("viw", &["SQL"]),
        ("sh-session", &["ShellSession"]),
        ("webidl", &["WebIDL"]),
        ("pp", &["Pascal", "Puppet"]),
        ("qml", &["QML"]),
        ("gn", &["GN"]),
        ("ss", &["Scheme"]),
        ("3m", &["Roff", "Roff Manpage"]),
        ("kicad_pcb", &["KiCad Layout"]),
        ("wlk", &["Wollok"]),
        ("bal", &["Ballerina"]),
        ("wl", &["Mathematica"]),
        ("monkey", &["Monkey"]),
        ("grt", &["Groovy"]),
        ("eh", &["eC"]),
        ("jsx", &["JSX"]),
        ("watchr", &["Ruby"]),
        ("jl", &["Julia"]),
        ("dylan", &["Dylan"]),
        ("numsc", &["NumPy"]),
        ("maxhelp", &["Max"]),
        ("rsc", &["Rascal"]),
        ("scaml", &["Scaml"]),
        ("sfd", &["Spline Font Database"]),
        ("pgsql", &["PLpgSQL"]),
        ("ceylon", &["Ceylon"]),
        ("rb", &["Ruby"]),
        ("handlebars", &["Handlebars"]),
        ("gi", &["GAP"]),
        ("unity", &["Unity3D Asset"]),
        ("rd", &["R"]),
        ("fp", &["GLSL"]),
        ("tcsh", &["Tcsh"]),
        ("ronn", &["Markdown"]),
        ("vw", &["PLSQL"]),
        ("zig", &["Zig"]),
        ("rdf", &["XML"]),
        ("fsx", &["F#"]),
        ("oxo", &["Ox"]),
        ("yasnippet", &["YASnippet"]),
        ("perl", &["Perl"]),
        ("cmake.in", &["CMake"]),
        ("erb", &["HTML+ERB"]),
        ("wsf", &["XML"]),
        ("zil", &["ZIL"]),
        ("i7x", &["Inform 7"]),
        ("geom", &["GLSL"]),
        ("mss", &["CartoCSS"]),
        ("workbook", &["Markdown"]),
        ("f90", &["Fortran"]),
        ("rq", &["SPARQL"]),
        ("nim", &["Nim"]),
        ("cls", &["ObjectScript", "VBA", "TeX", "Apex", "OpenEdge ABL"]),
        ("dcl", &["Clean"]),
        ("conllu", &["CoNLL-U"]),
        ("es", &["Erlang", "JavaScript"]),
        ("mod", &["XML", "Modula-2", "Linux Kernel Module", "AMPL"]),
        ("golo", &["Golo"]),
        ("css", &["CSS"]),
        ("ph", &["Perl"]),
        ("txt", &["Text"]),
        ("smali", &["Smali"]),
        ("js.erb", &["JavaScript+ERB"]),
        ("gf", &["Grammatical Framework"]),
        ("glade", &["XML"]),
        ("sci", &["Scilab"]),
        ("fsi", &["F#"]),
        ("5", &["Roff", "Roff Manpage"]),
        ("tpb", &["PLSQL"]),
        ("bsv", &["Bluespec"]),
        ("sch", &["KiCad Schematic", "Eagle", "XML", "Scheme"]),
        ("fr", &["Text", "Frege", "Forth"]),
        ("razor", &["HTML+Razor"]),
        ("jss", &["JavaScript"]),
        ("auk", &["Awk"]),
        ("v", &["Coq", "V", "Verilog"]),
        ("qll", &["CodeQL"]),
        ("mirah", &["Mirah"]),
        ("phps", &["PHP"]),
        ("nims", &["Nim"]),
        ("2", &["Roff", "Roff Manpage"]),
        ("gawk", &["Awk"]),
        ("hrl", &["Erlang"]),
        ("oz", &["Oz"]),
        ("dockerfile", &["Dockerfile"]),
        ("nuspec", &["XML"]),
        ("po", &["Gettext Catalog"]),
        ("puml", &["PlantUML"]),
        ("prefab", &["Unity3D Asset"]),
        ("cobol", &["COBOL"]),
        ("mdown", &["Markdown"]),
        ("cl", &["Cool", "OpenCL", "Common Lisp"]),
        ("yml", &["YAML"]),
        ("vala", &["Vala"]),
        ("l", &["Lex", "Roff", "Common Lisp", "PicoLisp"]),
        ("gmx", &["XML"]),
        ("pls", &["PLSQL"]),
        ("mt", &["Mathematica"]),
        ("axml", &["XML"]),
        ("yy", &["JSON", "Yacc"]),
        ("rl", &["Ragel"]),
        ("8xp.txt", &["TI Program"]),
        ("coq", &["Coq"]),
        ("vapi", &["Vala"]),
        ("cl2", &["Clojure"]),
        ("app.src", &["Erlang"]),
        ("slim", &["Slim"]),
        ("xpy", &["Python"]),
        ("3in", &["Roff", "Roff Manpage"]),
        ("sagews", &["Sage"]),
        ("texinfo", &["Texinfo"]),
        ("gradle", &["Gradle"]),
        ("vtt", &["WebVTT"]),
        ("mawk", &["Awk"]),
        ("smk", &["Python"]),
        ("obj", &["Wavefront Object"]),
        ("dm", &["DM"]),
        ("swift", &["Swift"]),
        ("cw", &["Redcode"]),
        ("rtf", &["Rich Text Format"]),
        ("stTheme", &["XML Property List"]),
        ("vert", &["GLSL"]),
        ("sublime-syntax", &["YAML"]),
        ("ads", &["Ada"]),
        ("snip", &["Vim Snippet"]),
        ("command", &["Shell"]),
        ("pkl", &["Pickle"]),
        ("vue", &["Vue"]),
        ("robot", &["RobotFramework"]),
        ("py", &["Python"]),
        ("nr", &["Roff"]),
        ("hlsli", &["HLSL"]),
        ("s", &["Motorola 68K Assembly", "Unix Assembly"]),
        ("epj", &["Ecere Projects"]),
        ("nawk", &["Awk"]),
        ("cql", &["SQL"]),
        ("ik", &["Ioke"]),
        ("sl", &["Slash"]),
        ("xsd", &["XML"]),
        ("erb.deface", &["HTML+ERB"]),
        ("psm1", &["PowerShell"]),
        ("csl", &["XML"]),
        ("_coffee", &["CoffeeScript"]),
        ("kit", &["Kit"]),
        ("eps", &["PostScript"]),
        ("icl", &["Clean"]),
        ("scd", &["SuperCollider"]),
        ("vho", &["VHDL"]),
        ("mediawiki", &["MediaWiki"]),
        ("db2", &["SQLPL"]),
        ("opa", &["Opa"]),
        ("ice", &["Slice", "JSON"]),
        ("ck", &["ChucK"]),
        ("reek", &["YAML"]),
        ("sps", &["Scheme"]),
        ("kt", &["Kotlin"]),
        ("sj", &["Objective-J"]),
        ("pat", &["Max"]),
        ("vhost", &["Nginx", "ApacheConf"]),
        ("ch", &["xBase", "Charity"]),
        ("xquery", &["XQuery"]),
        ("x", &["DirectX 3D File", "Linker Script", "RPC", "Logos"]),
        ("fth", &["Forth"]),
        ("ado", &["Stata"]),
        ("apl", &["APL"]),
        ("cginc", &["HLSL"]),
        ("axs.erb", &["NetLinx+ERB"]),
        ("bmx", &["BlitzMax"]),
        ("3", &["Roff", "Roff Manpage"]),
        ("jsonl", &["JSON"]),
        ("mxml", &["XML"]),
        ("gql", &["GraphQL"]),
        ("ll", &["LLVM"]),
        ("jsproj", &["XML"]),
        ("jsonnet", &["Jsonnet"]),
        ("sas", &["SAS"]),
        ("xaml", &["XML"]),
        ("ino", &["C++"]),
        ("vshader", &["GLSL"]),
        ("sublime-snippet", &["XML"]),
        ("xql", &["XQuery"]),
        ("p6l", &["Raku"]),
        ("litcoffee", &["Literate CoffeeScript"]),
        ("x10", &["X10"]),
        ("ny", &["Common Lisp"]),
        ("json5", &["JSON5"]),
        ("pyp", &["Python"]),
        ("webapp", &["JSON"]),
        ("a51", &["Assembly"]),
        ("pb", &["PureBasic"]),
        ("dart", &["Dart"]),
        ("sra", &["PowerBuilder"]),
        ("launch", &["XML"]),
        ("py3", &["Python"]),
        ("lex", &["Lex"]),
        ("nearley", &["Nearley"]),
        ("cppobjdump", &["Cpp-ObjDump"]),
        ("geo", &["GLSL"]),
        ("wisp", &["wisp"]),
        ("vim", &["Vim script"]),
        ("sublime-build", &["JSON with Comments"]),
        ("uc", &["UnrealScript"]),
        ("thor", &["Ruby"]),
        ("mjs", &["JavaScript"]),
        ("sld", &["Scheme"]),
        ("lol", &["LOLCODE"]),
        ("io", &["Io"]),
        ("ini", &["INI"]),
        ("m", &["M", "Limbo", "Objective-C", "MATLAB", "MUF", "Mercury", "Mathematica"]),
        ("rviz", &["YAML"]),
        ("mrc", &["mIRC Script"]),
        ("storyboard", &["XML"]),
        ("bdf", &["Glyph Bitmap Distribution Format"]),
        ("cpp", &["C++"]),
        ("gtp", &["Gerber Image"]),
        ("uno", &["Uno"]),
        ("gltf", &["JSON"]),
        ("gpb", &["Gerber Image"]),
        ("erl", &["Erlang"]),
        ("rs", &["Rust", "RenderScript"]),
        ("purs", &["PureScript"]),
        ("lgt", &["Logtalk"]),
        ("nlogo", &["NetLogo"]),
        ("yar", &["YARA"]),
        ("psc", &["Papyrus"]),
        ("nut", &["Squirrel"]),
        ("ma", &["Mathematica"]),
        ("nbp", &["Mathematica"]),
        ("vhf", &["VHDL"]),
        ("xspec", &["XML"]),
        ("org", &["Org"]),
        ("rkt", &["Racket"]),
        ("vmb", &["Vim script"]),
        ("pas", &["Pascal"]),
        ("hxx", &["C++"]),
        ("prg", &["xBase"]),
        ("bats", &["Shell"]),
        ("myt", &["Myghty"]),
        ("rst.txt", &["reStructuredText"]),
        ("eliom", &["OCaml"]),
        ("xsjs", &["JavaScript"]),
        ("sbt", &["Scala"]),
        ("wast", &["WebAssembly"]),
        ("avsc", &["JSON"]),
        ("cdf", &["Mathematica"]),
        ("tmac", &["Roff"]),
        ("angelscript", &["AngelScript"]),
        ("arc", &["Arc"]),
        ("xacro", &["XML"]),
        ("man", &["Roff", "Roff Manpage"]),
        ("god", &["Ruby"]),
        ("eclass", &["Gentoo Eclass"]),
        ("4th", &["Forth"]),
        ("cu", &["Cuda"]),
        ("idc", &["C"]),
        ("svg", &["SVG"]),
        ("http", &["HTTP"]),
        ("as", &["AngelScript", "ActionScript"]),
        ("st", &["Smalltalk", "HTML"]),
        ("ltx", &["TeX"]),
        ("mq5", &["MQL5"]),
        ("mir", &["YAML"]),
        ("rsh", &["RenderScript"]),
        ("rbtbar", &["REALbasic"]),
        ("hlsl", &["HLSL"]),
        ("adoc", &["AsciiDoc"]),
        ("yaml.sed", &["YAML"]),
        ("xqy", &["XQuery"]),
        ("mk", &["Makefile"]),
        ("mli", &["OCaml"]),
        ("gcode", &["G-code"]),
        ("dwl", &["DataWeave"]),
        ("el", &["Emacs Lisp"]),
        ("webmanifest", &["JSON"]),
        ("plt", &["Gnuplot"]),
        ("rst", &["reStructuredText"]),
        ("hb", &["Harbour"]),
        ("svh", &["SystemVerilog"]),
        ("odin", &["Odin", "Object Data Instance Notation"]),
        ("ampl", &["AMPL"]),
        ("regex", &["Regular Expression"]),
        ("coffee", &["CoffeeScript"]),
        ("rbuild", &["Ruby"]),
        ("nqp", &["Raku"]),
        ("JSON-tmLanguage", &["JSON"]),
        ("frt", &["Forth"]),
        ("decls", &["BlitzBasic"]),
        ("gml", &["Game Maker Language", "XML", "Gerber Image", "Graph Modeling Language"]),
        ("udf", &["SQL"]),
        ("nproj", &["XML"]),
        ("scpt", &["AppleScript"]),
        ("sats", &["ATS"]),
        ("jsm", &["JavaScript"]),
        ("las", &["Lasso"]),
        ("wxs", &["XML"]),
        ("vhd", &["VHDL"]),
        ("srt", &["SubRip Text", "SRecode Template"]),
        ("pogo", &["PogoScript"]),
        ("sp", &["SourcePawn"]),
        ("zimpl", &["Zimpl"]),
        ("gp", &["Gnuplot"]),
        ("mo", &["Modelica"]),
        ("js", &["JavaScript"]),
        ("pks", &["PLSQL"]),
        ("fan", &["Fantom"]),
        ("jflex", &["JFlex"]),
        ("tmux", &["Shell"]),
        ("vstemplate", &["XML"]),
        ("fy", &["Fancy"]),
        ("gdbinit", &["GDB"]),
        ("vhs", &["VHDL"]),
        ("self", &["Self"]),
        ("pyx", &["Cython"]),
        ("mask", &["Mask", "Unity3D Asset"]),
        ("osm", &["XML"]),
        ("view.lkml", &["LookML"]),
        ("hbs", &["Handlebars"]),
        ("cuh", &["Cuda"]),
        ("ash", &["AGS Script"]),
        ("wat", &["WebAssembly"]),
        ("yacc", &["Yacc"]),
        ("conll", &["CoNLL-U"]),
        ("mly", &["OCaml"]),
        ("props", &["XML"]),
        ("patch", &["Diff"]),
        ("nu", &["Nu"]),
        ("f03", &["Fortran"]),
        ("gnuplot", &["Gnuplot"]),
        ("tea", &["Tea"]),
        ("bf", &["Brainfuck", "HyPhy"]),
        ("duby", &["Mirah"]),
        ("lbx", &["TeX"]),
        ("darcspatch", &["Darcs Patch"]),
        ("tsx", &["TSX", "XML"]),
        ("xbm", &["X BitMap"]),
        ("ada", &["Ada"]),
        ("snippets", &["Vim Snippet"]),
        ("8", &["Roff", "Roff Manpage"]),
        ("vxml", &["XML"]),
        ("ld", &["Linker Script"]),
        ("dfm", &["Pascal"]),
        ("sma", &["Pawn"]),
        ("g4", &["ANTLR"]),
        ("mak", &["Makefile"]),
        ("e", &["Eiffel"]),
        ("rg", &["Rouge"]),
        ("ru", &["Ruby"]),
        ("bash", &["Shell"]),
        ("dotsettings", &["XML"]),
        ("3qt", &["Roff", "Roff Manpage"]),
        ("sco", &["Csound Score"]),
        ("srw", &["PowerBuilder"]),
        ("mathematica", &["Mathematica"]),
        ("gitignore", &["Ignore List"]),
        ("csd", &["Csound Document"]),
        ("xsp-config", &["XPages"]),
        ("ccxml", &["XML"]),
        ("gtl", &["Gerber Image"]),
        ("html", &["HTML"]),
        ("xc", &["XC"]),
        ("fcgi", &["Lua", "Perl", "Ruby", "PHP", "Python", "Shell"]),
        ("xhtml", &["HTML"]),
        ("tml", &["XML"]),
        ("trg", &["PLSQL"]),
        ("qasm", &["OpenQASM"]),
        ("click", &["Click"]),
        ("upc", &["Unified Parallel C"]),
        ("axi.erb", &["NetLinx+ERB"]),
        ("reds", &["Red"]),
        ("fxh", &["HLSL"]),
        ("cbx", &["TeX"]),
        ("xq", &["XQuery"]),
        ("ahk", &["AutoHotkey"]),
        ("me", &["Roff"]),
        ("rest.txt", &["reStructuredText"]),
        ("rs.in", &["Rust"]),
        ("moo", &["Mercury", "Moocode"]),
        ("djs", &["Dogescript"]),
        ("xliff", &["XML"]),
        ("cxx", &["C++"]),
        ("asset", &["Unity3D Asset"]),
        ("lean", &["Lean"]),
        ("gsx", &["Gosu"]),
        ("glslf", &["GLSL"]),
        ("fs", &["F#", "GLSL", "Filterscript", "Forth"]),
        ("cps", &["Component Pascal"]),
        ("scxml", &["XML"]),
        ("resx", &["XML"]),
        ("gbp", &["Gerber Image"]),
        ("lslp", &["LSL"]),
        ("PcbDoc", &["Altium Designer"]),
        ("1x", &["Roff", "Roff Manpage"]),
        ("ql", &["CodeQL"]),
        ("jsb", &["JavaScript"]),
        ("m4", &["M4Sugar", "M4"]),
        ("i", &["Motorola 68K Assembly", "SWIG", "Assembly"]),
        ("aj", &["AspectJ"]),
        ("r3", &["Rebol"]),
        ("lhs", &["Literate Haskell"]),
        ("ux", &["XML"]),
        ("mq4", &["MQL4"]),
        ("ipynb", &["Jupyter Notebook"]),
        ("spin", &["Propeller Spin"]),
        ("cmd", &["Batchfile"]),
        ("rss", &["XML"]),
        ("aspx", &["ASP"]),
        ("cmake", &["CMake"]),
        ("r", &["R", "Rebol"]),
        ("brs", &["Brightscript"]),
        ("cats", &["C"]),
        ("filters", &["XML"]),
        ("iuml", &["PlantUML"]),
        ("pcss", &["PostCSS"]),
        ("mqh", &["MQL4", "MQL5"]),
        ("shen", &["Shen"]),
        ("epsi", &["PostScript"]),
        ("tool", &["Shell"]),
        ("irclog", &["IRC log"]),
        ("snippet", &["Vim Snippet"]),
        ("xlf", &["XML"]),
        ("nit", &["Nit"]),
        ("rbuistate", &["REALbasic"]),
        ("rexx", &["REXX"]),
        ("mustache", &["HTML+Django"]),
        ("gbl", &["Gerber Image"]),
        ("adml", &["XML"]),
        ("ditaval", &["XML"]),
        ("pri", &["QMake"]),
        ("php", &["PHP", "Hack"]),
        ("xojo_menu", &["Xojo"]),
        ("sfproj", &["XML"]),
        ("sublime-keymap", &["JSON with Comments"]),
        ("t", &["Perl", "Raku", "Turing", "Terra"]),
        ("proto", &["Protocol Buffer"]),
        ("fpp", &["Fortran"]),
        ("reg", &["Windows Registry Entries"]),
        ("xmi", &["XML"]),
        ("njs", &["JavaScript"]),
        ("mms", &["Module Management System"]),
        ("ejs", &["EJS"]),
        ("vba", &["VBA", "Vim script"]),
        ("metal", &["Metal"]),
        ("mspec", &["Ruby"]),
        ("vbhtml", &["Visual Basic .NET"]),
        ("jisonlex", &["Jison Lex"]),
        ("pod", &["Pod 6", "Pod"]),
        ("postcss", &["PostCSS"]),
        ("tm", &["Tcl"]),
        ("prc", &["SQL", "PLSQL"]),
        ("mm", &["XML", "Objective-C++"]),
        ("oxh", &["Ox"]),
        ("eliomi", &["OCaml"]),
        ("gto", &["Gerber Image"]),
        ("ecl", &["ECLiPSe", "ECL"]),
        ("asd", &["Common Lisp"]),
        ("3p", &["Roff", "Roff Manpage"]),
        ("sty", &["TeX"]),
        ("mkdown", &["Markdown"]),
        ("tab", &["SQL"]),
        ("clixml", &["XML"]),
        ("c++objdump", &["Cpp-ObjDump"]),
        ("9", &["Roff", "Roff Manpage"]),
        ("yrl", &["Erlang"]),
        ("sru", &["PowerBuilder"]),
        ("cscfg", &["XML"]),
        ("yara", &["YARA"]),
        ("nix", &["Nix"]),
        ("cljx", &["Clojure"]),
        ("jake", &["JavaScript"]),
        ("bas", &["VBA"]),
        ("vsh", &["GLSL"]),
        ("grxml", &["XML"]),
        ("nc", &["nesC"]),
        ("befunge", &["Befunge"]),
        ("w", &["CWeb", "OpenEdge ABL"]),
        ("jq", &["JSONiq"]),
        ("zmpl", &["Zimpl"]),
        ("phtml", &["HTML+PHP"]),
        ("lookml", &["LookML"]),
        ("sql", &["TSQL", "PLpgSQL", "SQL", "SQLPL", "PLSQL"]),
        ("8xk.txt", &["TI Program"]),
        ("fun", &["Standard ML"]),
        ("kid", &["Genshi"]),
        ("eq", &["EQ"]),
        ("sublime-mousemap", &["JSON with Comments"]),
        ("xsjslib", &["JavaScript"]),
        ("csproj", &["XML"]),
        ("vht", &["VHDL"]),
        ("rest", &["reStructuredText"]),
        ("au3", &["AutoIt"]),
        ("php4", &["PHP"]),
        ("lasso9", &["Lasso"]),
        ("pd", &["Pure Data"]),
        ("inc", &["SourcePawn", "Pawn", "C++", "SQL", "NASL", "PHP", "POV-Ray SDL", "Motorola 68K Assembly", "Pascal", "Assembly", "HTML"]),
        ("groovy", &["Groovy"]),
        ("cc", &["C++"]),
        ("gsp", &["Groovy Server Pages"]),
        ("tfstate.backup", &["JSON"]),
        ("bat", &["Batchfile"]),
        ("OutJob", &["Altium Designer"]),
        ("syntax", &["YAML"]),
        ("grace", &["Grace"]),
        ("ruby", &["Ruby"]),
        ("jsonld", &["JSONLD"]),
        ("pro", &["Prolog", "Proguard", "INI", "QMake", "IDL"]),
        ("mkd", &["Markdown"]),
        ("styl", &["Stylus"]),
        ("agc", &["Apollo Guidance Computer"]),
        ("hql", &["HiveQL"]),
        ("dyalog", &["APL"]),
        ("hqf", &["SQF"]),
        ("fshader", &["GLSL"]),
        ("asc", &["Public Key", "AGS Script", "AsciiDoc"]),
        ("haml.deface", &["Haml"]),
        ("p", &["Gnuplot", "OpenEdge ABL"]),
        ("sublime-theme", &["JSON with Comments"]),
        ("adp", &["Tcl"]),
        ("tpp", &["C++"]),
        ("ttl", &["Turtle"]),
        ("aug", &["Augeas"]),
        ("dpr", &["Pascal"]),
        ("re", &["C++", "Reason"]),
        ("tesc", &["GLSL"]),
        ("pig", &["PigLatin"]),
        ("xojo_window", &["Xojo"]),
        ("rktl", &["Racket"]),
        ("sass", &["Sass"]),
        ("gemspec", &["Ruby"]),
        ("ddl", &["SQL", "PLSQL"]),
        ("latte", &["Latte"]),
        ("vcl", &["VCL"]),
        ("fx", &["HLSL", "FLUX"]),
        ("tst", &["GAP", "Scilab"]),
        ("yml.mysql", &["YAML"]),
        ("ebuild", &["Gentoo Ebuild"]),
        ("3pm", &["Roff", "Roff Manpage"]),
        ("cocci", &["SmPL"]),
        ("csv", &["CSV"]),
        ("hxsl", &["Haxe"]),
        ("minid", &["MiniD"]),
        ("hats", &["ATS"]),
        ("x68", &["Motorola 68K Assembly"]),
        ("xi", &["Logos"]),
        ("lmi", &["Python"]),
        ("targets", &["XML"]),
        ("xml.dist", &["XML"]),
        ("ksh", &["Shell"]),
        ("ml", &["OCaml"]),
        ("vbs", &["VBScript"]),
        ("mysql", &["SQL"]),
        ("mlir", &["MLIR"]),
        ("pbt", &["PowerBuilder"]),
        ("cshtml", &["HTML+Razor"]),
        ("ctp", &["PHP"]),
        ("pov", &["POV-Ray SDL"]),
        ("haml", &["Haml"]),
        ("jinja2", &["HTML+Django"]),
        ("mu", &["mupad"]),
        ("xml", &["XML"]),
        ("sublime_metrics", &["JSON with Comments"]),
        ("srdf", &["XML"]),
        ("p6m", &["Raku"]),
        ("cxx-objdump", &["Cpp-ObjDump"]),
        ("owl", &["Web Ontology Language"]),
        ("oxygene", &["Oxygene"]),
        ("q", &["HiveQL", "q"]),
        ("xojo_report", &["Xojo"]),
        ("xm", &["Logos"]),
        ("hhi", &["Hack"]),
        ("red", &["Red"]),
        ("orc", &["Csound"]),
        ("gitconfig", &["Git Config"]),
        ("pic", &["Pic"]),
        ("ml4", &["OCaml"]),
        ("afm", &["Adobe Font Metrics"]),
        ("xpm", &["X PixMap"]),
        ("hpp", &["C++"]),
        ("xsl", &["XSLT"]),
        ("d", &["D", "Makefile", "DTrace"]),
        ("ni", &["Inform 7"]),
        ("podspec", &["Ruby"]),
        ("gko", &["Gerber Image"]),
        ("c++-objdump", &["Cpp-ObjDump"]),
        ("asp", &["ASP"]),
        ("xpl", &["XProc"]),
        ("nimble", &["Nim"]),
        ("apib", &["API Blueprint"]),
        ("x3d", &["XML"]),
        ("f95", &["Fortran"]),
        ("logtalk", &["Logtalk"]),
        ("cp", &["C++", "Component Pascal"]),
        ("weechatlog", &["IRC log"]),
        ("hlean", &["Lean"]),
        ("boo", &["Boo"]),
        ("pac", &["JavaScript"]),
        ("matlab", &["MATLAB"]),
        ("capnp", &["Cap\'n Proto"]),
        ("gbs", &["Gerber Image"]),
        ("hcl", &["HCL"]),
        ("zep", &["Zephir"]),
        ("twig", &["Twig"]),
        ("gap", &["GAP"]),
        ("agda", &["Agda"]),
        ("es6", &["JavaScript"]),
        ("lsl", &["LSL"]),
        ("nginxconf", &["Nginx"]),
        ("topojson", &["JSON"]),
        ("chs", &["C2hs Haskell"]),
        ("numpyw", &["NumPy"]),
        ("scad", &["OpenSCAD"]),
        ("go", &["Go"]),
        ("muse", &["Muse"]),
        ("sthlp", &["Stata"]),
        ("pug", &["Pug"]),
        ("p4", &["P4"]),
        ("dot", &["Graphviz (DOT)"]),
        ("podsl", &["Common Lisp"]),
        ("8xp", &["TI Program"]),
        ("gtpl", &["Groovy"]),
        ("pm", &["Perl", "Raku", "X PixMap"]),
        ("zcml", &["XML"]),
        ("gd", &["GAP", "GDScript"]),
        ("jelly", &["XML"]),
        ("idr", &["Idris"]),
        ("4", &["Roff", "Roff Manpage"]),
        ("gni", &["GN"]),
        ("opencl", &["OpenCL"]),
        ("applescript", &["AppleScript"]),
        ("dpatch", &["Darcs Patch"]),
        ("ec", &["eC"]),
        ("java", &["Java"]),
        ("lektorproject", &["INI"]),
        ("pod6", &["Pod 6"]),
        ("pytb", &["Python traceback"]),
        ("pasm", &["Parrot Assembly"]),
        ("jade", &["Pug"]),
        ("zpl", &["Zimpl"]),
        ("lfe", &["LFE"]),
        ("csx", &["C#"]),
        ("_ls", &["LiveScript"]),
        ("cljscm", &["Clojure"]),
        ("marko", &["Marko"]),
        ("ML", &["Standard ML"]),
        ("edn", &["edn"]),
        ("rbbas", &["REALbasic"]),
        ("fancypack", &["Fancy"]),
        ("tcl", &["Tcl"]),
        ("txi", &["Texinfo"]),
        ("sv", &["SystemVerilog"]),
        ("cson", &["CSON"]),
        ("raml", &["RAML"]),
        ("nasm", &["Assembly"]),
        ("c", &["C"]),
        ("axi", &["NetLinx"]),
        ("rbfrm", &["REALbasic"]),
        ("rsx", &["R"]),
        ("ihlp", &["Stata"]),
        ("vhi", &["VHDL"]),
        ("gyp", &["Python"]),
        ("kicad_mod", &["KiCad Layout"]),
        ("rbres", &["REALbasic"]),
        ("odd", &["XML"]),
        ("rbmnu", &["REALbasic"]),
        ("iss", &["Inno Setup"]),
        ("txl", &["TXL"]),
        ("axs", &["NetLinx"]),
        ("bbx", &["TeX"]),
        ("ascx", &["ASP"]),
        ("yyp", &["JSON"]),
        ("mxt", &["Max"]),
        ("mll", &["OCaml"]),
        ("textile", &["Textile"]),
        ("vark", &["Gosu"]),
        ("hsc", &["Haskell"]),
        ("nl", &["NL", "NewLisp"]),
        ("regexp", &["Regular Expression"]),
        ("ecr", &["HTML+ECR"]),
        ("mcr", &["MAXScript"]),
        ("aw", &["PHP"]),
        ("texi", &["Texinfo"]),
        ("tex", &["TeX"]),
        ("lvproj", &["LabVIEW"]),
        ("lisp", &["NewLisp", "Common Lisp"]),
        ("wsgi", &["Python"]),
        ("fst", &["F*"]),
        ("rbx", &["Ruby"]),
        ("xproj", &["XML"]),
        ("cljc", &["Clojure"]),
        ("jsfl", &["JavaScript"]),
        ("gypi", &["Python"]),
        ("ily", &["LilyPond"]),
        ("hx", &["Haxe"]),
        ("vhdl", &["VHDL"]),
        ("parrot", &["Parrot"]),
        ("dita", &["XML"]),
        ("lidr", &["Idris"]),
        ("mbox", &["EML"]),
        ("cnc", &["G-code"]),
        ("hs", &["Haskell"]),
        ("1in", &["Roff", "Roff Manpage"]),
        ("clp", &["CLIPS"]),
        ("cfg", &["HAProxy", "INI"]),
        ("clw", &["Clarion"]),
        ("f", &["Filebench WML", "Forth", "Fortran"]),
        ("8xk", &["TI Program"]),
        ("wlua", &["Lua"]),
        ("plot", &["Gnuplot"]),
        ("cjs", &["JavaScript"]),
        ("dyl", &["Dylan"]),
        ("lds", &["Linker Script"]),
        ("xs", &["XS"]),
        ("asy", &["Asymptote", "LTspice Symbol"]),
        ("smt2", &["SMT"]),
        ("wxl", &["XML"]),
        ("objdump", &["ObjDump"]),
        ("ebnf", &["EBNF"]),
        ("sce", &["Scilab"]),
        ("arpa", &["DNS Zone"]),
        ("ig", &["Modula-3"]),
        ("xib", &["XML"]),
        ("ipf", &["IGOR Pro"]),
        ("lid", &["Dylan"]),
        ("gvy", &["Groovy"]),
        ("frg", &["GLSL"]),
        ("ninja", &["Ninja"]),
        ("plsql", &["PLSQL"]),
        ("pascal", &["Pascal"]),
        ("mdx", &["Markdown"]),
        ("gco", &["G-code"]),
        ("pir", &["Parrot Internal Representation"]),
        ("jsp", &["Java Server Pages"]),
        ("wiki", &["MediaWiki"]),
        ("plantuml", &["PlantUML"]),
        ("maxpat", &["Max"]),
        ("ncl", &["NCL", "XML", "Text"]),
        ("frx", &["VBA"]),
        ("cpp-objdump", &["Cpp-ObjDump"]),
        ("ccp", &["COBOL"]),
        ("graphql", &["GraphQL"]),
        ("eb", &["Easybuild"]),
        ("tla", &["TLA"]),
        ("zap", &["ZAP"]),
        ("wsdl", &["XML"]),
        ("plx", &["Perl"]),
        ("yang", &["YANG"]),
        ("dhall", &["Dhall"]),
        ("vsixmanifest", &["XML"]),
        ("ipp", &["C++"]),
        ("workflow", &["XML", "HCL"]),
        ("flf", &["FIGlet Font"]),
        ("gnu", &["Gnuplot"]),
        ("cy", &["Cycript"]),
        ("bones", &["JavaScript"]),
        ("geojson", &["JSON"]),
        ("xproc", &["XProc"]),
        ("rmd", &["RMarkdown"]),
        ("tmTheme", &["XML Property List"]),
        ("asax", &["ASP"]),
        ("plb", &["PLSQL"]),
        ("vh", &["SystemVerilog"]),
        ("moon", &["MoonScript"]),
        ("reb", &["Rebol"]),
        ("zsh", &["Shell"]),
        ("tac", &["Python"]),
        ("sublime-macro", &["JSON with Comments"]),
    ]),
};

