static FILENAMES: phf::Map<&'static str, &'static str> =
::phf::Map {
    key: 3213172566270843353,
    disps: ::phf::Slice::Static(&[
        (0, 119),
        (7, 60),
        (0, 3),
        (0, 94),
        (6, 89),
        (1, 1),
        (0, 4),
        (1, 225),
        (5, 238),
        (0, 198),
        (0, 28),
        (0, 73),
        (4, 103),
        (6, 247),
        (0, 7),
        (45, 104),
        (0, 101),
        (2, 48),
        (8, 57),
        (0, 143),
        (0, 245),
        (0, 3),
        (0, 14),
        (10, 27),
        (1, 243),
        (7, 112),
        (2, 195),
        (0, 4),
        (3, 21),
        (0, 0),
        (0, 14),
        (0, 0),
        (0, 0),
        (0, 0),
        (0, 9),
        (0, 52),
        (0, 1),
        (0, 150),
        (5, 208),
        (0, 18),
        (5, 200),
        (37, 118),
        (0, 87),
        (0, 5),
        (0, 47),
        (0, 4),
        (0, 28),
        (22, 90),
        (0, 42),
        (34, 212),
        (4, 209),
        (7, 143),
    ]),
    entries: ::phf::Slice::Static(&[
        ("package.use.stable.mask", "Text"),
        ("Cargo.lock", "TOML"),
        ("BUCK", "Starlark"),
        (".php_cs", "PHP"),
        ("Kbuild", "Makefile"),
        ("Jarfile", "Ruby"),
        (".XCompose", "XCompose"),
        ("man", "Shell"),
        (".jslintrc", "JSON with Comments"),
        ("COPYING", "Text"),
        ("_emacs", "Emacs Lisp"),
        (".jscsrc", "JSON with Comments"),
        ("mkfile", "Makefile"),
        (".project", "XML"),
        ("DEPS", "Python"),
        ("9fs", "Shell"),
        (".stylelintignore", "Ignore List"),
        ("fonts.alias", "X Font Directory Index"),
        ("zprofile", "Shell"),
        ("sshd_config", "SSH Config"),
        ("dir_colors", "dircolors"),
        (".abbrev_defs", "Emacs Lisp"),
        (".tern-config", "JSON"),
        ("Slakefile", "LiveScript"),
        ("composer.lock", "JSON"),
        ("Guardfile", "Ruby"),
        ("mmn", "Roff"),
        ("Makefile.frag", "Makefile"),
        ("bash_aliases", "Shell"),
        (".factor-rc", "Factor"),
        (".cproject", "XML"),
        ("zlogout", "Shell"),
        ("README.mysql", "Text"),
        ("m3makefile", "Quake"),
        ("click.me", "Text"),
        ("troffrc-end", "Roff"),
        ("tsconfig.json", "JSON with Comments"),
        (".spacemacs", "Emacs Lisp"),
        (".dir_colors", "dircolors"),
        ("wscript", "Python"),
        ("LICENSE", "Text"),
        ("BUILD.bazel", "Starlark"),
        ("Makefile.in", "Makefile"),
        ("eqnrc", "Roff"),
        ("SConscript", "Python"),
        ("buildfile", "Ruby"),
        (".gitignore", "Ignore List"),
        (".dockerignore", "Ignore List"),
        (".gitattributes", "Git Attributes"),
        ("cabal.config", "Cabal Config"),
        ("fonts.scale", "X Font Directory Index"),
        ("starfield", "Tcl"),
        ("keep.me", "Text"),
        (".htmlhintrc", "JSON"),
        ("SConstruct", "Python"),
        (".php", "PHP"),
        (".vscodeignore", "Ignore List"),
        (".arcconfig", "JSON"),
        ("_dir_colors", "dircolors"),
        ("meson.build", "Meson"),
        (".luacheckrc", "Lua"),
        ("zshrc", "Shell"),
        ("makefile", "Makefile"),
        ("_dircolors", "dircolors"),
        ("cshrc", "Shell"),
        ("package.use.mask", "Text"),
        ("firestore.rules", "Cloud Firestore Security Rules"),
        ("mcmod.info", "JSON"),
        ("Fakefile", "Fancy"),
        ("_curlrc", "cURL Config"),
        ("Snakefile", "Python"),
        ("INSTALL", "Text"),
        ("apache2.conf", "ApacheConf"),
        ("bash_logout", "Shell"),
        ("NEWS", "Text"),
        (".bash_aliases", "Shell"),
        ("GNUmakefile", "Makefile"),
        ("build.xml", "Ant Build System"),
        (".zshrc", "Shell"),
        ("README.1ST", "Text"),
        (".tern-project", "JSON"),
        ("Cask", "Emacs Lisp"),
        ("Notebook", "Jupyter Notebook"),
        ("FONTLOG", "Text"),
        (".zlogin", "Shell"),
        ("abbrev_defs", "Emacs Lisp"),
        ("meson_options.txt", "Meson"),
        (".atomignore", "Ignore List"),
        ("README.me", "Text"),
        ("go.mod", "Text"),
        (".clang-format", "YAML"),
        (".emacs.desktop", "Emacs Lisp"),
        ("NuGet.config", "XML"),
        (".factor-boot-rc", "Factor"),
        (".dircolors", "dircolors"),
        ("gitignore_global", "Ignore List"),
        ("fp-lib-table", "KiCad Layout"),
        ("Gemfile.lock", "Ruby"),
        ("ant.xml", "Ant Build System"),
        ("App.config", "XML"),
        (".gitconfig", "Git Config"),
        ("encodings.dir", "X Font Directory Index"),
        ("CMakeLists.txt", "CMake"),
        (".bash_profile", "Shell"),
        ("packages.config", "XML"),
        ("Makefile.am", "Makefile"),
        (".classpath", "XML"),
        ("gradlew", "Shell"),
        ("DIR_COLORS", "dircolors"),
        ("gvimrc", "Vim script"),
        ("Makefile.boot", "Makefile"),
        ("descrip.mms", "Module Management System"),
        (".gnus", "Emacs Lisp"),
        ("configure.ac", "M4Sugar"),
        (".npmrc", "NPM Config"),
        ("haproxy.cfg", "HAProxy"),
        ("expr-dist", "R"),
        ("inputrc", "Readline Config"),
        (".nvimrc", "Vim script"),
        ("Project.ede", "Emacs Lisp"),
        (".babelignore", "Ignore List"),
        ("bash_profile", "Shell"),
        (".login", "Shell"),
        ("package.mask", "Text"),
        ("nextflow.config", "Nextflow"),
        ("ssh-config", "SSH Config"),
        ("mmt", "Roff"),
        (".cshrc", "Shell"),
        (".bash_history", "Shell"),
        (".profile", "Shell"),
        ("cabal.project", "Cabal Config"),
        ("Makefile.wat", "Makefile"),
        ("Jakefile", "JavaScript"),
        (".gvimrc", "Vim script"),
        ("cpanfile", "Perl"),
        ("nanorc", "nanorc"),
        ("bashrc", "Shell"),
        ("ack", "Perl"),
        ("sshconfig", "SSH Config"),
        (".gclient", "Python"),
        ("Rexfile", "Perl"),
        ("xcompose", "XCompose"),
        (".bashrc", "Shell"),
        (".zlogout", "Shell"),
        (".vimrc", "Vim script"),
        ("Cakefile", "CoffeeScript"),
        (".eslintrc.json", "JSON with Comments"),
        ("sshconfig.snip", "SSH Config"),
        ("Makefile.inc", "Makefile"),
        (".zprofile", "Shell"),
        (".nanorc", "nanorc"),
        ("readme.1st", "Text"),
        ("Gopkg.lock", "TOML"),
        ("BUILD", "Starlark"),
        ("Web.Debug.config", "XML"),
        ("Phakefile", "PHP"),
        ("APKBUILD", "Alpine Abuild"),
        ("COPYRIGHT.regex", "Text"),
        ("nim.cfg", "Nim"),
        ("troffrc", "Roff"),
        (".htaccess", "ApacheConf"),
        ("Buildfile", "Ruby"),
        ("mix.lock", "Elixir"),
        (".irbrc", "Ruby"),
        ("rebar.lock", "Erlang"),
        (".inputrc", "Readline Config"),
        ("Gemfile", "Ruby"),
        ("Dangerfile", "Ruby"),
        ("vimrc", "Vim script"),
        (".pryrc", "Ruby"),
        (".zshenv", "Shell"),
        (".coffeelintignore", "Ignore List"),
        ("profile", "Shell"),
        ("rebar.config.lock", "Erlang"),
        ("PKGBUILD", "Shell"),
        (".wgetrc", "Wget Config"),
        ("Appraisals", "Ruby"),
        ("COPYING.regex", "Text"),
        ("ROOT", "Isabelle ROOT"),
        (".Rprofile", "R"),
        ("WORKSPACE", "Starlark"),
        ("owh", "Tcl"),
        ("makefile.sco", "Makefile"),
        ("fonts.dir", "X Font Directory Index"),
        ("Web.config", "XML"),
        ("nvimrc", "Vim script"),
        ("BSDmakefile", "Makefile"),
        ("use.stable.mask", "Text"),
        (".gemrc", "YAML"),
        ("use.mask", "Text"),
        ("Jenkinsfile", "Groovy"),
        ("Makefile.PL", "Perl"),
        (".curlrc", "cURL Config"),
        ("zlogin", "Shell"),
        ("Modulefile", "Puppet"),
        ("gitignore-global", "Ignore List"),
        ("ssh_config", "SSH Config"),
        ("jsconfig.json", "JSON with Comments"),
        (".eslintignore", "Ignore List"),
        ("INSTALL.mysql", "Text"),
        ("Brewfile", "Ruby"),
        (".bash_logout", "Shell"),
        (".watchmanconfig", "JSON"),
        (".npmignore", "Ignore List"),
        ("Snapfile", "Ruby"),
        ("Thorfile", "Ruby"),
        ("Rakefile", "Ruby"),
        (".php_cs.dist", "PHP"),
        ("Podfile", "Ruby"),
        ("Settings.StyleCop", "XML"),
        ("sshd-config", "SSH Config"),
        (".prettierignore", "Ignore List"),
        ("ld.script", "Linker Script"),
        ("rebar.config", "Erlang"),
        (".gitmodules", "Git Config"),
        ("delete.me", "Text"),
        ("XCompose", "XCompose"),
        ("zshenv", "Shell"),
        ("Berksfile", "Ruby"),
        ("Puppetfile", "Ruby"),
        (".viper", "Emacs Lisp"),
        ("glide.lock", "YAML"),
        ("login", "Shell"),
        ("Dockerfile", "Dockerfile"),
        ("Capfile", "Ruby"),
        ("Deliverfile", "Ruby"),
        (".emacs", "Emacs Lisp"),
        ("read.me", "Text"),
        ("pom.xml", "Maven POM"),
        ("Emakefile", "Erlang"),
        (".editorconfig", "EditorConfig"),
        ("contents.lr", "Markdown"),
        (".jshintrc", "JSON with Comments"),
        ("Mavenfile", "Ruby"),
        (".cvsignore", "Ignore List"),
        ("yarn.lock", "YAML"),
        ("Fastfile", "Ruby"),
        ("nginx.conf", "Nginx"),
        ("language-configuration.json", "JSON with Comments"),
        (".bzrignore", "Ignore List"),
        ("Nukefile", "Nu"),
        ("riemann.config", "Clojure"),
        ("buildozer.spec", "INI"),
        ("descrip.mmk", "Module Management System"),
        ("m3overrides", "Quake"),
        ("go.sum", "Text"),
        (".babelrc", "JSON with Comments"),
        ("Vagrantfile", "Ruby"),
        ("Web.Release.config", "XML"),
        (".gn", "GN"),
        ("LICENSE.mysql", "Text"),
        (".nodemonignore", "Ignore List"),
        ("_vimrc", "Vim script"),
        (".clang-tidy", "YAML"),
        ("Makefile", "Makefile"),
        ("httpd.conf", "ApacheConf"),
        ("test.me", "Text"),
    ]),
};

