static FILENAMES: phf::Map<&'static str, &'static str> =
::phf::Map {
    key: 15467950696543387533,
    disps: &[
        (2, 15),
        (0, 1),
        (0, 36),
        (0, 6),
        (0, 24),
        (0, 50),
        (0, 4),
        (1, 2),
        (0, 11),
        (0, 37),
        (0, 67),
        (1, 191),
        (0, 75),
        (8, 177),
        (0, 60),
        (0, 96),
        (0, 5),
        (0, 0),
        (0, 2),
        (0, 4),
        (7, 176),
        (1, 89),
        (11, 124),
        (0, 3),
        (1, 10),
        (0, 60),
        (0, 76),
        (2, 83),
        (0, 104),
        (0, 13),
        (0, 0),
        (3, 41),
        (0, 0),
        (0, 3),
        (0, 63),
        (0, 127),
        (1, 201),
        (3, 183),
        (10, 242),
        (0, 84),
        (2, 9),
        (0, 127),
        (6, 164),
        (0, 168),
        (3, 0),
        (0, 75),
        (4, 190),
        (0, 1),
        (0, 129),
        (3, 43),
        (0, 20),
        (12, 55),
    ],
    entries: &[
        ("NEWS", "Text"),
        ("ld.script", "Linker Script"),
        ("Thorfile", "Ruby"),
        (".project", "XML"),
        ("nim.cfg", "Nim"),
        (".nvimrc", "Vim script"),
        (".emacs", "Emacs Lisp"),
        ("fonts.dir", "X Font Directory Index"),
        (".npmignore", "Ignore List"),
        ("Settings.StyleCop", "XML"),
        ("ssh-config", "SSH Config"),
        (".php_cs", "PHP"),
        (".eslintrc.json", "JSON with Comments"),
        (".npmrc", "NPM Config"),
        ("contents.lr", "Markdown"),
        (".factor-rc", "Factor"),
        ("Rakefile", "Ruby"),
        ("COPYING", "Text"),
        ("Makefile.inc", "Makefile"),
        (".gnus", "Emacs Lisp"),
        ("m3makefile", "Quake"),
        ("Makefile.wat", "Makefile"),
        ("nginx.conf", "Nginx"),
        ("Phakefile", "PHP"),
        ("_emacs", "Emacs Lisp"),
        (".jslintrc", "JSON with Comments"),
        ("mix.lock", "Elixir"),
        ("package.mask", "Text"),
        (".jscsrc", "JSON with Comments"),
        ("firestore.rules", "Cloud Firestore Security Rules"),
        ("nanorc", "nanorc"),
        ("_curlrc", "cURL Config"),
        (".cproject", "XML"),
        ("man", "Shell"),
        ("PKGBUILD", "Shell"),
        ("Gemfile.lock", "Ruby"),
        (".arcconfig", "JSON"),
        ("gitignore_global", "Ignore List"),
        ("jsconfig.json", "JSON with Comments"),
        (".clang-tidy", "YAML"),
        ("nextflow.config", "Nextflow"),
        ("rebar.config.lock", "Erlang"),
        ("cabal.project", "Cabal Config"),
        ("DEPS", "Python"),
        ("gitignore-global", "Ignore List"),
        ("Jenkinsfile", "Groovy"),
        ("Rexfile", "Perl"),
        ("descrip.mmk", "Module Management System"),
        ("abbrev_defs", "Emacs Lisp"),
        ("Vagrantfile", "Ruby"),
        (".zshrc", "Shell"),
        ("troffrc-end", "Roff"),
        ("packages.config", "XML"),
        (".dockerignore", "Ignore List"),
        ("XCompose", "XCompose"),
        (".profile", "Shell"),
        (".zlogout", "Shell"),
        ("zlogout", "Shell"),
        ("mcmod.info", "JSON"),
        ("buildfile", "Ruby"),
        ("rebar.config", "Erlang"),
        ("sshd_config", "SSH Config"),
        ("bash_logout", "Shell"),
        ("use.stable.mask", "Text"),
        ("glide.lock", "YAML"),
        (".eslintignore", "Ignore List"),
        (".clang-format", "YAML"),
        (".atomignore", "Ignore List"),
        ("Project.ede", "Emacs Lisp"),
        ("APKBUILD", "Alpine Abuild"),
        ("README.mysql", "Text"),
        ("Web.Release.config", "XML"),
        (".luacheckrc", "Lua"),
        ("keep.me", "Text"),
        ("bash_aliases", "Shell"),
        (".classpath", "XML"),
        ("gradlew", "Shell"),
        ("LICENSE.mysql", "Text"),
        ("cpanfile", "Perl"),
        ("owh", "Tcl"),
        (".bashrc", "Shell"),
        (".irbrc", "Ruby"),
        (".inputrc", "Readline Config"),
        ("Web.Debug.config", "XML"),
        ("dir_colors", "dircolors"),
        ("bashrc", "Shell"),
        (".zlogin", "Shell"),
        ("Cargo.lock", "TOML"),
        (".gn", "GN"),
        ("xcompose", "XCompose"),
        ("Snakefile", "Python"),
        ("mkfile", "Makefile"),
        ("go.sum", "Text"),
        ("Capfile", "Ruby"),
        (".abbrev_defs", "Emacs Lisp"),
        ("nvimrc", "Vim script"),
        ("Fastfile", "Ruby"),
        ("build.xml", "Ant Build System"),
        ("makefile.sco", "Makefile"),
        (".babelrc", "JSON with Comments"),
        ("rebar.lock", "Erlang"),
        ("read.me", "Text"),
        ("tsconfig.json", "JSON with Comments"),
        ("Gopkg.lock", "TOML"),
        ("vimrc", "Vim script"),
        (".coffeelintignore", "Ignore List"),
        ("ROOT", "Isabelle ROOT"),
        ("Fakefile", "Fancy"),
        ("ssh_config", "SSH Config"),
        ("NuGet.config", "XML"),
        ("Makefile.in", "Makefile"),
        (".wgetrc", "Wget Config"),
        ("pom.xml", "Maven POM"),
        ("buildozer.spec", "INI"),
        ("SConscript", "Python"),
        ("Makefile.boot", "Makefile"),
        ("Cakefile", "CoffeeScript"),
        ("Snapfile", "Ruby"),
        ("encodings.dir", "X Font Directory Index"),
        (".bzrignore", "Ignore List"),
        ("Jakefile", "JavaScript"),
        (".tern-project", "JSON"),
        ("delete.me", "Text"),
        ("starfield", "Tcl"),
        ("Brewfile", "Ruby"),
        (".watchmanconfig", "JSON"),
        ("httpd.conf", "ApacheConf"),
        ("use.mask", "Text"),
        ("COPYRIGHT.regex", "Text"),
        (".tern-config", "JSON"),
        ("Slakefile", "LiveScript"),
        ("9fs", "Shell"),
        ("Makefile", "Makefile"),
        ("Dockerfile", "Dockerfile"),
        ("cabal.config", "Cabal Config"),
        ("FONTLOG", "Text"),
        (".gvimrc", "Vim script"),
        ("Makefile.am", "Makefile"),
        ("_dircolors", "dircolors"),
        ("App.config", "XML"),
        (".spacemacs", "Emacs Lisp"),
        (".php", "PHP"),
        ("sshconfig", "SSH Config"),
        ("zlogin", "Shell"),
        ("LICENSE", "Text"),
        ("INSTALL.mysql", "Text"),
        ("Podfile", "Ruby"),
        ("cshrc", "Shell"),
        ("Deliverfile", "Ruby"),
        (".viper", "Emacs Lisp"),
        ("Dangerfile", "Ruby"),
        ("README.1ST", "Text"),
        ("composer.lock", "JSON"),
        ("Cask", "Emacs Lisp"),
        ("Notebook", "Jupyter Notebook"),
        ("WORKSPACE", "Starlark"),
        ("Jarfile", "Ruby"),
        ("fonts.scale", "X Font Directory Index"),
        ("m3overrides", "Quake"),
        (".dir_colors", "dircolors"),
        ("haproxy.cfg", "HAProxy"),
        (".gitattributes", "Git Attributes"),
        ("troffrc", "Roff"),
        ("wscript", "Python"),
        ("Mavenfile", "Ruby"),
        ("Makefile.frag", "Makefile"),
        (".nodemonignore", "Ignore List"),
        ("riemann.config", "Clojure"),
        (".vscodeignore", "Ignore List"),
        (".bash_aliases", "Shell"),
        (".prettierignore", "Ignore List"),
        ("SConstruct", "Python"),
        (".php_cs.dist", "PHP"),
        ("meson_options.txt", "Meson"),
        ("Makefile.PL", "Perl"),
        ("Nukefile", "Nu"),
        ("BUILD", "Starlark"),
        (".cshrc", "Shell"),
        ("ack", "Perl"),
        (".bash_logout", "Shell"),
        (".emacs.desktop", "Emacs Lisp"),
        (".stylelintignore", "Ignore List"),
        (".curlrc", "cURL Config"),
        ("GNUmakefile", "Makefile"),
        ("Appraisals", "Ruby"),
        (".htaccess", "ApacheConf"),
        ("mmn", "Roff"),
        ("zshrc", "Shell"),
        ("sshd-config", "SSH Config"),
        ("DIR_COLORS", "dircolors"),
        ("BSDmakefile", "Makefile"),
        ("zprofile", "Shell"),
        (".gemrc", "YAML"),
        ("configure.ac", "M4Sugar"),
        (".pryrc", "Ruby"),
        (".babelignore", "Ignore List"),
        ("login", "Shell"),
        ("eqnrc", "Roff"),
        ("meson.build", "Meson"),
        (".htmlhintrc", "JSON"),
        (".factor-boot-rc", "Factor"),
        ("apache2.conf", "ApacheConf"),
        ("mmt", "Roff"),
        (".dircolors", "dircolors"),
        ("BUILD.bazel", "Starlark"),
        ("test.me", "Text"),
        (".gclient", "Python"),
        ("click.me", "Text"),
        ("expr-dist", "R"),
        ("_dir_colors", "dircolors"),
        (".bash_profile", "Shell"),
        ("yarn.lock", "YAML"),
        (".login", "Shell"),
        ("README.me", "Text"),
        ("descrip.mms", "Module Management System"),
        (".gitmodules", "Git Config"),
        ("Emakefile", "Erlang"),
        (".gitignore", "Ignore List"),
        ("CMakeLists.txt", "CMake"),
        (".XCompose", "XCompose"),
        ("go.mod", "Text"),
        ("Puppetfile", "Ruby"),
        ("Kbuild", "Makefile"),
        (".zprofile", "Shell"),
        ("language-configuration.json", "JSON with Comments"),
        ("Guardfile", "Ruby"),
        (".jshintrc", "JSON with Comments"),
        ("Web.config", "XML"),
        ("Buildfile", "Ruby"),
        ("gvimrc", "Vim script"),
        ("Berksfile", "Ruby"),
        (".Rprofile", "R"),
        ("makefile", "Makefile"),
        ("profile", "Shell"),
        (".gitconfig", "Git Config"),
        ("fonts.alias", "X Font Directory Index"),
        ("_vimrc", "Vim script"),
        ("readme.1st", "Text"),
        (".bash_history", "Shell"),
        ("bash_profile", "Shell"),
        (".zshenv", "Shell"),
        ("INSTALL", "Text"),
        ("Gemfile", "Ruby"),
        ("inputrc", "Readline Config"),
        ("package.use.mask", "Text"),
        ("package.use.stable.mask", "Text"),
        ("COPYING.regex", "Text"),
        ("zshenv", "Shell"),
        ("fp-lib-table", "KiCad Layout"),
        ("ant.xml", "Ant Build System"),
        (".editorconfig", "EditorConfig"),
        (".nanorc", "nanorc"),
        ("sshconfig.snip", "SSH Config"),
        ("BUCK", "Starlark"),
        ("Modulefile", "Puppet"),
        (".cvsignore", "Ignore List"),
        (".vimrc", "Vim script"),
    ],
};

