static INTERPRETERS: phf::Map<&'static str, &[&str]> =
::phf::Map {
    key: 12913932095322966823,
    disps: &[
        (0, 18),
        (0, 0),
        (0, 112),
        (0, 0),
        (0, 13),
        (10, 92),
        (0, 1),
        (0, 86),
        (1, 11),
        (4, 23),
        (0, 24),
        (0, 96),
        (0, 1),
        (0, 116),
        (3, 100),
        (33, 40),
        (0, 11),
        (0, 3),
        (8, 26),
        (0, 90),
        (3, 4),
        (24, 51),
        (78, 58),
        (0, 4),
        (77, 45),
    ],
    entries: &[
        ("crystal", &["Crystal"]),
        ("sed", &["sed"]),
        ("escript", &["Erlang"]),
        ("ecl", &["Common Lisp"]),
        ("parrot", &["Parrot Internal Representation", "Parrot Assembly"]),
        ("php", &["PHP"]),
        ("pike", &["Pike"]),
        ("cperl", &["Perl"]),
        ("nextflow", &["Nextflow"]),
        ("lsl", &["LSL"]),
        ("stp", &["SMT"]),
        ("clisp", &["Common Lisp"]),
        ("swipl", &["Prolog"]),
        ("pwsh", &["PowerShell"]),
        ("csh", &["Tcsh"]),
        ("openrc-run", &["OpenRC runscript"]),
        ("pdksh", &["Shell"]),
        ("osascript", &["AppleScript"]),
        ("mathsat5", &["SMT"]),
        ("ioke", &["Ioke"]),
        ("ts-node", &["TypeScript"]),
        ("gerbview", &["Gerber Image"]),
        ("python3", &["Python"]),
        ("rhino", &["JavaScript"]),
        ("gn", &["GN"]),
        ("jruby", &["Ruby"]),
        ("dash", &["Shell"]),
        ("rbx", &["Ruby"]),
        ("gjs", &["JavaScript"]),
        ("ocamlscript", &["OCaml"]),
        ("minised", &["sed"]),
        ("sclang", &["SuperCollider"]),
        ("ksh", &["Shell"]),
        ("zsh", &["Shell"]),
        ("mmi", &["Mercury"]),
        ("ash", &["Shell"]),
        ("opensmt", &["SMT"]),
        ("instantfpc", &["Pascal"]),
        ("julia", &["Julia"]),
        ("aplx", &["APL"]),
        ("dyalog", &["APL"]),
        ("makeinfo", &["Texinfo"]),
        ("racket", &["Racket"]),
        ("chicken", &["Scheme"]),
        ("tcsh", &["Tcsh"]),
        ("hy", &["Hy"]),
        ("qjs", &["JavaScript"]),
        ("scheme", &["Scheme"]),
        ("sh", &["Shell"]),
        ("jolie", &["Jolie"]),
        ("ccl", &["Common Lisp"]),
        ("regina", &["REXX"]),
        ("js", &["JavaScript"]),
        ("ocaml", &["Reason", "OCaml"]),
        ("runhaskell", &["Haskell"]),
        ("gnuplot", &["Gnuplot"]),
        ("scsynth", &["SuperCollider"]),
        ("nush", &["Nu"]),
        ("gawk", &["Awk"]),
        ("chakra", &["JavaScript"]),
        ("csi", &["Scheme"]),
        ("Rscript", &["R"]),
        ("scala", &["Scala"]),
        ("nawk", &["Awk"]),
        ("io", &["Io"]),
        ("gsed", &["sed"]),
        ("guile", &["Scheme"]),
        ("yices2", &["SMT"]),
        ("apl", &["APL"]),
        ("raku", &["Raku"]),
        ("bash", &["Shell"]),
        ("bigloo", &["Scheme"]),
        ("coffee", &["CoffeeScript"]),
        ("pil", &["PicoLisp"]),
        ("python", &["Python"]),
        ("v8-shell", &["JavaScript"]),
        ("rune", &["E"]),
        ("dart", &["Dart"]),
        ("wish", &["Tcl"]),
        ("qmake", &["QMake"]),
        ("elixir", &["Elixir"]),
        ("sbcl", &["Common Lisp"]),
        ("python2", &["Python"]),
        ("mksh", &["Shell"]),
        ("boolector", &["SMT"]),
        ("deno", &["TypeScript"]),
        ("v8", &["JavaScript"]),
        ("rake", &["Ruby"]),
        ("macruby", &["Ruby"]),
        ("gosh", &["Scheme"]),
        ("mawk", &["Awk"]),
        ("picolisp", &["PicoLisp"]),
        ("ssed", &["sed"]),
        ("tclsh", &["Tcl"]),
        ("verit", &["SMT"]),
        ("smtinterpol", &["SMT"]),
        ("node", &["JavaScript"]),
        ("r6rs", &["Scheme"]),
        ("jconsole", &["J"]),
        ("groovy", &["Groovy"]),
        ("perl6", &["Pod 6", "Raku"]),
        ("asy", &["Asymptote"]),
        ("ruby", &["Ruby"]),
        ("smt-rat", &["SMT"]),
        ("yap", &["Prolog"]),
        ("dtrace", &["DTrace"]),
        ("rexx", &["REXX"]),
        ("perl", &["Pod", "Perl"]),
        ("gerbv", &["Gerber Image"]),
        ("rakudo", &["Raku"]),
        ("lisp", &["Common Lisp"]),
        ("lua", &["Terra", "Lua"]),
        ("z3", &["SMT"]),
        ("cwl-runner", &["Common Workflow Language"]),
        ("ocamlrun", &["OCaml"]),
        ("fish", &["fish"]),
        ("moon", &["MoonScript"]),
        ("make", &["Makefile"]),
        ("newlisp", &["NewLisp"]),
        ("awk", &["Awk"]),
        ("tcc", &["C"]),
        ("cvc4", &["SMT"]),
        ("rc", &["Shell"]),
        ("d8", &["JavaScript"]),
    ],
};

