static LANGUAGE_INFO: phf::Map<&'static str, Language> =
::phf::Map {
    key: 3213172566270843353,
    disps: ::phf::Slice::Static(&[
        (0, 296),
        (0, 5),
        (0, 213),
        (0, 231),
        (0, 0),
        (1, 3),
        (0, 4),
        (0, 287),
        (0, 39),
        (1, 173),
        (0, 292),
        (0, 133),
        (0, 15),
        (0, 150),
        (0, 2),
        (0, 128),
        (0, 1),
        (1, 24),
        (0, 0),
        (0, 38),
        (0, 259),
        (0, 2),
        (0, 128),
        (0, 110),
        (0, 2),
        (0, 48),
        (0, 5),
        (0, 24),
        (0, 166),
        (4, 164),
        (0, 8),
        (0, 2),
        (0, 3),
        (6, 260),
        (0, 61),
        (0, 539),
        (0, 39),
        (0, 0),
        (0, 45),
        (0, 219),
        (0, 157),
        (0, 54),
        (0, 288),
        (0, 393),
        (0, 179),
        (3, 362),
        (0, 210),
        (0, 146),
        (0, 112),
        (0, 69),
        (0, 1),
        (0, 165),
        (0, 318),
        (3, 108),
        (0, 1),
        (0, 12),
        (1, 101),
        (2, 129),
        (0, 0),
        (0, 487),
        (1, 131),
        (1, 10),
        (0, 1),
        (0, 82),
        (0, 3),
        (0, 39),
        (2, 538),
        (0, 158),
        (0, 33),
        (10, 217),
        (0, 3),
        (1, 289),
        (0, 19),
        (1, 125),
        (0, 0),
        (0, 227),
        (0, 10),
        (0, 385),
        (0, 368),
        (0, 206),
        (0, 534),
        (0, 461),
        (0, 112),
        (10, 157),
        (5, 403),
        (0, 118),
        (1, 5),
        (0, 2),
        (1, 335),
        (0, 229),
        (0, 2),
        (0, 0),
        (0, 268),
        (1, 211),
        (0, 3),
        (0, 1),
        (0, 33),
        (5, 260),
        (1, 4),
        (3, 67),
        (0, 95),
        (3, 331),
        (7, 110),
        (0, 208),
        (0, 240),
        (0, 93),
        (8, 211),
        (1, 136),
        (6, 438),
        (8, 523),
        (1, 243),
    ]),
    entries: ::phf::Slice::Static(&[
        ("R", Language { name: "R", language_type: LanguageType::Programming }),
        ("Ant Build System", Language { name: "Ant Build System", language_type: LanguageType::Data }),
        ("Smali", Language { name: "Smali", language_type: LanguageType::Programming }),
        ("C++", Language { name: "C++", language_type: LanguageType::Programming }),
        ("JFlex", Language { name: "JFlex", language_type: LanguageType::Programming }),
        ("HAProxy", Language { name: "HAProxy", language_type: LanguageType::Data }),
        ("JSON", Language { name: "JSON", language_type: LanguageType::Data }),
        ("Ruby", Language { name: "Ruby", language_type: LanguageType::Programming }),
        ("Myghty", Language { name: "Myghty", language_type: LanguageType::Programming }),
        ("Proguard", Language { name: "Proguard", language_type: LanguageType::Data }),
        ("Elm", Language { name: "Elm", language_type: LanguageType::Programming }),
        ("Xojo", Language { name: "Xojo", language_type: LanguageType::Programming }),
        ("CSV", Language { name: "CSV", language_type: LanguageType::Data }),
        ("RDoc", Language { name: "RDoc", language_type: LanguageType::Prose }),
        ("Inno Setup", Language { name: "Inno Setup", language_type: LanguageType::Programming }),
        ("Cirru", Language { name: "Cirru", language_type: LanguageType::Programming }),
        ("Pan", Language { name: "Pan", language_type: LanguageType::Programming }),
        ("Tcsh", Language { name: "Tcsh", language_type: LanguageType::Programming }),
        ("Dylan", Language { name: "Dylan", language_type: LanguageType::Programming }),
        ("Pic", Language { name: "Pic", language_type: LanguageType::Markup }),
        ("Jsonnet", Language { name: "Jsonnet", language_type: LanguageType::Programming }),
        ("Objective-J", Language { name: "Objective-J", language_type: LanguageType::Programming }),
        ("COBOL", Language { name: "COBOL", language_type: LanguageType::Programming }),
        ("Ignore List", Language { name: "Ignore List", language_type: LanguageType::Data }),
        ("Clarion", Language { name: "Clarion", language_type: LanguageType::Programming }),
        ("PureBasic", Language { name: "PureBasic", language_type: LanguageType::Programming }),
        ("Csound Score", Language { name: "Csound Score", language_type: LanguageType::Programming }),
        ("Jison Lex", Language { name: "Jison Lex", language_type: LanguageType::Programming }),
        ("Crystal", Language { name: "Crystal", language_type: LanguageType::Programming }),
        ("SystemVerilog", Language { name: "SystemVerilog", language_type: LanguageType::Programming }),
        ("Linux Kernel Module", Language { name: "Linux Kernel Module", language_type: LanguageType::Data }),
        ("ObjDump", Language { name: "ObjDump", language_type: LanguageType::Data }),
        ("PHP", Language { name: "PHP", language_type: LanguageType::Programming }),
        ("SCSS", Language { name: "SCSS", language_type: LanguageType::Markup }),
        ("YAML", Language { name: "YAML", language_type: LanguageType::Data }),
        ("IRC log", Language { name: "IRC log", language_type: LanguageType::Data }),
        ("RobotFramework", Language { name: "RobotFramework", language_type: LanguageType::Programming }),
        ("Unix Assembly", Language { name: "Unix Assembly", language_type: LanguageType::Programming }),
        ("Grace", Language { name: "Grace", language_type: LanguageType::Programming }),
        ("Nemerle", Language { name: "Nemerle", language_type: LanguageType::Programming }),
        ("RMarkdown", Language { name: "RMarkdown", language_type: LanguageType::Prose }),
        ("Altium Designer", Language { name: "Altium Designer", language_type: LanguageType::Data }),
        ("Boo", Language { name: "Boo", language_type: LanguageType::Programming }),
        ("Ox", Language { name: "Ox", language_type: LanguageType::Programming }),
        ("P4", Language { name: "P4", language_type: LanguageType::Programming }),
        ("XML Property List", Language { name: "XML Property List", language_type: LanguageType::Data }),
        ("ApacheConf", Language { name: "ApacheConf", language_type: LanguageType::Data }),
        ("Windows Registry Entries", Language { name: "Windows Registry Entries", language_type: LanguageType::Data }),
        ("Arc", Language { name: "Arc", language_type: LanguageType::Programming }),
        ("GraphQL", Language { name: "GraphQL", language_type: LanguageType::Data }),
        ("Text", Language { name: "Text", language_type: LanguageType::Prose }),
        ("Papyrus", Language { name: "Papyrus", language_type: LanguageType::Programming }),
        ("Wget Config", Language { name: "Wget Config", language_type: LanguageType::Data }),
        ("VBScript", Language { name: "VBScript", language_type: LanguageType::Programming }),
        ("Vim Snippet", Language { name: "Vim Snippet", language_type: LanguageType::Markup }),
        ("LookML", Language { name: "LookML", language_type: LanguageType::Programming }),
        ("SRecode Template", Language { name: "SRecode Template", language_type: LanguageType::Markup }),
        ("CMake", Language { name: "CMake", language_type: LanguageType::Programming }),
        ("SubRip Text", Language { name: "SubRip Text", language_type: LanguageType::Data }),
        ("ASN.1", Language { name: "ASN.1", language_type: LanguageType::Data }),
        ("Nginx", Language { name: "Nginx", language_type: LanguageType::Data }),
        ("Regular Expression", Language { name: "Regular Expression", language_type: LanguageType::Data }),
        ("Literate Agda", Language { name: "Literate Agda", language_type: LanguageType::Programming }),
        ("Cap\'n Proto", Language { name: "Cap'n Proto", language_type: LanguageType::Programming }),
        ("STON", Language { name: "STON", language_type: LanguageType::Data }),
        ("Object Data Instance Notation", Language { name: "Object Data Instance Notation", language_type: LanguageType::Data }),
        ("Moocode", Language { name: "Moocode", language_type: LanguageType::Programming }),
        ("REALbasic", Language { name: "REALbasic", language_type: LanguageType::Programming }),
        ("Grammatical Framework", Language { name: "Grammatical Framework", language_type: LanguageType::Programming }),
        ("XSLT", Language { name: "XSLT", language_type: LanguageType::Programming }),
        ("Gherkin", Language { name: "Gherkin", language_type: LanguageType::Programming }),
        ("Nit", Language { name: "Nit", language_type: LanguageType::Programming }),
        ("Mathematica", Language { name: "Mathematica", language_type: LanguageType::Programming }),
        ("TOML", Language { name: "TOML", language_type: LanguageType::Data }),
        ("Scilab", Language { name: "Scilab", language_type: LanguageType::Programming }),
        ("Perl", Language { name: "Perl", language_type: LanguageType::Programming }),
        ("C-ObjDump", Language { name: "C-ObjDump", language_type: LanguageType::Data }),
        ("fish", Language { name: "fish", language_type: LanguageType::Programming }),
        ("Java Properties", Language { name: "Java Properties", language_type: LanguageType::Data }),
        ("Brightscript", Language { name: "Brightscript", language_type: LanguageType::Programming }),
        ("Cycript", Language { name: "Cycript", language_type: LanguageType::Programming }),
        ("Public Key", Language { name: "Public Key", language_type: LanguageType::Data }),
        ("Go", Language { name: "Go", language_type: LanguageType::Programming }),
        ("Makefile", Language { name: "Makefile", language_type: LanguageType::Programming }),
        ("G-code", Language { name: "G-code", language_type: LanguageType::Programming }),
        ("LLVM", Language { name: "LLVM", language_type: LanguageType::Programming }),
        ("reStructuredText", Language { name: "reStructuredText", language_type: LanguageType::Prose }),
        ("cURL Config", Language { name: "cURL Config", language_type: LanguageType::Data }),
        ("Yacc", Language { name: "Yacc", language_type: LanguageType::Programming }),
        ("Pug", Language { name: "Pug", language_type: LanguageType::Markup }),
        ("Metal", Language { name: "Metal", language_type: LanguageType::Programming }),
        ("NASL", Language { name: "NASL", language_type: LanguageType::Programming }),
        ("MQL5", Language { name: "MQL5", language_type: LanguageType::Programming }),
        ("Alpine Abuild", Language { name: "Alpine Abuild", language_type: LanguageType::Programming }),
        ("ATS", Language { name: "ATS", language_type: LanguageType::Programming }),
        ("Slim", Language { name: "Slim", language_type: LanguageType::Markup }),
        ("LabVIEW", Language { name: "LabVIEW", language_type: LanguageType::Programming }),
        ("Scheme", Language { name: "Scheme", language_type: LanguageType::Programming }),
        ("V", Language { name: "V", language_type: LanguageType::Programming }),
        ("Tcl", Language { name: "Tcl", language_type: LanguageType::Programming }),
        ("Zeek", Language { name: "Zeek", language_type: LanguageType::Programming }),
        ("EML", Language { name: "EML", language_type: LanguageType::Data }),
        ("GDScript", Language { name: "GDScript", language_type: LanguageType::Programming }),
        ("Markdown", Language { name: "Markdown", language_type: LanguageType::Prose }),
        ("MQL4", Language { name: "MQL4", language_type: LanguageType::Programming }),
        ("Vue", Language { name: "Vue", language_type: LanguageType::Markup }),
        ("Gradle", Language { name: "Gradle", language_type: LanguageType::Data }),
        ("Logtalk", Language { name: "Logtalk", language_type: LanguageType::Programming }),
        ("Self", Language { name: "Self", language_type: LanguageType::Programming }),
        ("GAP", Language { name: "GAP", language_type: LanguageType::Programming }),
        ("SQF", Language { name: "SQF", language_type: LanguageType::Programming }),
        ("Groovy Server Pages", Language { name: "Groovy Server Pages", language_type: LanguageType::Programming }),
        ("Marko", Language { name: "Marko", language_type: LanguageType::Markup }),
        ("TSX", Language { name: "TSX", language_type: LanguageType::Programming }),
        ("Cloud Firestore Security Rules", Language { name: "Cloud Firestore Security Rules", language_type: LanguageType::Data }),
        ("PureScript", Language { name: "PureScript", language_type: LanguageType::Programming }),
        ("Open Policy Agent", Language { name: "Open Policy Agent", language_type: LanguageType::Programming }),
        ("Graphviz (DOT)", Language { name: "Graphviz (DOT)", language_type: LanguageType::Data }),
        ("OpenSCAD", Language { name: "OpenSCAD", language_type: LanguageType::Programming }),
        ("DIGITAL Command Language", Language { name: "DIGITAL Command Language", language_type: LanguageType::Programming }),
        ("MiniD", Language { name: "MiniD", language_type: LanguageType::Programming }),
        ("C2hs Haskell", Language { name: "C2hs Haskell", language_type: LanguageType::Programming }),
        ("Monkey", Language { name: "Monkey", language_type: LanguageType::Programming }),
        ("F*", Language { name: "F*", language_type: LanguageType::Programming }),
        ("Unity3D Asset", Language { name: "Unity3D Asset", language_type: LanguageType::Data }),
        ("GCC Machine Description", Language { name: "GCC Machine Description", language_type: LanguageType::Programming }),
        ("PogoScript", Language { name: "PogoScript", language_type: LanguageType::Programming }),
        ("CSS", Language { name: "CSS", language_type: LanguageType::Markup }),
        ("1C Enterprise", Language { name: "1C Enterprise", language_type: LanguageType::Programming }),
        ("ooc", Language { name: "ooc", language_type: LanguageType::Programming }),
        ("ChucK", Language { name: "ChucK", language_type: LanguageType::Programming }),
        ("SmPL", Language { name: "SmPL", language_type: LanguageType::Programming }),
        ("Cuda", Language { name: "Cuda", language_type: LanguageType::Programming }),
        ("Modula-2", Language { name: "Modula-2", language_type: LanguageType::Programming }),
        ("Literate CoffeeScript", Language { name: "Literate CoffeeScript", language_type: LanguageType::Programming }),
        ("Elixir", Language { name: "Elixir", language_type: LanguageType::Programming }),
        ("ZIL", Language { name: "ZIL", language_type: LanguageType::Programming }),
        ("Faust", Language { name: "Faust", language_type: LanguageType::Programming }),
        ("PLSQL", Language { name: "PLSQL", language_type: LanguageType::Programming }),
        ("Squirrel", Language { name: "Squirrel", language_type: LanguageType::Programming }),
        ("Agda", Language { name: "Agda", language_type: LanguageType::Programming }),
        ("Git Config", Language { name: "Git Config", language_type: LanguageType::Data }),
        ("LilyPond", Language { name: "LilyPond", language_type: LanguageType::Programming }),
        ("Coq", Language { name: "Coq", language_type: LanguageType::Programming }),
        ("Cython", Language { name: "Cython", language_type: LanguageType::Programming }),
        ("Pep8", Language { name: "Pep8", language_type: LanguageType::Programming }),
        ("FIGlet Font", Language { name: "FIGlet Font", language_type: LanguageType::Data }),
        ("ZAP", Language { name: "ZAP", language_type: LanguageType::Programming }),
        ("Red", Language { name: "Red", language_type: LanguageType::Programming }),
        ("Parrot", Language { name: "Parrot", language_type: LanguageType::Programming }),
        ("Pure Data", Language { name: "Pure Data", language_type: LanguageType::Data }),
        ("Type Language", Language { name: "Type Language", language_type: LanguageType::Data }),
        ("Apex", Language { name: "Apex", language_type: LanguageType::Programming }),
        ("J", Language { name: "J", language_type: LanguageType::Programming }),
        ("COLLADA", Language { name: "COLLADA", language_type: LanguageType::Data }),
        ("Jupyter Notebook", Language { name: "Jupyter Notebook", language_type: LanguageType::Markup }),
        ("CSON", Language { name: "CSON", language_type: LanguageType::Data }),
        ("TI Program", Language { name: "TI Program", language_type: LanguageType::Programming }),
        ("SWIG", Language { name: "SWIG", language_type: LanguageType::Programming }),
        ("Nim", Language { name: "Nim", language_type: LanguageType::Programming }),
        ("TLA", Language { name: "TLA", language_type: LanguageType::Programming }),
        ("YANG", Language { name: "YANG", language_type: LanguageType::Data }),
        ("X Font Directory Index", Language { name: "X Font Directory Index", language_type: LanguageType::Data }),
        ("Ada", Language { name: "Ada", language_type: LanguageType::Programming }),
        ("GAML", Language { name: "GAML", language_type: LanguageType::Programming }),
        ("HTML+Django", Language { name: "HTML+Django", language_type: LanguageType::Markup }),
        ("Mask", Language { name: "Mask", language_type: LanguageType::Markup }),
        ("Common Workflow Language", Language { name: "Common Workflow Language", language_type: LanguageType::Programming }),
        ("VCL", Language { name: "VCL", language_type: LanguageType::Programming }),
        ("Eagle", Language { name: "Eagle", language_type: LanguageType::Data }),
        ("PostCSS", Language { name: "PostCSS", language_type: LanguageType::Markup }),
        ("OpenStep Property List", Language { name: "OpenStep Property List", language_type: LanguageType::Data }),
        ("EJS", Language { name: "EJS", language_type: LanguageType::Markup }),
        ("UrWeb", Language { name: "UrWeb", language_type: LanguageType::Programming }),
        ("ObjectScript", Language { name: "ObjectScript", language_type: LanguageType::Programming }),
        ("LFE", Language { name: "LFE", language_type: LanguageType::Programming }),
        ("HTML+ECR", Language { name: "HTML+ECR", language_type: LanguageType::Markup }),
        ("JavaScript", Language { name: "JavaScript", language_type: LanguageType::Programming }),
        ("Reason", Language { name: "Reason", language_type: LanguageType::Programming }),
        ("BibTeX", Language { name: "BibTeX", language_type: LanguageType::Markup }),
        ("Starlark", Language { name: "Starlark", language_type: LanguageType::Programming }),
        ("Module Management System", Language { name: "Module Management System", language_type: LanguageType::Programming }),
        ("TSQL", Language { name: "TSQL", language_type: LanguageType::Programming }),
        ("RUNOFF", Language { name: "RUNOFF", language_type: LanguageType::Markup }),
        ("Cool", Language { name: "Cool", language_type: LanguageType::Programming }),
        ("ECLiPSe", Language { name: "ECLiPSe", language_type: LanguageType::Programming }),
        ("HiveQL", Language { name: "HiveQL", language_type: LanguageType::Programming }),
        ("XS", Language { name: "XS", language_type: LanguageType::Programming }),
        ("UnrealScript", Language { name: "UnrealScript", language_type: LanguageType::Programming }),
        ("XCompose", Language { name: "XCompose", language_type: LanguageType::Data }),
        ("Lasso", Language { name: "Lasso", language_type: LanguageType::Programming }),
        ("Java", Language { name: "Java", language_type: LanguageType::Programming }),
        ("MUF", Language { name: "MUF", language_type: LanguageType::Programming }),
        ("Java Server Pages", Language { name: "Java Server Pages", language_type: LanguageType::Programming }),
        ("Zig", Language { name: "Zig", language_type: LanguageType::Programming }),
        ("HTTP", Language { name: "HTTP", language_type: LanguageType::Data }),
        ("Jolie", Language { name: "Jolie", language_type: LanguageType::Programming }),
        ("CoffeeScript", Language { name: "CoffeeScript", language_type: LanguageType::Programming }),
        ("HTML+ERB", Language { name: "HTML+ERB", language_type: LanguageType::Markup }),
        ("Bison", Language { name: "Bison", language_type: LanguageType::Programming }),
        ("JSON5", Language { name: "JSON5", language_type: LanguageType::Data }),
        ("BitBake", Language { name: "BitBake", language_type: LanguageType::Programming }),
        ("Python console", Language { name: "Python console", language_type: LanguageType::Programming }),
        ("Rust", Language { name: "Rust", language_type: LanguageType::Programming }),
        ("C", Language { name: "C", language_type: LanguageType::Programming }),
        ("Creole", Language { name: "Creole", language_type: LanguageType::Prose }),
        ("Idris", Language { name: "Idris", language_type: LanguageType::Programming }),
        ("Web Ontology Language", Language { name: "Web Ontology Language", language_type: LanguageType::Data }),
        ("OpenEdge ABL", Language { name: "OpenEdge ABL", language_type: LanguageType::Programming }),
        ("POV-Ray SDL", Language { name: "POV-Ray SDL", language_type: LanguageType::Programming }),
        ("RPM Spec", Language { name: "RPM Spec", language_type: LanguageType::Data }),
        ("KiCad Schematic", Language { name: "KiCad Schematic", language_type: LanguageType::Data }),
        ("mIRC Script", Language { name: "mIRC Script", language_type: LanguageType::Programming }),
        ("Forth", Language { name: "Forth", language_type: LanguageType::Programming }),
        ("HXML", Language { name: "HXML", language_type: LanguageType::Data }),
        ("Cpp-ObjDump", Language { name: "Cpp-ObjDump", language_type: LanguageType::Data }),
        ("M4", Language { name: "M4", language_type: LanguageType::Programming }),
        ("Rich Text Format", Language { name: "Rich Text Format", language_type: LanguageType::Markup }),
        ("Parrot Internal Representation", Language { name: "Parrot Internal Representation", language_type: LanguageType::Programming }),
        ("Asymptote", Language { name: "Asymptote", language_type: LanguageType::Programming }),
        ("PlantUML", Language { name: "PlantUML", language_type: LanguageType::Data }),
        ("GLSL", Language { name: "GLSL", language_type: LanguageType::Programming }),
        ("Assembly", Language { name: "Assembly", language_type: LanguageType::Programming }),
        ("E", Language { name: "E", language_type: LanguageType::Programming }),
        ("X PixMap", Language { name: "X PixMap", language_type: LanguageType::Data }),
        ("Fantom", Language { name: "Fantom", language_type: LanguageType::Programming }),
        ("MLIR", Language { name: "MLIR", language_type: LanguageType::Programming }),
        ("Haskell", Language { name: "Haskell", language_type: LanguageType::Programming }),
        ("REXX", Language { name: "REXX", language_type: LanguageType::Programming }),
        ("X10", Language { name: "X10", language_type: LanguageType::Programming }),
        ("Clean", Language { name: "Clean", language_type: LanguageType::Programming }),
        ("Odin", Language { name: "Odin", language_type: LanguageType::Programming }),
        ("q", Language { name: "q", language_type: LanguageType::Programming }),
        ("INI", Language { name: "INI", language_type: LanguageType::Data }),
        ("NPM Config", Language { name: "NPM Config", language_type: LanguageType::Data }),
        ("Turtle", Language { name: "Turtle", language_type: LanguageType::Data }),
        ("AsciiDoc", Language { name: "AsciiDoc", language_type: LanguageType::Prose }),
        ("PigLatin", Language { name: "PigLatin", language_type: LanguageType::Programming }),
        ("SugarSS", Language { name: "SugarSS", language_type: LanguageType::Markup }),
        ("LiveScript", Language { name: "LiveScript", language_type: LanguageType::Programming }),
        ("Pawn", Language { name: "Pawn", language_type: LanguageType::Programming }),
        ("Clojure", Language { name: "Clojure", language_type: LanguageType::Programming }),
        ("Hy", Language { name: "Hy", language_type: LanguageType::Programming }),
        ("Csound Document", Language { name: "Csound Document", language_type: LanguageType::Programming }),
        ("Erlang", Language { name: "Erlang", language_type: LanguageType::Programming }),
        ("JSX", Language { name: "JSX", language_type: LanguageType::Programming }),
        ("Roff", Language { name: "Roff", language_type: LanguageType::Markup }),
        ("edn", Language { name: "edn", language_type: LanguageType::Data }),
        ("Fancy", Language { name: "Fancy", language_type: LanguageType::Programming }),
        ("ECL", Language { name: "ECL", language_type: LanguageType::Programming }),
        ("GN", Language { name: "GN", language_type: LanguageType::Data }),
        ("Filterscript", Language { name: "Filterscript", language_type: LanguageType::Programming }),
        ("Csound", Language { name: "Csound", language_type: LanguageType::Programming }),
        ("Handlebars", Language { name: "Handlebars", language_type: LanguageType::Markup }),
        ("Swift", Language { name: "Swift", language_type: LanguageType::Programming }),
        ("Emacs Lisp", Language { name: "Emacs Lisp", language_type: LanguageType::Programming }),
        ("Propeller Spin", Language { name: "Propeller Spin", language_type: LanguageType::Programming }),
        ("Limbo", Language { name: "Limbo", language_type: LanguageType::Programming }),
        ("Diff", Language { name: "Diff", language_type: LanguageType::Data }),
        ("Redcode", Language { name: "Redcode", language_type: LanguageType::Programming }),
        ("Oxygene", Language { name: "Oxygene", language_type: LanguageType::Programming }),
        ("Lean", Language { name: "Lean", language_type: LanguageType::Programming }),
        ("Befunge", Language { name: "Befunge", language_type: LanguageType::Programming }),
        ("Nearley", Language { name: "Nearley", language_type: LanguageType::Programming }),
        ("Riot", Language { name: "Riot", language_type: LanguageType::Markup }),
        ("RHTML", Language { name: "RHTML", language_type: LanguageType::Markup }),
        ("RPC", Language { name: "RPC", language_type: LanguageType::Programming }),
        ("EmberScript", Language { name: "EmberScript", language_type: LanguageType::Programming }),
        ("AGS Script", Language { name: "AGS Script", language_type: LanguageType::Programming }),
        ("WebAssembly", Language { name: "WebAssembly", language_type: LanguageType::Programming }),
        ("Genshi", Language { name: "Genshi", language_type: LanguageType::Programming }),
        ("SQLPL", Language { name: "SQLPL", language_type: LanguageType::Programming }),
        ("4D", Language { name: "4D", language_type: LanguageType::Programming }),
        ("Protocol Buffer", Language { name: "Protocol Buffer", language_type: LanguageType::Data }),
        ("Microsoft Developer Studio Project", Language { name: "Microsoft Developer Studio Project", language_type: LanguageType::Data }),
        ("PostScript", Language { name: "PostScript", language_type: LanguageType::Markup }),
        ("Gosu", Language { name: "Gosu", language_type: LanguageType::Programming }),
        ("Pod 6", Language { name: "Pod 6", language_type: LanguageType::Prose }),
        ("SAS", Language { name: "SAS", language_type: LanguageType::Programming }),
        ("Wollok", Language { name: "Wollok", language_type: LanguageType::Programming }),
        ("KiCad Layout", Language { name: "KiCad Layout", language_type: LanguageType::Data }),
        ("Gentoo Ebuild", Language { name: "Gentoo Ebuild", language_type: LanguageType::Programming }),
        ("Org", Language { name: "Org", language_type: LanguageType::Prose }),
        ("AutoIt", Language { name: "AutoIt", language_type: LanguageType::Programming }),
        ("Quake", Language { name: "Quake", language_type: LanguageType::Programming }),
        ("desktop", Language { name: "desktop", language_type: LanguageType::Data }),
        ("OpenType Feature File", Language { name: "OpenType Feature File", language_type: LanguageType::Data }),
        ("Fortran", Language { name: "Fortran", language_type: LanguageType::Programming }),
        ("Brainfuck", Language { name: "Brainfuck", language_type: LanguageType::Programming }),
        ("Ioke", Language { name: "Ioke", language_type: LanguageType::Programming }),
        ("Hack", Language { name: "Hack", language_type: LanguageType::Programming }),
        ("PowerBuilder", Language { name: "PowerBuilder", language_type: LanguageType::Programming }),
        ("ABNF", Language { name: "ABNF", language_type: LanguageType::Data }),
        ("NetLogo", Language { name: "NetLogo", language_type: LanguageType::Programming }),
        ("Shen", Language { name: "Shen", language_type: LanguageType::Programming }),
        ("RAML", Language { name: "RAML", language_type: LanguageType::Markup }),
        ("Readline Config", Language { name: "Readline Config", language_type: LanguageType::Data }),
        ("Io", Language { name: "Io", language_type: LanguageType::Programming }),
        ("XML", Language { name: "XML", language_type: LanguageType::Data }),
        ("Pickle", Language { name: "Pickle", language_type: LanguageType::Data }),
        ("Muse", Language { name: "Muse", language_type: LanguageType::Prose }),
        ("Solidity", Language { name: "Solidity", language_type: LanguageType::Programming }),
        ("Rouge", Language { name: "Rouge", language_type: LanguageType::Programming }),
        ("LSL", Language { name: "LSL", language_type: LanguageType::Programming }),
        ("SSH Config", Language { name: "SSH Config", language_type: LanguageType::Data }),
        ("VHDL", Language { name: "VHDL", language_type: LanguageType::Programming }),
        ("Motorola 68K Assembly", Language { name: "Motorola 68K Assembly", language_type: LanguageType::Programming }),
        ("Smalltalk", Language { name: "Smalltalk", language_type: LanguageType::Programming }),
        ("Logos", Language { name: "Logos", language_type: LanguageType::Programming }),
        ("EBNF", Language { name: "EBNF", language_type: LanguageType::Data }),
        ("AppleScript", Language { name: "AppleScript", language_type: LanguageType::Programming }),
        ("DNS Zone", Language { name: "DNS Zone", language_type: LanguageType::Data }),
        ("World of Warcraft Addon Data", Language { name: "World of Warcraft Addon Data", language_type: LanguageType::Data }),
        ("AutoHotkey", Language { name: "AutoHotkey", language_type: LanguageType::Programming }),
        ("HyPhy", Language { name: "HyPhy", language_type: LanguageType::Programming }),
        ("OpenRC runscript", Language { name: "OpenRC runscript", language_type: LanguageType::Programming }),
        ("Vim script", Language { name: "Vim script", language_type: LanguageType::Programming }),
        ("Dockerfile", Language { name: "Dockerfile", language_type: LanguageType::Programming }),
        ("PLpgSQL", Language { name: "PLpgSQL", language_type: LanguageType::Programming }),
        ("EditorConfig", Language { name: "EditorConfig", language_type: LanguageType::Data }),
        ("Lex", Language { name: "Lex", language_type: LanguageType::Programming }),
        ("XQuery", Language { name: "XQuery", language_type: LanguageType::Programming }),
        ("TypeScript", Language { name: "TypeScript", language_type: LanguageType::Programming }),
        ("Ecere Projects", Language { name: "Ecere Projects", language_type: LanguageType::Data }),
        ("Genie", Language { name: "Genie", language_type: LanguageType::Programming }),
        ("ActionScript", Language { name: "ActionScript", language_type: LanguageType::Programming }),
        ("Chapel", Language { name: "Chapel", language_type: LanguageType::Programming }),
        ("Game Maker Language", Language { name: "Game Maker Language", language_type: LanguageType::Programming }),
        ("RenderScript", Language { name: "RenderScript", language_type: LanguageType::Programming }),
        ("Formatted", Language { name: "Formatted", language_type: LanguageType::Data }),
        ("Raku", Language { name: "Raku", language_type: LanguageType::Programming }),
        ("XProc", Language { name: "XProc", language_type: LanguageType::Programming }),
        ("Mako", Language { name: "Mako", language_type: LanguageType::Programming }),
        ("Factor", Language { name: "Factor", language_type: LanguageType::Programming }),
        ("Common Lisp", Language { name: "Common Lisp", language_type: LanguageType::Programming }),
        ("WebIDL", Language { name: "WebIDL", language_type: LanguageType::Programming }),
        ("Textile", Language { name: "Textile", language_type: LanguageType::Prose }),
        ("CoNLL-U", Language { name: "CoNLL-U", language_type: LanguageType::Data }),
        ("Volt", Language { name: "Volt", language_type: LanguageType::Programming }),
        ("M", Language { name: "M", language_type: LanguageType::Programming }),
        ("Blade", Language { name: "Blade", language_type: LanguageType::Markup }),
        ("PowerShell", Language { name: "PowerShell", language_type: LanguageType::Programming }),
        ("Verilog", Language { name: "Verilog", language_type: LanguageType::Programming }),
        ("Meson", Language { name: "Meson", language_type: LanguageType::Programming }),
        ("NetLinx", Language { name: "NetLinx", language_type: LanguageType::Programming }),
        ("JSON with Comments", Language { name: "JSON with Comments", language_type: LanguageType::Data }),
        ("LTspice Symbol", Language { name: "LTspice Symbol", language_type: LanguageType::Data }),
        ("Ceylon", Language { name: "Ceylon", language_type: LanguageType::Programming }),
        ("IGOR Pro", Language { name: "IGOR Pro", language_type: LanguageType::Programming }),
        ("Spline Font Database", Language { name: "Spline Font Database", language_type: LanguageType::Data }),
        ("Alloy", Language { name: "Alloy", language_type: LanguageType::Programming }),
        ("YASnippet", Language { name: "YASnippet", language_type: LanguageType::Markup }),
        ("Isabelle", Language { name: "Isabelle", language_type: LanguageType::Programming }),
        ("GDB", Language { name: "GDB", language_type: LanguageType::Programming }),
        ("Adobe Font Metrics", Language { name: "Adobe Font Metrics", language_type: LanguageType::Data }),
        ("Latte", Language { name: "Latte", language_type: LanguageType::Markup }),
        ("NL", Language { name: "NL", language_type: LanguageType::Data }),
        ("SQL", Language { name: "SQL", language_type: LanguageType::Data }),
        ("Lua", Language { name: "Lua", language_type: LanguageType::Programming }),
        ("Shell", Language { name: "Shell", language_type: LanguageType::Programming }),
        ("Gnuplot", Language { name: "Gnuplot", language_type: LanguageType::Programming }),
        ("SPARQL", Language { name: "SPARQL", language_type: LanguageType::Data }),
        ("Wavefront Material", Language { name: "Wavefront Material", language_type: LanguageType::Data }),
        ("Parrot Assembly", Language { name: "Parrot Assembly", language_type: LanguageType::Programming }),
        ("OCaml", Language { name: "OCaml", language_type: LanguageType::Programming }),
        ("Zimpl", Language { name: "Zimpl", language_type: LanguageType::Programming }),
        ("Kit", Language { name: "Kit", language_type: LanguageType::Markup }),
        ("wdl", Language { name: "wdl", language_type: LanguageType::Programming }),
        ("Ninja", Language { name: "Ninja", language_type: LanguageType::Data }),
        ("Ring", Language { name: "Ring", language_type: LanguageType::Programming }),
        ("AspectJ", Language { name: "AspectJ", language_type: LanguageType::Programming }),
        ("Cabal Config", Language { name: "Cabal Config", language_type: LanguageType::Data }),
        ("Turing", Language { name: "Turing", language_type: LanguageType::Programming }),
        ("TeX", Language { name: "TeX", language_type: LanguageType::Markup }),
        ("Awk", Language { name: "Awk", language_type: LanguageType::Programming }),
        ("MediaWiki", Language { name: "MediaWiki", language_type: LanguageType::Prose }),
        ("Glyph", Language { name: "Glyph", language_type: LanguageType::Programming }),
        ("Haxe", Language { name: "Haxe", language_type: LanguageType::Programming }),
        ("HLSL", Language { name: "HLSL", language_type: LanguageType::Programming }),
        ("TXL", Language { name: "TXL", language_type: LanguageType::Programming }),
        ("Standard ML", Language { name: "Standard ML", language_type: LanguageType::Programming }),
        ("Haml", Language { name: "Haml", language_type: LanguageType::Markup }),
        ("Python", Language { name: "Python", language_type: LanguageType::Programming }),
        ("SuperCollider", Language { name: "SuperCollider", language_type: LanguageType::Programming }),
        ("C#", Language { name: "C#", language_type: LanguageType::Programming }),
        ("ZenScript", Language { name: "ZenScript", language_type: LanguageType::Programming }),
        ("Nu", Language { name: "Nu", language_type: LanguageType::Programming }),
        ("OpenCL", Language { name: "OpenCL", language_type: LanguageType::Programming }),
        ("Puppet", Language { name: "Puppet", language_type: LanguageType::Programming }),
        ("Texinfo", Language { name: "Texinfo", language_type: LanguageType::Prose }),
        ("API Blueprint", Language { name: "API Blueprint", language_type: LanguageType::Markup }),
        ("Scala", Language { name: "Scala", language_type: LanguageType::Programming }),
        ("Linker Script", Language { name: "Linker Script", language_type: LanguageType::Data }),
        ("Closure Templates", Language { name: "Closure Templates", language_type: LanguageType::Markup }),
        ("Ragel", Language { name: "Ragel", language_type: LanguageType::Programming }),
        ("Roff Manpage", Language { name: "Roff Manpage", language_type: LanguageType::Markup }),
        ("Literate Haskell", Language { name: "Literate Haskell", language_type: LanguageType::Programming }),
        ("Thrift", Language { name: "Thrift", language_type: LanguageType::Programming }),
        ("NewLisp", Language { name: "NewLisp", language_type: LanguageType::Programming }),
        ("Stata", Language { name: "Stata", language_type: LanguageType::Programming }),
        ("Gerber Image", Language { name: "Gerber Image", language_type: LanguageType::Data }),
        ("Gettext Catalog", Language { name: "Gettext Catalog", language_type: LanguageType::Prose }),
        ("Smarty", Language { name: "Smarty", language_type: LanguageType::Programming }),
        ("Pascal", Language { name: "Pascal", language_type: LanguageType::Programming }),
        ("Stylus", Language { name: "Stylus", language_type: LanguageType::Markup }),
        ("YARA", Language { name: "YARA", language_type: LanguageType::Programming }),
        ("Less", Language { name: "Less", language_type: LanguageType::Markup }),
        ("BlitzMax", Language { name: "BlitzMax", language_type: LanguageType::Programming }),
        ("Groovy", Language { name: "Groovy", language_type: LanguageType::Programming }),
        ("F#", Language { name: "F#", language_type: LanguageType::Programming }),
        ("ASP", Language { name: "ASP", language_type: LanguageType::Programming }),
        ("HTML+Razor", Language { name: "HTML+Razor", language_type: LanguageType::Markup }),
        ("BlitzBasic", Language { name: "BlitzBasic", language_type: LanguageType::Programming }),
        ("Scaml", Language { name: "Scaml", language_type: LanguageType::Markup }),
        ("Prisma", Language { name: "Prisma", language_type: LanguageType::Data }),
        ("Modula-3", Language { name: "Modula-3", language_type: LanguageType::Programming }),
        ("Charity", Language { name: "Charity", language_type: LanguageType::Programming }),
        ("Nix", Language { name: "Nix", language_type: LanguageType::Programming }),
        ("LOLCODE", Language { name: "LOLCODE", language_type: LanguageType::Programming }),
        ("Rascal", Language { name: "Rascal", language_type: LanguageType::Programming }),
        ("Opal", Language { name: "Opal", language_type: LanguageType::Programming }),
        ("SVG", Language { name: "SVG", language_type: LanguageType::Data }),
        ("DM", Language { name: "DM", language_type: LanguageType::Programming }),
        ("Dogescript", Language { name: "Dogescript", language_type: LanguageType::Programming }),
        ("Zephir", Language { name: "Zephir", language_type: LanguageType::Programming }),
        ("xBase", Language { name: "xBase", language_type: LanguageType::Programming }),
        ("FreeMarker", Language { name: "FreeMarker", language_type: LanguageType::Programming }),
        ("MAXScript", Language { name: "MAXScript", language_type: LanguageType::Programming }),
        ("Bluespec", Language { name: "Bluespec", language_type: LanguageType::Programming }),
        ("nanorc", Language { name: "nanorc", language_type: LanguageType::Data }),
        ("JSONLD", Language { name: "JSONLD", language_type: LanguageType::Data }),
        ("Harbour", Language { name: "Harbour", language_type: LanguageType::Programming }),
        ("Unified Parallel C", Language { name: "Unified Parallel C", language_type: LanguageType::Programming }),
        ("PicoLisp", Language { name: "PicoLisp", language_type: LanguageType::Programming }),
        ("JSONiq", Language { name: "JSONiq", language_type: LanguageType::Programming }),
        ("Batchfile", Language { name: "Batchfile", language_type: LanguageType::Programming }),
        ("Augeas", Language { name: "Augeas", language_type: LanguageType::Programming }),
        ("D", Language { name: "D", language_type: LanguageType::Programming }),
        ("Inform 7", Language { name: "Inform 7", language_type: LanguageType::Programming }),
        ("EQ", Language { name: "EQ", language_type: LanguageType::Programming }),
        ("mcfunction", Language { name: "mcfunction", language_type: LanguageType::Programming }),
        ("Apollo Guidance Computer", Language { name: "Apollo Guidance Computer", language_type: LanguageType::Programming }),
        ("ColdFusion CFC", Language { name: "ColdFusion CFC", language_type: LanguageType::Programming }),
        ("Edje Data Collection", Language { name: "Edje Data Collection", language_type: LanguageType::Data }),
        ("KiCad Legacy Layout", Language { name: "KiCad Legacy Layout", language_type: LanguageType::Data }),
        ("dircolors", Language { name: "dircolors", language_type: LanguageType::Data }),
        ("Sass", Language { name: "Sass", language_type: LanguageType::Markup }),
        ("ANTLR", Language { name: "ANTLR", language_type: LanguageType::Programming }),
        ("NSIS", Language { name: "NSIS", language_type: LanguageType::Programming }),
        ("ShaderLab", Language { name: "ShaderLab", language_type: LanguageType::Programming }),
        ("Filebench WML", Language { name: "Filebench WML", language_type: LanguageType::Programming }),
        ("mupad", Language { name: "mupad", language_type: LanguageType::Programming }),
        ("Glyph Bitmap Distribution Format", Language { name: "Glyph Bitmap Distribution Format", language_type: LanguageType::Data }),
        ("X BitMap", Language { name: "X BitMap", language_type: LanguageType::Data }),
        ("Julia", Language { name: "Julia", language_type: LanguageType::Programming }),
        ("MTML", Language { name: "MTML", language_type: LanguageType::Markup }),
        ("Easybuild", Language { name: "Easybuild", language_type: LanguageType::Data }),
        ("ColdFusion", Language { name: "ColdFusion", language_type: LanguageType::Programming }),
        ("Oz", Language { name: "Oz", language_type: LanguageType::Programming }),
        ("Dhall", Language { name: "Dhall", language_type: LanguageType::Programming }),
        ("nesC", Language { name: "nesC", language_type: LanguageType::Programming }),
        ("Stan", Language { name: "Stan", language_type: LanguageType::Programming }),
        ("D-ObjDump", Language { name: "D-ObjDump", language_type: LanguageType::Data }),
        ("HTML", Language { name: "HTML", language_type: LanguageType::Markup }),
        ("JavaScript+ERB", Language { name: "JavaScript+ERB", language_type: LanguageType::Programming }),
        ("QML", Language { name: "QML", language_type: LanguageType::Programming }),
        ("Racket", Language { name: "Racket", language_type: LanguageType::Programming }),
        ("HTML+PHP", Language { name: "HTML+PHP", language_type: LanguageType::Markup }),
        ("Sage", Language { name: "Sage", language_type: LanguageType::Programming }),
        ("Darcs Patch", Language { name: "Darcs Patch", language_type: LanguageType::Data }),
        ("Tea", Language { name: "Tea", language_type: LanguageType::Markup }),
        ("Modelica", Language { name: "Modelica", language_type: LanguageType::Programming }),
        ("Vala", Language { name: "Vala", language_type: LanguageType::Programming }),
        ("Maven POM", Language { name: "Maven POM", language_type: LanguageType::Data }),
        ("wisp", Language { name: "wisp", language_type: LanguageType::Programming }),
        ("Prolog", Language { name: "Prolog", language_type: LanguageType::Programming }),
        ("Python traceback", Language { name: "Python traceback", language_type: LanguageType::Data }),
        ("Dart", Language { name: "Dart", language_type: LanguageType::Programming }),
        ("eC", Language { name: "eC", language_type: LanguageType::Programming }),
        ("sed", Language { name: "sed", language_type: LanguageType::Programming }),
        ("CartoCSS", Language { name: "CartoCSS", language_type: LanguageType::Programming }),
        ("Kotlin", Language { name: "Kotlin", language_type: LanguageType::Programming }),
        ("Graph Modeling Language", Language { name: "Graph Modeling Language", language_type: LanguageType::Data }),
        ("HCL", Language { name: "HCL", language_type: LanguageType::Programming }),
        ("NumPy", Language { name: "NumPy", language_type: LanguageType::Programming }),
        ("AngelScript", Language { name: "AngelScript", language_type: LanguageType::Programming }),
        ("Svelte", Language { name: "Svelte", language_type: LanguageType::Markup }),
        ("Twig", Language { name: "Twig", language_type: LanguageType::Markup }),
        ("Slice", Language { name: "Slice", language_type: LanguageType::Programming }),
        ("Git Attributes", Language { name: "Git Attributes", language_type: LanguageType::Data }),
        ("KRL", Language { name: "KRL", language_type: LanguageType::Programming }),
        ("Ren\'Py", Language { name: "Ren'Py", language_type: LanguageType::Programming }),
        ("SMT", Language { name: "SMT", language_type: LanguageType::Programming }),
        ("CodeQL", Language { name: "CodeQL", language_type: LanguageType::Programming }),
        ("Processing", Language { name: "Processing", language_type: LanguageType::Programming }),
        ("Golo", Language { name: "Golo", language_type: LanguageType::Programming }),
        ("XC", Language { name: "XC", language_type: LanguageType::Programming }),
        ("Nextflow", Language { name: "Nextflow", language_type: LanguageType::Programming }),
        ("Uno", Language { name: "Uno", language_type: LanguageType::Programming }),
        ("HolyC", Language { name: "HolyC", language_type: LanguageType::Programming }),
        ("ABAP", Language { name: "ABAP", language_type: LanguageType::Programming }),
        ("Mercury", Language { name: "Mercury", language_type: LanguageType::Programming }),
        ("Mirah", Language { name: "Mirah", language_type: LanguageType::Programming }),
        ("QMake", Language { name: "QMake", language_type: LanguageType::Programming }),
        ("MATLAB", Language { name: "MATLAB", language_type: LanguageType::Programming }),
        ("Rebol", Language { name: "Rebol", language_type: LanguageType::Programming }),
        ("Omgrofl", Language { name: "Omgrofl", language_type: LanguageType::Programming }),
        ("Max", Language { name: "Max", language_type: LanguageType::Programming }),
        ("NetLinx+ERB", Language { name: "NetLinx+ERB", language_type: LanguageType::Programming }),
        ("Objective-C++", Language { name: "Objective-C++", language_type: LanguageType::Programming }),
        ("Raw token data", Language { name: "Raw token data", language_type: LanguageType::Data }),
        ("Visual Basic .NET", Language { name: "Visual Basic .NET", language_type: LanguageType::Programming }),
        ("Pony", Language { name: "Pony", language_type: LanguageType::Programming }),
        ("GAMS", Language { name: "GAMS", language_type: LanguageType::Programming }),
        ("Objective-C", Language { name: "Objective-C", language_type: LanguageType::Programming }),
        ("XPages", Language { name: "XPages", language_type: LanguageType::Data }),
        ("Jison", Language { name: "Jison", language_type: LanguageType::Programming }),
        ("Frege", Language { name: "Frege", language_type: LanguageType::Programming }),
        ("Pike", Language { name: "Pike", language_type: LanguageType::Programming }),
        ("CLIPS", Language { name: "CLIPS", language_type: LanguageType::Programming }),
        ("LoomScript", Language { name: "LoomScript", language_type: LanguageType::Programming }),
        ("OpenQASM", Language { name: "OpenQASM", language_type: LanguageType::Programming }),
        ("Xtend", Language { name: "Xtend", language_type: LanguageType::Programming }),
        ("AMPL", Language { name: "AMPL", language_type: LanguageType::Programming }),
        ("DataWeave", Language { name: "DataWeave", language_type: LanguageType::Programming }),
        ("CWeb", Language { name: "CWeb", language_type: LanguageType::Programming }),
        ("IDL", Language { name: "IDL", language_type: LanguageType::Programming }),
        ("DirectX 3D File", Language { name: "DirectX 3D File", language_type: LanguageType::Data }),
        ("ShellSession", Language { name: "ShellSession", language_type: LanguageType::Programming }),
        ("DTrace", Language { name: "DTrace", language_type: LanguageType::Programming }),
        ("Opa", Language { name: "Opa", language_type: LanguageType::Programming }),
        ("Slash", Language { name: "Slash", language_type: LanguageType::Programming }),
        ("WebVTT", Language { name: "WebVTT", language_type: LanguageType::Data }),
        ("Ballerina", Language { name: "Ballerina", language_type: LanguageType::Programming }),
        ("SourcePawn", Language { name: "SourcePawn", language_type: LanguageType::Programming }),
        ("HTML+EEX", Language { name: "HTML+EEX", language_type: LanguageType::Markup }),
        ("Pod", Language { name: "Pod", language_type: LanguageType::Prose }),
        ("FLUX", Language { name: "FLUX", language_type: LanguageType::Programming }),
        ("Eiffel", Language { name: "Eiffel", language_type: LanguageType::Programming }),
        ("Terra", Language { name: "Terra", language_type: LanguageType::Programming }),
        ("Wavefront Object", Language { name: "Wavefront Object", language_type: LanguageType::Data }),
        ("Component Pascal", Language { name: "Component Pascal", language_type: LanguageType::Programming }),
        ("MoonScript", Language { name: "MoonScript", language_type: LanguageType::Programming }),
        ("Gentoo Eclass", Language { name: "Gentoo Eclass", language_type: LanguageType::Programming }),
        ("VBA", Language { name: "VBA", language_type: LanguageType::Programming }),
        ("M4Sugar", Language { name: "M4Sugar", language_type: LanguageType::Programming }),
        ("Liquid", Language { name: "Liquid", language_type: LanguageType::Markup }),
        ("Isabelle ROOT", Language { name: "Isabelle ROOT", language_type: LanguageType::Programming }),
        ("NCL", Language { name: "NCL", language_type: LanguageType::Programming }),
        ("Click", Language { name: "Click", language_type: LanguageType::Programming }),
        ("APL", Language { name: "APL", language_type: LanguageType::Programming }),
        ("SaltStack", Language { name: "SaltStack", language_type: LanguageType::Programming }),
        ("Jasmin", Language { name: "Jasmin", language_type: LanguageType::Programming }),
    ]),
};

