static LANGUAGE_INFO: phf::Map<&'static str, Language> =
::phf::Map {
    key: 3213172566270843353,
    disps: ::phf::Slice::Static(&[
        (0, 296),
        (0, 5),
        (0, 213),
        (0, 231),
        (0, 0),
        (1, 3),
        (0, 4),
        (0, 287),
        (0, 39),
        (1, 173),
        (0, 292),
        (0, 133),
        (0, 15),
        (0, 150),
        (0, 2),
        (0, 128),
        (0, 1),
        (1, 24),
        (0, 0),
        (0, 38),
        (0, 259),
        (0, 2),
        (0, 128),
        (0, 110),
        (0, 2),
        (0, 48),
        (0, 5),
        (0, 24),
        (0, 166),
        (4, 164),
        (0, 8),
        (0, 2),
        (0, 3),
        (6, 260),
        (0, 61),
        (0, 539),
        (0, 39),
        (0, 0),
        (0, 45),
        (0, 219),
        (0, 157),
        (0, 54),
        (0, 288),
        (0, 393),
        (0, 179),
        (3, 362),
        (0, 210),
        (0, 146),
        (0, 112),
        (0, 69),
        (0, 1),
        (0, 165),
        (0, 318),
        (3, 108),
        (0, 1),
        (0, 12),
        (1, 101),
        (2, 129),
        (0, 0),
        (0, 487),
        (1, 131),
        (1, 10),
        (0, 1),
        (0, 82),
        (0, 3),
        (0, 39),
        (2, 538),
        (0, 158),
        (0, 33),
        (10, 217),
        (0, 3),
        (1, 289),
        (0, 19),
        (1, 125),
        (0, 0),
        (0, 227),
        (0, 10),
        (0, 385),
        (0, 368),
        (0, 206),
        (0, 534),
        (0, 461),
        (0, 112),
        (10, 157),
        (5, 403),
        (0, 118),
        (1, 5),
        (0, 2),
        (1, 335),
        (0, 229),
        (0, 2),
        (0, 0),
        (0, 268),
        (1, 211),
        (0, 3),
        (0, 1),
        (0, 33),
        (5, 260),
        (1, 4),
        (3, 67),
        (0, 95),
        (3, 331),
        (7, 110),
        (0, 208),
        (0, 240),
        (0, 93),
        (8, 211),
        (1, 136),
        (6, 438),
        (8, 523),
        (1, 243),
    ]),
    entries: ::phf::Slice::Static(&[
        ("R", Language { name: "R", ext: Some("r"), language_type: LanguageType::Programming, color: Some("#198CE7"), group: None }),
        ("Ant Build System", Language { name: "Ant Build System", ext: None, language_type: LanguageType::Data, color: None, group: None }),
        ("Smali", Language { name: "Smali", ext: Some("smali"), language_type: LanguageType::Programming, color: None, group: None }),
        ("C++", Language { name: "C++", ext: Some("cpp"), language_type: LanguageType::Programming, color: Some("#f34b7d"), group: None }),
        ("JFlex", Language { name: "JFlex", ext: Some("flex"), language_type: LanguageType::Programming, color: None, group: Some("Lex") }),
        ("HAProxy", Language { name: "HAProxy", ext: Some("cfg"), language_type: LanguageType::Data, color: None, group: None }),
        ("JSON", Language { name: "JSON", ext: Some("json"), language_type: LanguageType::Data, color: None, group: None }),
        ("Ruby", Language { name: "Ruby", ext: Some("rb"), language_type: LanguageType::Programming, color: Some("#701516"), group: None }),
        ("Myghty", Language { name: "Myghty", ext: Some("myt"), language_type: LanguageType::Programming, color: None, group: None }),
        ("Proguard", Language { name: "Proguard", ext: Some("pro"), language_type: LanguageType::Data, color: None, group: None }),
        ("Elm", Language { name: "Elm", ext: Some("elm"), language_type: LanguageType::Programming, color: Some("#60B5CC"), group: None }),
        ("Xojo", Language { name: "Xojo", ext: Some("xojo_code"), language_type: LanguageType::Programming, color: None, group: None }),
        ("CSV", Language { name: "CSV", ext: Some("csv"), language_type: LanguageType::Data, color: None, group: None }),
        ("RDoc", Language { name: "RDoc", ext: Some("rdoc"), language_type: LanguageType::Prose, color: None, group: None }),
        ("Inno Setup", Language { name: "Inno Setup", ext: Some("iss"), language_type: LanguageType::Programming, color: None, group: None }),
        ("Cirru", Language { name: "Cirru", ext: Some("cirru"), language_type: LanguageType::Programming, color: Some("#ccccff"), group: None }),
        ("Pan", Language { name: "Pan", ext: Some("pan"), language_type: LanguageType::Programming, color: Some("#cc0000"), group: None }),
        ("Tcsh", Language { name: "Tcsh", ext: Some("tcsh"), language_type: LanguageType::Programming, color: None, group: Some("Shell") }),
        ("Dylan", Language { name: "Dylan", ext: Some("dylan"), language_type: LanguageType::Programming, color: Some("#6c616e"), group: None }),
        ("Pic", Language { name: "Pic", ext: Some("pic"), language_type: LanguageType::Markup, color: None, group: Some("Roff") }),
        ("Jsonnet", Language { name: "Jsonnet", ext: Some("jsonnet"), language_type: LanguageType::Programming, color: Some("#0064bd"), group: None }),
        ("Objective-J", Language { name: "Objective-J", ext: Some("j"), language_type: LanguageType::Programming, color: Some("#ff0c5a"), group: None }),
        ("COBOL", Language { name: "COBOL", ext: Some("cob"), language_type: LanguageType::Programming, color: None, group: None }),
        ("Ignore List", Language { name: "Ignore List", ext: Some("gitignore"), language_type: LanguageType::Data, color: None, group: Some("INI") }),
        ("Clarion", Language { name: "Clarion", ext: Some("clw"), language_type: LanguageType::Programming, color: Some("#db901e"), group: None }),
        ("PureBasic", Language { name: "PureBasic", ext: Some("pb"), language_type: LanguageType::Programming, color: Some("#5a6986"), group: None }),
        ("Csound Score", Language { name: "Csound Score", ext: Some("sco"), language_type: LanguageType::Programming, color: None, group: None }),
        ("Jison Lex", Language { name: "Jison Lex", ext: Some("jisonlex"), language_type: LanguageType::Programming, color: None, group: Some("Lex") }),
        ("Crystal", Language { name: "Crystal", ext: Some("cr"), language_type: LanguageType::Programming, color: Some("#000100"), group: None }),
        ("SystemVerilog", Language { name: "SystemVerilog", ext: Some("sv"), language_type: LanguageType::Programming, color: Some("#DAE1C2"), group: None }),
        ("Linux Kernel Module", Language { name: "Linux Kernel Module", ext: Some("mod"), language_type: LanguageType::Data, color: None, group: None }),
        ("ObjDump", Language { name: "ObjDump", ext: Some("objdump"), language_type: LanguageType::Data, color: None, group: None }),
        ("PHP", Language { name: "PHP", ext: Some("php"), language_type: LanguageType::Programming, color: Some("#4F5D95"), group: None }),
        ("SCSS", Language { name: "SCSS", ext: Some("scss"), language_type: LanguageType::Markup, color: None, group: Some("CSS") }),
        ("YAML", Language { name: "YAML", ext: Some("yml"), language_type: LanguageType::Data, color: None, group: None }),
        ("IRC log", Language { name: "IRC log", ext: Some("irclog"), language_type: LanguageType::Data, color: None, group: None }),
        ("RobotFramework", Language { name: "RobotFramework", ext: Some("robot"), language_type: LanguageType::Programming, color: None, group: None }),
        ("Unix Assembly", Language { name: "Unix Assembly", ext: Some("s"), language_type: LanguageType::Programming, color: None, group: Some("Assembly") }),
        ("Grace", Language { name: "Grace", ext: Some("grace"), language_type: LanguageType::Programming, color: None, group: None }),
        ("Nemerle", Language { name: "Nemerle", ext: Some("n"), language_type: LanguageType::Programming, color: Some("#3d3c6e"), group: None }),
        ("RMarkdown", Language { name: "RMarkdown", ext: Some("rmd"), language_type: LanguageType::Prose, color: None, group: None }),
        ("Altium Designer", Language { name: "Altium Designer", ext: Some("OutJob"), language_type: LanguageType::Data, color: None, group: None }),
        ("Boo", Language { name: "Boo", ext: Some("boo"), language_type: LanguageType::Programming, color: Some("#d4bec1"), group: None }),
        ("Ox", Language { name: "Ox", ext: Some("ox"), language_type: LanguageType::Programming, color: None, group: None }),
        ("P4", Language { name: "P4", ext: Some("p4"), language_type: LanguageType::Programming, color: Some("#7055b5"), group: None }),
        ("XML Property List", Language { name: "XML Property List", ext: Some("plist"), language_type: LanguageType::Data, color: None, group: Some("XML") }),
        ("ApacheConf", Language { name: "ApacheConf", ext: Some("apacheconf"), language_type: LanguageType::Data, color: None, group: None }),
        ("Windows Registry Entries", Language { name: "Windows Registry Entries", ext: Some("reg"), language_type: LanguageType::Data, color: None, group: None }),
        ("Arc", Language { name: "Arc", ext: Some("arc"), language_type: LanguageType::Programming, color: Some("#aa2afe"), group: None }),
        ("GraphQL", Language { name: "GraphQL", ext: Some("graphql"), language_type: LanguageType::Data, color: None, group: None }),
        ("Text", Language { name: "Text", ext: Some("txt"), language_type: LanguageType::Prose, color: None, group: None }),
        ("Papyrus", Language { name: "Papyrus", ext: Some("psc"), language_type: LanguageType::Programming, color: Some("#6600cc"), group: None }),
        ("Wget Config", Language { name: "Wget Config", ext: None, language_type: LanguageType::Data, color: None, group: Some("INI") }),
        ("VBScript", Language { name: "VBScript", ext: Some("vbs"), language_type: LanguageType::Programming, color: Some("#15dcdc"), group: None }),
        ("Vim Snippet", Language { name: "Vim Snippet", ext: Some("snip"), language_type: LanguageType::Markup, color: None, group: None }),
        ("LookML", Language { name: "LookML", ext: Some("lookml"), language_type: LanguageType::Programming, color: Some("#652B81"), group: None }),
        ("SRecode Template", Language { name: "SRecode Template", ext: Some("srt"), language_type: LanguageType::Markup, color: Some("#348a34"), group: None }),
        ("CMake", Language { name: "CMake", ext: Some("cmake"), language_type: LanguageType::Programming, color: None, group: None }),
        ("SubRip Text", Language { name: "SubRip Text", ext: Some("srt"), language_type: LanguageType::Data, color: None, group: None }),
        ("ASN.1", Language { name: "ASN.1", ext: Some("asn"), language_type: LanguageType::Data, color: None, group: None }),
        ("Nginx", Language { name: "Nginx", ext: Some("nginxconf"), language_type: LanguageType::Data, color: None, group: None }),
        ("Regular Expression", Language { name: "Regular Expression", ext: Some("regexp"), language_type: LanguageType::Data, color: None, group: None }),
        ("Literate Agda", Language { name: "Literate Agda", ext: Some("lagda"), language_type: LanguageType::Programming, color: None, group: Some("Agda") }),
        ("Cap\'n Proto", Language { name: "Cap'n Proto", ext: Some("capnp"), language_type: LanguageType::Programming, color: None, group: None }),
        ("STON", Language { name: "STON", ext: Some("ston"), language_type: LanguageType::Data, color: None, group: Some("Smalltalk") }),
        ("Object Data Instance Notation", Language { name: "Object Data Instance Notation", ext: Some("odin"), language_type: LanguageType::Data, color: None, group: None }),
        ("Moocode", Language { name: "Moocode", ext: Some("moo"), language_type: LanguageType::Programming, color: None, group: None }),
        ("REALbasic", Language { name: "REALbasic", ext: Some("rbbas"), language_type: LanguageType::Programming, color: None, group: None }),
        ("Grammatical Framework", Language { name: "Grammatical Framework", ext: Some("gf"), language_type: LanguageType::Programming, color: Some("#79aa7a"), group: None }),
        ("XSLT", Language { name: "XSLT", ext: Some("xslt"), language_type: LanguageType::Programming, color: Some("#EB8CEB"), group: None }),
        ("Gherkin", Language { name: "Gherkin", ext: Some("feature"), language_type: LanguageType::Programming, color: Some("#5B2063"), group: None }),
        ("Nit", Language { name: "Nit", ext: Some("nit"), language_type: LanguageType::Programming, color: Some("#009917"), group: None }),
        ("Mathematica", Language { name: "Mathematica", ext: Some("mathematica"), language_type: LanguageType::Programming, color: None, group: None }),
        ("TOML", Language { name: "TOML", ext: Some("toml"), language_type: LanguageType::Data, color: None, group: None }),
        ("Scilab", Language { name: "Scilab", ext: Some("sci"), language_type: LanguageType::Programming, color: None, group: None }),
        ("Perl", Language { name: "Perl", ext: Some("pl"), language_type: LanguageType::Programming, color: Some("#0298c3"), group: None }),
        ("C-ObjDump", Language { name: "C-ObjDump", ext: Some("c-objdump"), language_type: LanguageType::Data, color: None, group: None }),
        ("fish", Language { name: "fish", ext: Some("fish"), language_type: LanguageType::Programming, color: None, group: Some("Shell") }),
        ("Java Properties", Language { name: "Java Properties", ext: Some("properties"), language_type: LanguageType::Data, color: None, group: None }),
        ("Brightscript", Language { name: "Brightscript", ext: Some("brs"), language_type: LanguageType::Programming, color: None, group: None }),
        ("Cycript", Language { name: "Cycript", ext: Some("cy"), language_type: LanguageType::Programming, color: None, group: None }),
        ("Public Key", Language { name: "Public Key", ext: Some("asc"), language_type: LanguageType::Data, color: None, group: None }),
        ("Go", Language { name: "Go", ext: Some("go"), language_type: LanguageType::Programming, color: Some("#00ADD8"), group: None }),
        ("Makefile", Language { name: "Makefile", ext: Some("mak"), language_type: LanguageType::Programming, color: Some("#427819"), group: None }),
        ("G-code", Language { name: "G-code", ext: Some("g"), language_type: LanguageType::Programming, color: Some("#D08CF2"), group: None }),
        ("LLVM", Language { name: "LLVM", ext: Some("ll"), language_type: LanguageType::Programming, color: Some("#185619"), group: None }),
        ("reStructuredText", Language { name: "reStructuredText", ext: Some("rst"), language_type: LanguageType::Prose, color: None, group: None }),
        ("cURL Config", Language { name: "cURL Config", ext: None, language_type: LanguageType::Data, color: None, group: Some("INI") }),
        ("Yacc", Language { name: "Yacc", ext: Some("y"), language_type: LanguageType::Programming, color: Some("#4B6C4B"), group: None }),
        ("Pug", Language { name: "Pug", ext: Some("jade"), language_type: LanguageType::Markup, color: None, group: Some("HTML") }),
        ("Metal", Language { name: "Metal", ext: Some("metal"), language_type: LanguageType::Programming, color: Some("#8f14e9"), group: None }),
        ("NASL", Language { name: "NASL", ext: Some("nasl"), language_type: LanguageType::Programming, color: None, group: None }),
        ("MQL5", Language { name: "MQL5", ext: Some("mq5"), language_type: LanguageType::Programming, color: Some("#4A76B8"), group: None }),
        ("Alpine Abuild", Language { name: "Alpine Abuild", ext: None, language_type: LanguageType::Programming, color: None, group: Some("Shell") }),
        ("ATS", Language { name: "ATS", ext: Some("dats"), language_type: LanguageType::Programming, color: Some("#1ac620"), group: None }),
        ("Slim", Language { name: "Slim", ext: Some("slim"), language_type: LanguageType::Markup, color: None, group: Some("HTML") }),
        ("LabVIEW", Language { name: "LabVIEW", ext: Some("lvproj"), language_type: LanguageType::Programming, color: None, group: None }),
        ("Scheme", Language { name: "Scheme", ext: Some("scm"), language_type: LanguageType::Programming, color: Some("#1e4aec"), group: None }),
        ("V", Language { name: "V", ext: Some("v"), language_type: LanguageType::Programming, color: Some("#5d87bd"), group: None }),
        ("Tcl", Language { name: "Tcl", ext: Some("tcl"), language_type: LanguageType::Programming, color: Some("#e4cc98"), group: None }),
        ("Zeek", Language { name: "Zeek", ext: Some("zeek"), language_type: LanguageType::Programming, color: None, group: None }),
        ("EML", Language { name: "EML", ext: Some("eml"), language_type: LanguageType::Data, color: None, group: None }),
        ("GDScript", Language { name: "GDScript", ext: Some("gd"), language_type: LanguageType::Programming, color: Some("#355570"), group: None }),
        ("Markdown", Language { name: "Markdown", ext: Some("md"), language_type: LanguageType::Prose, color: None, group: None }),
        ("MQL4", Language { name: "MQL4", ext: Some("mq4"), language_type: LanguageType::Programming, color: Some("#62A8D6"), group: None }),
        ("Vue", Language { name: "Vue", ext: Some("vue"), language_type: LanguageType::Markup, color: Some("#2c3e50"), group: None }),
        ("Gradle", Language { name: "Gradle", ext: Some("gradle"), language_type: LanguageType::Data, color: None, group: None }),
        ("Logtalk", Language { name: "Logtalk", ext: Some("lgt"), language_type: LanguageType::Programming, color: None, group: None }),
        ("Self", Language { name: "Self", ext: Some("self"), language_type: LanguageType::Programming, color: Some("#0579aa"), group: None }),
        ("GAP", Language { name: "GAP", ext: Some("g"), language_type: LanguageType::Programming, color: None, group: None }),
        ("SQF", Language { name: "SQF", ext: Some("sqf"), language_type: LanguageType::Programming, color: Some("#3F3F3F"), group: None }),
        ("Groovy Server Pages", Language { name: "Groovy Server Pages", ext: Some("gsp"), language_type: LanguageType::Programming, color: None, group: Some("Groovy") }),
        ("Marko", Language { name: "Marko", ext: Some("marko"), language_type: LanguageType::Markup, color: None, group: Some("HTML") }),
        ("TSX", Language { name: "TSX", ext: Some("tsx"), language_type: LanguageType::Programming, color: None, group: Some("TypeScript") }),
        ("Cloud Firestore Security Rules", Language { name: "Cloud Firestore Security Rules", ext: None, language_type: LanguageType::Data, color: None, group: None }),
        ("PureScript", Language { name: "PureScript", ext: Some("purs"), language_type: LanguageType::Programming, color: Some("#1D222D"), group: None }),
        ("Open Policy Agent", Language { name: "Open Policy Agent", ext: Some("rego"), language_type: LanguageType::Programming, color: None, group: None }),
        ("Graphviz (DOT)", Language { name: "Graphviz (DOT)", ext: Some("dot"), language_type: LanguageType::Data, color: None, group: None }),
        ("OpenSCAD", Language { name: "OpenSCAD", ext: Some("scad"), language_type: LanguageType::Programming, color: None, group: None }),
        ("DIGITAL Command Language", Language { name: "DIGITAL Command Language", ext: Some("com"), language_type: LanguageType::Programming, color: None, group: None }),
        ("MiniD", Language { name: "MiniD", ext: Some("minid"), language_type: LanguageType::Programming, color: None, group: None }),
        ("C2hs Haskell", Language { name: "C2hs Haskell", ext: Some("chs"), language_type: LanguageType::Programming, color: None, group: Some("Haskell") }),
        ("Monkey", Language { name: "Monkey", ext: Some("monkey"), language_type: LanguageType::Programming, color: None, group: None }),
        ("F*", Language { name: "F*", ext: Some("fst"), language_type: LanguageType::Programming, color: Some("#572e30"), group: None }),
        ("Unity3D Asset", Language { name: "Unity3D Asset", ext: Some("anim"), language_type: LanguageType::Data, color: None, group: None }),
        ("GCC Machine Description", Language { name: "GCC Machine Description", ext: Some("md"), language_type: LanguageType::Programming, color: None, group: None }),
        ("PogoScript", Language { name: "PogoScript", ext: Some("pogo"), language_type: LanguageType::Programming, color: Some("#d80074"), group: None }),
        ("CSS", Language { name: "CSS", ext: Some("css"), language_type: LanguageType::Markup, color: Some("#563d7c"), group: None }),
        ("1C Enterprise", Language { name: "1C Enterprise", ext: Some("bsl"), language_type: LanguageType::Programming, color: Some("#814CCC"), group: None }),
        ("ooc", Language { name: "ooc", ext: Some("ooc"), language_type: LanguageType::Programming, color: Some("#b0b77e"), group: None }),
        ("ChucK", Language { name: "ChucK", ext: Some("ck"), language_type: LanguageType::Programming, color: None, group: None }),
        ("SmPL", Language { name: "SmPL", ext: Some("cocci"), language_type: LanguageType::Programming, color: Some("#c94949"), group: None }),
        ("Cuda", Language { name: "Cuda", ext: Some("cu"), language_type: LanguageType::Programming, color: Some("#3A4E3A"), group: None }),
        ("Modula-2", Language { name: "Modula-2", ext: Some("mod"), language_type: LanguageType::Programming, color: None, group: None }),
        ("Literate CoffeeScript", Language { name: "Literate CoffeeScript", ext: Some("litcoffee"), language_type: LanguageType::Programming, color: None, group: Some("CoffeeScript") }),
        ("Elixir", Language { name: "Elixir", ext: Some("ex"), language_type: LanguageType::Programming, color: Some("#6e4a7e"), group: None }),
        ("ZIL", Language { name: "ZIL", ext: Some("zil"), language_type: LanguageType::Programming, color: Some("#dc75e5"), group: None }),
        ("Faust", Language { name: "Faust", ext: Some("dsp"), language_type: LanguageType::Programming, color: Some("#c37240"), group: None }),
        ("PLSQL", Language { name: "PLSQL", ext: Some("pls"), language_type: LanguageType::Programming, color: Some("#dad8d8"), group: None }),
        ("Squirrel", Language { name: "Squirrel", ext: Some("nut"), language_type: LanguageType::Programming, color: Some("#800000"), group: None }),
        ("Agda", Language { name: "Agda", ext: Some("agda"), language_type: LanguageType::Programming, color: Some("#315665"), group: None }),
        ("Git Config", Language { name: "Git Config", ext: Some("gitconfig"), language_type: LanguageType::Data, color: None, group: Some("INI") }),
        ("LilyPond", Language { name: "LilyPond", ext: Some("ly"), language_type: LanguageType::Programming, color: None, group: None }),
        ("Coq", Language { name: "Coq", ext: Some("coq"), language_type: LanguageType::Programming, color: None, group: None }),
        ("Cython", Language { name: "Cython", ext: Some("pyx"), language_type: LanguageType::Programming, color: None, group: Some("Python") }),
        ("Pep8", Language { name: "Pep8", ext: Some("pep"), language_type: LanguageType::Programming, color: Some("#C76F5B"), group: None }),
        ("FIGlet Font", Language { name: "FIGlet Font", ext: Some("flf"), language_type: LanguageType::Data, color: None, group: None }),
        ("ZAP", Language { name: "ZAP", ext: Some("zap"), language_type: LanguageType::Programming, color: Some("#0d665e"), group: None }),
        ("Red", Language { name: "Red", ext: Some("red"), language_type: LanguageType::Programming, color: Some("#f50000"), group: None }),
        ("Parrot", Language { name: "Parrot", ext: Some("parrot"), language_type: LanguageType::Programming, color: Some("#f3ca0a"), group: None }),
        ("Pure Data", Language { name: "Pure Data", ext: Some("pd"), language_type: LanguageType::Data, color: None, group: None }),
        ("Type Language", Language { name: "Type Language", ext: Some("tl"), language_type: LanguageType::Data, color: None, group: None }),
        ("Apex", Language { name: "Apex", ext: Some("cls"), language_type: LanguageType::Programming, color: None, group: None }),
        ("J", Language { name: "J", ext: Some("ijs"), language_type: LanguageType::Programming, color: Some("#9EEDFF"), group: None }),
        ("COLLADA", Language { name: "COLLADA", ext: Some("dae"), language_type: LanguageType::Data, color: None, group: None }),
        ("Jupyter Notebook", Language { name: "Jupyter Notebook", ext: Some("ipynb"), language_type: LanguageType::Markup, color: Some("#DA5B0B"), group: None }),
        ("CSON", Language { name: "CSON", ext: Some("cson"), language_type: LanguageType::Data, color: None, group: None }),
        ("TI Program", Language { name: "TI Program", ext: Some("8xp"), language_type: LanguageType::Programming, color: Some("#A0AA87"), group: None }),
        ("SWIG", Language { name: "SWIG", ext: Some("i"), language_type: LanguageType::Programming, color: None, group: None }),
        ("Nim", Language { name: "Nim", ext: Some("nim"), language_type: LanguageType::Programming, color: Some("#37775b"), group: None }),
        ("TLA", Language { name: "TLA", ext: Some("tla"), language_type: LanguageType::Programming, color: None, group: None }),
        ("YANG", Language { name: "YANG", ext: Some("yang"), language_type: LanguageType::Data, color: None, group: None }),
        ("X Font Directory Index", Language { name: "X Font Directory Index", ext: None, language_type: LanguageType::Data, color: None, group: None }),
        ("Ada", Language { name: "Ada", ext: Some("adb"), language_type: LanguageType::Programming, color: Some("#02f88c"), group: None }),
        ("GAML", Language { name: "GAML", ext: Some("gaml"), language_type: LanguageType::Programming, color: Some("#FFC766"), group: None }),
        ("HTML+Django", Language { name: "HTML+Django", ext: Some("jinja"), language_type: LanguageType::Markup, color: None, group: Some("HTML") }),
        ("Mask", Language { name: "Mask", ext: Some("mask"), language_type: LanguageType::Markup, color: Some("#f97732"), group: None }),
        ("Common Workflow Language", Language { name: "Common Workflow Language", ext: Some("cwl"), language_type: LanguageType::Programming, color: Some("#B5314C"), group: None }),
        ("VCL", Language { name: "VCL", ext: Some("vcl"), language_type: LanguageType::Programming, color: Some("#148AA8"), group: None }),
        ("Eagle", Language { name: "Eagle", ext: Some("sch"), language_type: LanguageType::Data, color: None, group: None }),
        ("PostCSS", Language { name: "PostCSS", ext: Some("pcss"), language_type: LanguageType::Markup, color: None, group: Some("CSS") }),
        ("OpenStep Property List", Language { name: "OpenStep Property List", ext: Some("plist"), language_type: LanguageType::Data, color: None, group: None }),
        ("EJS", Language { name: "EJS", ext: Some("ejs"), language_type: LanguageType::Markup, color: None, group: Some("HTML") }),
        ("UrWeb", Language { name: "UrWeb", ext: Some("ur"), language_type: LanguageType::Programming, color: None, group: None }),
        ("ObjectScript", Language { name: "ObjectScript", ext: Some("cls"), language_type: LanguageType::Programming, color: Some("#424893"), group: None }),
        ("LFE", Language { name: "LFE", ext: Some("lfe"), language_type: LanguageType::Programming, color: Some("#4C3023"), group: None }),
        ("HTML+ECR", Language { name: "HTML+ECR", ext: Some("ecr"), language_type: LanguageType::Markup, color: None, group: Some("HTML") }),
        ("JavaScript", Language { name: "JavaScript", ext: Some("js"), language_type: LanguageType::Programming, color: Some("#f1e05a"), group: None }),
        ("Reason", Language { name: "Reason", ext: Some("re"), language_type: LanguageType::Programming, color: Some("#ff5847"), group: None }),
        ("BibTeX", Language { name: "BibTeX", ext: Some("bib"), language_type: LanguageType::Markup, color: None, group: Some("TeX") }),
        ("Starlark", Language { name: "Starlark", ext: Some("bzl"), language_type: LanguageType::Programming, color: Some("#76d275"), group: None }),
        ("Module Management System", Language { name: "Module Management System", ext: Some("mms"), language_type: LanguageType::Programming, color: None, group: None }),
        ("TSQL", Language { name: "TSQL", ext: Some("sql"), language_type: LanguageType::Programming, color: None, group: None }),
        ("RUNOFF", Language { name: "RUNOFF", ext: Some("rnh"), language_type: LanguageType::Markup, color: Some("#665a4e"), group: None }),
        ("Cool", Language { name: "Cool", ext: Some("cl"), language_type: LanguageType::Programming, color: None, group: None }),
        ("ECLiPSe", Language { name: "ECLiPSe", ext: Some("ecl"), language_type: LanguageType::Programming, color: None, group: Some("prolog") }),
        ("HiveQL", Language { name: "HiveQL", ext: Some("q"), language_type: LanguageType::Programming, color: Some("#dce200"), group: None }),
        ("XS", Language { name: "XS", ext: Some("xs"), language_type: LanguageType::Programming, color: None, group: None }),
        ("UnrealScript", Language { name: "UnrealScript", ext: Some("uc"), language_type: LanguageType::Programming, color: Some("#a54c4d"), group: None }),
        ("XCompose", Language { name: "XCompose", ext: None, language_type: LanguageType::Data, color: None, group: None }),
        ("Lasso", Language { name: "Lasso", ext: Some("lasso"), language_type: LanguageType::Programming, color: Some("#999999"), group: None }),
        ("Java", Language { name: "Java", ext: Some("java"), language_type: LanguageType::Programming, color: Some("#b07219"), group: None }),
        ("MUF", Language { name: "MUF", ext: Some("muf"), language_type: LanguageType::Programming, color: None, group: Some("Forth") }),
        ("Java Server Pages", Language { name: "Java Server Pages", ext: Some("jsp"), language_type: LanguageType::Programming, color: None, group: Some("Java") }),
        ("Zig", Language { name: "Zig", ext: Some("zig"), language_type: LanguageType::Programming, color: Some("#ec915c"), group: None }),
        ("HTTP", Language { name: "HTTP", ext: Some("http"), language_type: LanguageType::Data, color: None, group: None }),
        ("Jolie", Language { name: "Jolie", ext: Some("ol"), language_type: LanguageType::Programming, color: Some("#843179"), group: None }),
        ("CoffeeScript", Language { name: "CoffeeScript", ext: Some("coffee"), language_type: LanguageType::Programming, color: Some("#244776"), group: None }),
        ("HTML+ERB", Language { name: "HTML+ERB", ext: Some("erb"), language_type: LanguageType::Markup, color: None, group: Some("HTML") }),
        ("Bison", Language { name: "Bison", ext: Some("bison"), language_type: LanguageType::Programming, color: None, group: Some("Yacc") }),
        ("JSON5", Language { name: "JSON5", ext: Some("json5"), language_type: LanguageType::Data, color: None, group: None }),
        ("BitBake", Language { name: "BitBake", ext: Some("bb"), language_type: LanguageType::Programming, color: None, group: None }),
        ("Python console", Language { name: "Python console", ext: None, language_type: LanguageType::Programming, color: None, group: Some("Python") }),
        ("Rust", Language { name: "Rust", ext: Some("rs"), language_type: LanguageType::Programming, color: Some("#dea584"), group: None }),
        ("C", Language { name: "C", ext: Some("c"), language_type: LanguageType::Programming, color: Some("#555555"), group: None }),
        ("Creole", Language { name: "Creole", ext: Some("creole"), language_type: LanguageType::Prose, color: None, group: None }),
        ("Idris", Language { name: "Idris", ext: Some("idr"), language_type: LanguageType::Programming, color: Some("#b30000"), group: None }),
        ("Web Ontology Language", Language { name: "Web Ontology Language", ext: Some("owl"), language_type: LanguageType::Data, color: None, group: None }),
        ("OpenEdge ABL", Language { name: "OpenEdge ABL", ext: Some("p"), language_type: LanguageType::Programming, color: None, group: None }),
        ("POV-Ray SDL", Language { name: "POV-Ray SDL", ext: Some("pov"), language_type: LanguageType::Programming, color: None, group: None }),
        ("RPM Spec", Language { name: "RPM Spec", ext: Some("spec"), language_type: LanguageType::Data, color: None, group: None }),
        ("KiCad Schematic", Language { name: "KiCad Schematic", ext: Some("sch"), language_type: LanguageType::Data, color: None, group: None }),
        ("mIRC Script", Language { name: "mIRC Script", ext: Some("mrc"), language_type: LanguageType::Programming, color: Some("#926059"), group: None }),
        ("Forth", Language { name: "Forth", ext: Some("fth"), language_type: LanguageType::Programming, color: Some("#341708"), group: None }),
        ("HXML", Language { name: "HXML", ext: Some("hxml"), language_type: LanguageType::Data, color: None, group: None }),
        ("Cpp-ObjDump", Language { name: "Cpp-ObjDump", ext: Some("cppobjdump"), language_type: LanguageType::Data, color: None, group: None }),
        ("M4", Language { name: "M4", ext: Some("m4"), language_type: LanguageType::Programming, color: None, group: None }),
        ("Rich Text Format", Language { name: "Rich Text Format", ext: Some("rtf"), language_type: LanguageType::Markup, color: None, group: None }),
        ("Parrot Internal Representation", Language { name: "Parrot Internal Representation", ext: Some("pir"), language_type: LanguageType::Programming, color: None, group: Some("Parrot") }),
        ("Asymptote", Language { name: "Asymptote", ext: Some("asy"), language_type: LanguageType::Programming, color: Some("#4a0c0c"), group: None }),
        ("PlantUML", Language { name: "PlantUML", ext: Some("puml"), language_type: LanguageType::Data, color: None, group: None }),
        ("GLSL", Language { name: "GLSL", ext: Some("glsl"), language_type: LanguageType::Programming, color: None, group: None }),
        ("Assembly", Language { name: "Assembly", ext: Some("asm"), language_type: LanguageType::Programming, color: Some("#6E4C13"), group: None }),
        ("E", Language { name: "E", ext: Some("E"), language_type: LanguageType::Programming, color: Some("#ccce35"), group: None }),
        ("X PixMap", Language { name: "X PixMap", ext: Some("xpm"), language_type: LanguageType::Data, color: None, group: Some("C") }),
        ("Fantom", Language { name: "Fantom", ext: Some("fan"), language_type: LanguageType::Programming, color: Some("#14253c"), group: None }),
        ("MLIR", Language { name: "MLIR", ext: Some("mlir"), language_type: LanguageType::Programming, color: Some("#5EC8DB"), group: None }),
        ("Haskell", Language { name: "Haskell", ext: Some("hs"), language_type: LanguageType::Programming, color: Some("#5e5086"), group: None }),
        ("REXX", Language { name: "REXX", ext: Some("rexx"), language_type: LanguageType::Programming, color: None, group: None }),
        ("X10", Language { name: "X10", ext: Some("x10"), language_type: LanguageType::Programming, color: Some("#4B6BEF"), group: None }),
        ("Clean", Language { name: "Clean", ext: Some("icl"), language_type: LanguageType::Programming, color: Some("#3F85AF"), group: None }),
        ("Odin", Language { name: "Odin", ext: Some("odin"), language_type: LanguageType::Programming, color: Some("#60AFFE"), group: None }),
        ("q", Language { name: "q", ext: Some("q"), language_type: LanguageType::Programming, color: Some("#0040cd"), group: None }),
        ("INI", Language { name: "INI", ext: Some("ini"), language_type: LanguageType::Data, color: None, group: None }),
        ("NPM Config", Language { name: "NPM Config", ext: None, language_type: LanguageType::Data, color: None, group: Some("INI") }),
        ("Turtle", Language { name: "Turtle", ext: Some("ttl"), language_type: LanguageType::Data, color: None, group: None }),
        ("AsciiDoc", Language { name: "AsciiDoc", ext: Some("asciidoc"), language_type: LanguageType::Prose, color: None, group: None }),
        ("PigLatin", Language { name: "PigLatin", ext: Some("pig"), language_type: LanguageType::Programming, color: Some("#fcd7de"), group: None }),
        ("SugarSS", Language { name: "SugarSS", ext: Some("sss"), language_type: LanguageType::Markup, color: None, group: Some("CSS") }),
        ("LiveScript", Language { name: "LiveScript", ext: Some("ls"), language_type: LanguageType::Programming, color: Some("#499886"), group: None }),
        ("Pawn", Language { name: "Pawn", ext: Some("pwn"), language_type: LanguageType::Programming, color: Some("#dbb284"), group: None }),
        ("Clojure", Language { name: "Clojure", ext: Some("clj"), language_type: LanguageType::Programming, color: Some("#db5855"), group: None }),
        ("Hy", Language { name: "Hy", ext: Some("hy"), language_type: LanguageType::Programming, color: Some("#7790B2"), group: None }),
        ("Csound Document", Language { name: "Csound Document", ext: Some("csd"), language_type: LanguageType::Programming, color: None, group: None }),
        ("Erlang", Language { name: "Erlang", ext: Some("erl"), language_type: LanguageType::Programming, color: Some("#B83998"), group: None }),
        ("JSX", Language { name: "JSX", ext: Some("jsx"), language_type: LanguageType::Programming, color: None, group: Some("JavaScript") }),
        ("Roff", Language { name: "Roff", ext: Some("roff"), language_type: LanguageType::Markup, color: Some("#ecdebe"), group: None }),
        ("edn", Language { name: "edn", ext: Some("edn"), language_type: LanguageType::Data, color: None, group: None }),
        ("Fancy", Language { name: "Fancy", ext: Some("fy"), language_type: LanguageType::Programming, color: Some("#7b9db4"), group: None }),
        ("ECL", Language { name: "ECL", ext: Some("ecl"), language_type: LanguageType::Programming, color: Some("#8a1267"), group: None }),
        ("GN", Language { name: "GN", ext: Some("gn"), language_type: LanguageType::Data, color: None, group: None }),
        ("Filterscript", Language { name: "Filterscript", ext: Some("fs"), language_type: LanguageType::Programming, color: None, group: Some("RenderScript") }),
        ("Csound", Language { name: "Csound", ext: Some("orc"), language_type: LanguageType::Programming, color: None, group: None }),
        ("Handlebars", Language { name: "Handlebars", ext: Some("handlebars"), language_type: LanguageType::Markup, color: None, group: Some("HTML") }),
        ("Swift", Language { name: "Swift", ext: Some("swift"), language_type: LanguageType::Programming, color: Some("#ffac45"), group: None }),
        ("Emacs Lisp", Language { name: "Emacs Lisp", ext: Some("el"), language_type: LanguageType::Programming, color: Some("#c065db"), group: None }),
        ("Propeller Spin", Language { name: "Propeller Spin", ext: Some("spin"), language_type: LanguageType::Programming, color: Some("#7fa2a7"), group: None }),
        ("Limbo", Language { name: "Limbo", ext: Some("b"), language_type: LanguageType::Programming, color: None, group: None }),
        ("Diff", Language { name: "Diff", ext: Some("diff"), language_type: LanguageType::Data, color: None, group: None }),
        ("Redcode", Language { name: "Redcode", ext: Some("cw"), language_type: LanguageType::Programming, color: None, group: None }),
        ("Oxygene", Language { name: "Oxygene", ext: Some("oxygene"), language_type: LanguageType::Programming, color: Some("#cdd0e3"), group: None }),
        ("Lean", Language { name: "Lean", ext: Some("lean"), language_type: LanguageType::Programming, color: None, group: None }),
        ("Befunge", Language { name: "Befunge", ext: Some("befunge"), language_type: LanguageType::Programming, color: None, group: None }),
        ("Nearley", Language { name: "Nearley", ext: Some("ne"), language_type: LanguageType::Programming, color: Some("#990000"), group: None }),
        ("Riot", Language { name: "Riot", ext: Some("riot"), language_type: LanguageType::Markup, color: Some("#A71E49"), group: None }),
        ("RHTML", Language { name: "RHTML", ext: Some("rhtml"), language_type: LanguageType::Markup, color: None, group: Some("HTML") }),
        ("RPC", Language { name: "RPC", ext: Some("x"), language_type: LanguageType::Programming, color: None, group: None }),
        ("EmberScript", Language { name: "EmberScript", ext: Some("em"), language_type: LanguageType::Programming, color: Some("#FFF4F3"), group: None }),
        ("AGS Script", Language { name: "AGS Script", ext: Some("asc"), language_type: LanguageType::Programming, color: Some("#B9D9FF"), group: None }),
        ("WebAssembly", Language { name: "WebAssembly", ext: Some("wast"), language_type: LanguageType::Programming, color: Some("#04133b"), group: None }),
        ("Genshi", Language { name: "Genshi", ext: Some("kid"), language_type: LanguageType::Programming, color: None, group: None }),
        ("SQLPL", Language { name: "SQLPL", ext: Some("sql"), language_type: LanguageType::Programming, color: None, group: None }),
        ("4D", Language { name: "4D", ext: Some("4dm"), language_type: LanguageType::Programming, color: None, group: None }),
        ("Protocol Buffer", Language { name: "Protocol Buffer", ext: Some("proto"), language_type: LanguageType::Data, color: None, group: None }),
        ("Microsoft Developer Studio Project", Language { name: "Microsoft Developer Studio Project", ext: Some("dsp"), language_type: LanguageType::Data, color: None, group: None }),
        ("PostScript", Language { name: "PostScript", ext: Some("ps"), language_type: LanguageType::Markup, color: Some("#da291c"), group: None }),
        ("Gosu", Language { name: "Gosu", ext: Some("gs"), language_type: LanguageType::Programming, color: Some("#82937f"), group: None }),
        ("Pod 6", Language { name: "Pod 6", ext: Some("pod"), language_type: LanguageType::Prose, color: None, group: None }),
        ("SAS", Language { name: "SAS", ext: Some("sas"), language_type: LanguageType::Programming, color: Some("#B34936"), group: None }),
        ("Wollok", Language { name: "Wollok", ext: Some("wlk"), language_type: LanguageType::Programming, color: Some("#a23738"), group: None }),
        ("KiCad Layout", Language { name: "KiCad Layout", ext: Some("kicad_pcb"), language_type: LanguageType::Data, color: None, group: None }),
        ("Gentoo Ebuild", Language { name: "Gentoo Ebuild", ext: Some("ebuild"), language_type: LanguageType::Programming, color: None, group: Some("Shell") }),
        ("Org", Language { name: "Org", ext: Some("org"), language_type: LanguageType::Prose, color: None, group: None }),
        ("AutoIt", Language { name: "AutoIt", ext: Some("au3"), language_type: LanguageType::Programming, color: Some("#1C3552"), group: None }),
        ("Quake", Language { name: "Quake", ext: None, language_type: LanguageType::Programming, color: Some("#882233"), group: None }),
        ("desktop", Language { name: "desktop", ext: Some("desktop"), language_type: LanguageType::Data, color: None, group: None }),
        ("OpenType Feature File", Language { name: "OpenType Feature File", ext: Some("fea"), language_type: LanguageType::Data, color: None, group: None }),
        ("Fortran", Language { name: "Fortran", ext: Some("f90"), language_type: LanguageType::Programming, color: Some("#4d41b1"), group: None }),
        ("Brainfuck", Language { name: "Brainfuck", ext: Some("b"), language_type: LanguageType::Programming, color: Some("#2F2530"), group: None }),
        ("Ioke", Language { name: "Ioke", ext: Some("ik"), language_type: LanguageType::Programming, color: Some("#078193"), group: None }),
        ("Hack", Language { name: "Hack", ext: Some("hack"), language_type: LanguageType::Programming, color: Some("#878787"), group: None }),
        ("PowerBuilder", Language { name: "PowerBuilder", ext: Some("pbt"), language_type: LanguageType::Programming, color: Some("#8f0f8d"), group: None }),
        ("ABNF", Language { name: "ABNF", ext: Some("abnf"), language_type: LanguageType::Data, color: None, group: None }),
        ("NetLogo", Language { name: "NetLogo", ext: Some("nlogo"), language_type: LanguageType::Programming, color: Some("#ff6375"), group: None }),
        ("Shen", Language { name: "Shen", ext: Some("shen"), language_type: LanguageType::Programming, color: Some("#120F14"), group: None }),
        ("RAML", Language { name: "RAML", ext: Some("raml"), language_type: LanguageType::Markup, color: Some("#77d9fb"), group: None }),
        ("Readline Config", Language { name: "Readline Config", ext: None, language_type: LanguageType::Data, color: None, group: Some("INI") }),
        ("Io", Language { name: "Io", ext: Some("io"), language_type: LanguageType::Programming, color: Some("#a9188d"), group: None }),
        ("XML", Language { name: "XML", ext: Some("xml"), language_type: LanguageType::Data, color: None, group: None }),
        ("Pickle", Language { name: "Pickle", ext: Some("pkl"), language_type: LanguageType::Data, color: None, group: None }),
        ("Muse", Language { name: "Muse", ext: Some("muse"), language_type: LanguageType::Prose, color: None, group: None }),
        ("Solidity", Language { name: "Solidity", ext: None, language_type: LanguageType::Programming, color: Some("#AA6746"), group: None }),
        ("Rouge", Language { name: "Rouge", ext: Some("rg"), language_type: LanguageType::Programming, color: Some("#cc0088"), group: None }),
        ("LSL", Language { name: "LSL", ext: Some("lsl"), language_type: LanguageType::Programming, color: Some("#3d9970"), group: None }),
        ("SSH Config", Language { name: "SSH Config", ext: None, language_type: LanguageType::Data, color: None, group: Some("INI") }),
        ("VHDL", Language { name: "VHDL", ext: Some("vhdl"), language_type: LanguageType::Programming, color: Some("#adb2cb"), group: None }),
        ("Motorola 68K Assembly", Language { name: "Motorola 68K Assembly", ext: Some("asm"), language_type: LanguageType::Programming, color: None, group: Some("Assembly") }),
        ("Smalltalk", Language { name: "Smalltalk", ext: Some("st"), language_type: LanguageType::Programming, color: Some("#596706"), group: None }),
        ("Logos", Language { name: "Logos", ext: Some("xm"), language_type: LanguageType::Programming, color: None, group: None }),
        ("EBNF", Language { name: "EBNF", ext: Some("ebnf"), language_type: LanguageType::Data, color: None, group: None }),
        ("AppleScript", Language { name: "AppleScript", ext: Some("applescript"), language_type: LanguageType::Programming, color: Some("#101F1F"), group: None }),
        ("DNS Zone", Language { name: "DNS Zone", ext: Some("zone"), language_type: LanguageType::Data, color: None, group: None }),
        ("World of Warcraft Addon Data", Language { name: "World of Warcraft Addon Data", ext: Some("toc"), language_type: LanguageType::Data, color: None, group: None }),
        ("AutoHotkey", Language { name: "AutoHotkey", ext: Some("ahk"), language_type: LanguageType::Programming, color: Some("#6594b9"), group: None }),
        ("HyPhy", Language { name: "HyPhy", ext: Some("bf"), language_type: LanguageType::Programming, color: None, group: None }),
        ("OpenRC runscript", Language { name: "OpenRC runscript", ext: None, language_type: LanguageType::Programming, color: None, group: Some("Shell") }),
        ("Vim script", Language { name: "Vim script", ext: Some("vim"), language_type: LanguageType::Programming, color: Some("#199f4b"), group: None }),
        ("Dockerfile", Language { name: "Dockerfile", ext: Some("dockerfile"), language_type: LanguageType::Programming, color: Some("#384d54"), group: None }),
        ("PLpgSQL", Language { name: "PLpgSQL", ext: Some("pgsql"), language_type: LanguageType::Programming, color: None, group: None }),
        ("EditorConfig", Language { name: "EditorConfig", ext: None, language_type: LanguageType::Data, color: None, group: Some("INI") }),
        ("Lex", Language { name: "Lex", ext: Some("l"), language_type: LanguageType::Programming, color: Some("#DBCA00"), group: None }),
        ("XQuery", Language { name: "XQuery", ext: Some("xquery"), language_type: LanguageType::Programming, color: Some("#5232e7"), group: None }),
        ("TypeScript", Language { name: "TypeScript", ext: Some("ts"), language_type: LanguageType::Programming, color: Some("#2b7489"), group: None }),
        ("Ecere Projects", Language { name: "Ecere Projects", ext: Some("epj"), language_type: LanguageType::Data, color: None, group: Some("JavaScript") }),
        ("Genie", Language { name: "Genie", ext: Some("gs"), language_type: LanguageType::Programming, color: Some("#fb855d"), group: None }),
        ("ActionScript", Language { name: "ActionScript", ext: Some("as"), language_type: LanguageType::Programming, color: Some("#882B0F"), group: None }),
        ("Chapel", Language { name: "Chapel", ext: Some("chpl"), language_type: LanguageType::Programming, color: Some("#8dc63f"), group: None }),
        ("Game Maker Language", Language { name: "Game Maker Language", ext: Some("gml"), language_type: LanguageType::Programming, color: Some("#71b417"), group: None }),
        ("RenderScript", Language { name: "RenderScript", ext: Some("rs"), language_type: LanguageType::Programming, color: None, group: None }),
        ("Formatted", Language { name: "Formatted", ext: Some("for"), language_type: LanguageType::Data, color: None, group: None }),
        ("Raku", Language { name: "Raku", ext: Some("6pl"), language_type: LanguageType::Programming, color: Some("#0000fb"), group: None }),
        ("XProc", Language { name: "XProc", ext: Some("xpl"), language_type: LanguageType::Programming, color: None, group: None }),
        ("Mako", Language { name: "Mako", ext: Some("mako"), language_type: LanguageType::Programming, color: None, group: None }),
        ("Factor", Language { name: "Factor", ext: Some("factor"), language_type: LanguageType::Programming, color: Some("#636746"), group: None }),
        ("Common Lisp", Language { name: "Common Lisp", ext: Some("lisp"), language_type: LanguageType::Programming, color: Some("#3fb68b"), group: None }),
        ("WebIDL", Language { name: "WebIDL", ext: Some("webidl"), language_type: LanguageType::Programming, color: None, group: None }),
        ("Textile", Language { name: "Textile", ext: Some("textile"), language_type: LanguageType::Prose, color: None, group: None }),
        ("CoNLL-U", Language { name: "CoNLL-U", ext: Some("conllu"), language_type: LanguageType::Data, color: None, group: None }),
        ("Volt", Language { name: "Volt", ext: Some("volt"), language_type: LanguageType::Programming, color: Some("#1F1F1F"), group: None }),
        ("M", Language { name: "M", ext: Some("mumps"), language_type: LanguageType::Programming, color: None, group: None }),
        ("Blade", Language { name: "Blade", ext: Some("blade"), language_type: LanguageType::Markup, color: None, group: Some("HTML") }),
        ("PowerShell", Language { name: "PowerShell", ext: Some("ps1"), language_type: LanguageType::Programming, color: Some("#012456"), group: None }),
        ("Verilog", Language { name: "Verilog", ext: Some("v"), language_type: LanguageType::Programming, color: Some("#b2b7f8"), group: None }),
        ("Meson", Language { name: "Meson", ext: None, language_type: LanguageType::Programming, color: Some("#007800"), group: None }),
        ("NetLinx", Language { name: "NetLinx", ext: Some("axs"), language_type: LanguageType::Programming, color: Some("#0aa0ff"), group: None }),
        ("JSON with Comments", Language { name: "JSON with Comments", ext: Some("jsonc"), language_type: LanguageType::Data, color: None, group: Some("JSON") }),
        ("LTspice Symbol", Language { name: "LTspice Symbol", ext: Some("asy"), language_type: LanguageType::Data, color: None, group: None }),
        ("Ceylon", Language { name: "Ceylon", ext: Some("ceylon"), language_type: LanguageType::Programming, color: Some("#dfa535"), group: None }),
        ("IGOR Pro", Language { name: "IGOR Pro", ext: Some("ipf"), language_type: LanguageType::Programming, color: Some("#0000cc"), group: None }),
        ("Spline Font Database", Language { name: "Spline Font Database", ext: Some("sfd"), language_type: LanguageType::Data, color: None, group: None }),
        ("Alloy", Language { name: "Alloy", ext: Some("als"), language_type: LanguageType::Programming, color: Some("#64C800"), group: None }),
        ("YASnippet", Language { name: "YASnippet", ext: Some("yasnippet"), language_type: LanguageType::Markup, color: Some("#32AB90"), group: None }),
        ("Isabelle", Language { name: "Isabelle", ext: Some("thy"), language_type: LanguageType::Programming, color: Some("#FEFE00"), group: None }),
        ("GDB", Language { name: "GDB", ext: Some("gdb"), language_type: LanguageType::Programming, color: None, group: None }),
        ("Adobe Font Metrics", Language { name: "Adobe Font Metrics", ext: Some("afm"), language_type: LanguageType::Data, color: None, group: None }),
        ("Latte", Language { name: "Latte", ext: Some("latte"), language_type: LanguageType::Markup, color: None, group: Some("HTML") }),
        ("NL", Language { name: "NL", ext: Some("nl"), language_type: LanguageType::Data, color: None, group: None }),
        ("SQL", Language { name: "SQL", ext: Some("sql"), language_type: LanguageType::Data, color: None, group: None }),
        ("Lua", Language { name: "Lua", ext: Some("lua"), language_type: LanguageType::Programming, color: Some("#000080"), group: None }),
        ("Shell", Language { name: "Shell", ext: Some("sh"), language_type: LanguageType::Programming, color: Some("#89e051"), group: None }),
        ("Gnuplot", Language { name: "Gnuplot", ext: Some("gp"), language_type: LanguageType::Programming, color: Some("#f0a9f0"), group: None }),
        ("SPARQL", Language { name: "SPARQL", ext: Some("sparql"), language_type: LanguageType::Data, color: None, group: None }),
        ("Wavefront Material", Language { name: "Wavefront Material", ext: Some("mtl"), language_type: LanguageType::Data, color: None, group: None }),
        ("Parrot Assembly", Language { name: "Parrot Assembly", ext: Some("pasm"), language_type: LanguageType::Programming, color: None, group: Some("Parrot") }),
        ("OCaml", Language { name: "OCaml", ext: Some("ml"), language_type: LanguageType::Programming, color: Some("#3be133"), group: None }),
        ("Zimpl", Language { name: "Zimpl", ext: Some("zimpl"), language_type: LanguageType::Programming, color: None, group: None }),
        ("Kit", Language { name: "Kit", ext: Some("kit"), language_type: LanguageType::Markup, color: None, group: None }),
        ("wdl", Language { name: "wdl", ext: Some("wdl"), language_type: LanguageType::Programming, color: Some("#42f1f4"), group: None }),
        ("Ninja", Language { name: "Ninja", ext: Some("ninja"), language_type: LanguageType::Data, color: None, group: None }),
        ("Ring", Language { name: "Ring", ext: Some("ring"), language_type: LanguageType::Programming, color: Some("#2D54CB"), group: None }),
        ("AspectJ", Language { name: "AspectJ", ext: Some("aj"), language_type: LanguageType::Programming, color: Some("#a957b0"), group: None }),
        ("Cabal Config", Language { name: "Cabal Config", ext: Some("cabal"), language_type: LanguageType::Data, color: None, group: None }),
        ("Turing", Language { name: "Turing", ext: Some("t"), language_type: LanguageType::Programming, color: Some("#cf142b"), group: None }),
        ("TeX", Language { name: "TeX", ext: Some("tex"), language_type: LanguageType::Markup, color: Some("#3D6117"), group: None }),
        ("Awk", Language { name: "Awk", ext: Some("awk"), language_type: LanguageType::Programming, color: None, group: None }),
        ("MediaWiki", Language { name: "MediaWiki", ext: Some("mediawiki"), language_type: LanguageType::Prose, color: None, group: None }),
        ("Glyph", Language { name: "Glyph", ext: Some("glf"), language_type: LanguageType::Programming, color: Some("#c1ac7f"), group: None }),
        ("Haxe", Language { name: "Haxe", ext: Some("hx"), language_type: LanguageType::Programming, color: Some("#df7900"), group: None }),
        ("HLSL", Language { name: "HLSL", ext: Some("hlsl"), language_type: LanguageType::Programming, color: None, group: None }),
        ("TXL", Language { name: "TXL", ext: Some("txl"), language_type: LanguageType::Programming, color: None, group: None }),
        ("Standard ML", Language { name: "Standard ML", ext: Some("ML"), language_type: LanguageType::Programming, color: Some("#dc566d"), group: None }),
        ("Haml", Language { name: "Haml", ext: Some("haml"), language_type: LanguageType::Markup, color: None, group: Some("HTML") }),
        ("Python", Language { name: "Python", ext: Some("py"), language_type: LanguageType::Programming, color: Some("#3572A5"), group: None }),
        ("SuperCollider", Language { name: "SuperCollider", ext: Some("sc"), language_type: LanguageType::Programming, color: Some("#46390b"), group: None }),
        ("C#", Language { name: "C#", ext: Some("cs"), language_type: LanguageType::Programming, color: Some("#178600"), group: None }),
        ("ZenScript", Language { name: "ZenScript", ext: Some("zs"), language_type: LanguageType::Programming, color: Some("#00BCD1"), group: None }),
        ("Nu", Language { name: "Nu", ext: Some("nu"), language_type: LanguageType::Programming, color: Some("#c9df40"), group: None }),
        ("OpenCL", Language { name: "OpenCL", ext: Some("cl"), language_type: LanguageType::Programming, color: None, group: Some("C") }),
        ("Puppet", Language { name: "Puppet", ext: Some("pp"), language_type: LanguageType::Programming, color: Some("#302B6D"), group: None }),
        ("Texinfo", Language { name: "Texinfo", ext: Some("texinfo"), language_type: LanguageType::Prose, color: None, group: None }),
        ("API Blueprint", Language { name: "API Blueprint", ext: Some("apib"), language_type: LanguageType::Markup, color: Some("#2ACCA8"), group: None }),
        ("Scala", Language { name: "Scala", ext: Some("scala"), language_type: LanguageType::Programming, color: Some("#c22d40"), group: None }),
        ("Linker Script", Language { name: "Linker Script", ext: Some("ld"), language_type: LanguageType::Data, color: None, group: None }),
        ("Closure Templates", Language { name: "Closure Templates", ext: Some("soy"), language_type: LanguageType::Markup, color: None, group: Some("HTML") }),
        ("Ragel", Language { name: "Ragel", ext: Some("rl"), language_type: LanguageType::Programming, color: Some("#9d5200"), group: None }),
        ("Roff Manpage", Language { name: "Roff Manpage", ext: Some("1"), language_type: LanguageType::Markup, color: None, group: Some("Roff") }),
        ("Literate Haskell", Language { name: "Literate Haskell", ext: Some("lhs"), language_type: LanguageType::Programming, color: None, group: Some("Haskell") }),
        ("Thrift", Language { name: "Thrift", ext: Some("thrift"), language_type: LanguageType::Programming, color: None, group: None }),
        ("NewLisp", Language { name: "NewLisp", ext: Some("nl"), language_type: LanguageType::Programming, color: Some("#87AED7"), group: None }),
        ("Stata", Language { name: "Stata", ext: Some("do"), language_type: LanguageType::Programming, color: None, group: None }),
        ("Gerber Image", Language { name: "Gerber Image", ext: Some("gbr"), language_type: LanguageType::Data, color: None, group: None }),
        ("Gettext Catalog", Language { name: "Gettext Catalog", ext: Some("po"), language_type: LanguageType::Prose, color: None, group: None }),
        ("Smarty", Language { name: "Smarty", ext: Some("tpl"), language_type: LanguageType::Programming, color: None, group: None }),
        ("Pascal", Language { name: "Pascal", ext: Some("pas"), language_type: LanguageType::Programming, color: Some("#E3F171"), group: None }),
        ("Stylus", Language { name: "Stylus", ext: Some("styl"), language_type: LanguageType::Markup, color: None, group: Some("CSS") }),
        ("YARA", Language { name: "YARA", ext: Some("yar"), language_type: LanguageType::Programming, color: Some("#220000"), group: None }),
        ("Less", Language { name: "Less", ext: Some("less"), language_type: LanguageType::Markup, color: None, group: Some("CSS") }),
        ("BlitzMax", Language { name: "BlitzMax", ext: Some("bmx"), language_type: LanguageType::Programming, color: Some("#cd6400"), group: None }),
        ("Groovy", Language { name: "Groovy", ext: Some("groovy"), language_type: LanguageType::Programming, color: Some("#e69f56"), group: None }),
        ("F#", Language { name: "F#", ext: Some("fs"), language_type: LanguageType::Programming, color: Some("#b845fc"), group: None }),
        ("ASP", Language { name: "ASP", ext: Some("asp"), language_type: LanguageType::Programming, color: Some("#6a40fd"), group: None }),
        ("HTML+Razor", Language { name: "HTML+Razor", ext: Some("cshtml"), language_type: LanguageType::Markup, color: None, group: Some("HTML") }),
        ("BlitzBasic", Language { name: "BlitzBasic", ext: Some("bb"), language_type: LanguageType::Programming, color: None, group: None }),
        ("Scaml", Language { name: "Scaml", ext: Some("scaml"), language_type: LanguageType::Markup, color: None, group: Some("HTML") }),
        ("Prisma", Language { name: "Prisma", ext: Some("prisma"), language_type: LanguageType::Data, color: None, group: None }),
        ("Modula-3", Language { name: "Modula-3", ext: Some("i3"), language_type: LanguageType::Programming, color: Some("#223388"), group: None }),
        ("Charity", Language { name: "Charity", ext: Some("ch"), language_type: LanguageType::Programming, color: None, group: None }),
        ("Nix", Language { name: "Nix", ext: Some("nix"), language_type: LanguageType::Programming, color: Some("#7e7eff"), group: None }),
        ("LOLCODE", Language { name: "LOLCODE", ext: Some("lol"), language_type: LanguageType::Programming, color: Some("#cc9900"), group: None }),
        ("Rascal", Language { name: "Rascal", ext: Some("rsc"), language_type: LanguageType::Programming, color: Some("#fffaa0"), group: None }),
        ("Opal", Language { name: "Opal", ext: Some("opal"), language_type: LanguageType::Programming, color: Some("#f7ede0"), group: None }),
        ("SVG", Language { name: "SVG", ext: Some("svg"), language_type: LanguageType::Data, color: None, group: None }),
        ("DM", Language { name: "DM", ext: Some("dm"), language_type: LanguageType::Programming, color: Some("#447265"), group: None }),
        ("Dogescript", Language { name: "Dogescript", ext: Some("djs"), language_type: LanguageType::Programming, color: Some("#cca760"), group: None }),
        ("Zephir", Language { name: "Zephir", ext: Some("zep"), language_type: LanguageType::Programming, color: Some("#118f9e"), group: None }),
        ("xBase", Language { name: "xBase", ext: Some("prg"), language_type: LanguageType::Programming, color: Some("#403a40"), group: None }),
        ("FreeMarker", Language { name: "FreeMarker", ext: Some("ftl"), language_type: LanguageType::Programming, color: Some("#0050b2"), group: None }),
        ("MAXScript", Language { name: "MAXScript", ext: Some("ms"), language_type: LanguageType::Programming, color: Some("#00a6a6"), group: None }),
        ("Bluespec", Language { name: "Bluespec", ext: Some("bsv"), language_type: LanguageType::Programming, color: None, group: None }),
        ("nanorc", Language { name: "nanorc", ext: Some("nanorc"), language_type: LanguageType::Data, color: None, group: Some("INI") }),
        ("JSONLD", Language { name: "JSONLD", ext: Some("jsonld"), language_type: LanguageType::Data, color: None, group: None }),
        ("Harbour", Language { name: "Harbour", ext: Some("hb"), language_type: LanguageType::Programming, color: Some("#0e60e3"), group: None }),
        ("Unified Parallel C", Language { name: "Unified Parallel C", ext: Some("upc"), language_type: LanguageType::Programming, color: None, group: Some("C") }),
        ("PicoLisp", Language { name: "PicoLisp", ext: Some("l"), language_type: LanguageType::Programming, color: None, group: None }),
        ("JSONiq", Language { name: "JSONiq", ext: Some("jq"), language_type: LanguageType::Programming, color: Some("#40d47e"), group: None }),
        ("Batchfile", Language { name: "Batchfile", ext: Some("bat"), language_type: LanguageType::Programming, color: Some("#C1F12E"), group: None }),
        ("Augeas", Language { name: "Augeas", ext: Some("aug"), language_type: LanguageType::Programming, color: None, group: None }),
        ("D", Language { name: "D", ext: Some("d"), language_type: LanguageType::Programming, color: Some("#ba595e"), group: None }),
        ("Inform 7", Language { name: "Inform 7", ext: Some("ni"), language_type: LanguageType::Programming, color: None, group: None }),
        ("EQ", Language { name: "EQ", ext: Some("eq"), language_type: LanguageType::Programming, color: Some("#a78649"), group: None }),
        ("mcfunction", Language { name: "mcfunction", ext: Some("mcfunction"), language_type: LanguageType::Programming, color: Some("#E22837"), group: None }),
        ("Apollo Guidance Computer", Language { name: "Apollo Guidance Computer", ext: Some("agc"), language_type: LanguageType::Programming, color: None, group: Some("Assembly") }),
        ("ColdFusion CFC", Language { name: "ColdFusion CFC", ext: Some("cfc"), language_type: LanguageType::Programming, color: None, group: Some("ColdFusion") }),
        ("Edje Data Collection", Language { name: "Edje Data Collection", ext: Some("edc"), language_type: LanguageType::Data, color: None, group: None }),
        ("KiCad Legacy Layout", Language { name: "KiCad Legacy Layout", ext: Some("brd"), language_type: LanguageType::Data, color: None, group: None }),
        ("dircolors", Language { name: "dircolors", ext: Some("dircolors"), language_type: LanguageType::Data, color: None, group: None }),
        ("Sass", Language { name: "Sass", ext: Some("sass"), language_type: LanguageType::Markup, color: None, group: Some("CSS") }),
        ("ANTLR", Language { name: "ANTLR", ext: Some("g4"), language_type: LanguageType::Programming, color: Some("#9DC3FF"), group: None }),
        ("NSIS", Language { name: "NSIS", ext: Some("nsi"), language_type: LanguageType::Programming, color: None, group: None }),
        ("ShaderLab", Language { name: "ShaderLab", ext: Some("shader"), language_type: LanguageType::Programming, color: None, group: None }),
        ("Filebench WML", Language { name: "Filebench WML", ext: Some("f"), language_type: LanguageType::Programming, color: None, group: None }),
        ("mupad", Language { name: "mupad", ext: Some("mu"), language_type: LanguageType::Programming, color: None, group: None }),
        ("Glyph Bitmap Distribution Format", Language { name: "Glyph Bitmap Distribution Format", ext: Some("bdf"), language_type: LanguageType::Data, color: None, group: None }),
        ("X BitMap", Language { name: "X BitMap", ext: Some("xbm"), language_type: LanguageType::Data, color: None, group: Some("C") }),
        ("Julia", Language { name: "Julia", ext: Some("jl"), language_type: LanguageType::Programming, color: Some("#a270ba"), group: None }),
        ("MTML", Language { name: "MTML", ext: Some("mtml"), language_type: LanguageType::Markup, color: Some("#b7e1f4"), group: None }),
        ("Easybuild", Language { name: "Easybuild", ext: Some("eb"), language_type: LanguageType::Data, color: None, group: Some("Python") }),
        ("ColdFusion", Language { name: "ColdFusion", ext: Some("cfm"), language_type: LanguageType::Programming, color: Some("#ed2cd6"), group: None }),
        ("Oz", Language { name: "Oz", ext: Some("oz"), language_type: LanguageType::Programming, color: Some("#fab738"), group: None }),
        ("Dhall", Language { name: "Dhall", ext: Some("dhall"), language_type: LanguageType::Programming, color: Some("#dfafff"), group: None }),
        ("nesC", Language { name: "nesC", ext: Some("nc"), language_type: LanguageType::Programming, color: Some("#94B0C7"), group: None }),
        ("Stan", Language { name: "Stan", ext: Some("stan"), language_type: LanguageType::Programming, color: Some("#b2011d"), group: None }),
        ("D-ObjDump", Language { name: "D-ObjDump", ext: Some("d-objdump"), language_type: LanguageType::Data, color: None, group: None }),
        ("HTML", Language { name: "HTML", ext: Some("html"), language_type: LanguageType::Markup, color: Some("#e34c26"), group: None }),
        ("JavaScript+ERB", Language { name: "JavaScript+ERB", ext: Some("js.erb"), language_type: LanguageType::Programming, color: None, group: Some("JavaScript") }),
        ("QML", Language { name: "QML", ext: Some("qml"), language_type: LanguageType::Programming, color: Some("#44a51c"), group: None }),
        ("Racket", Language { name: "Racket", ext: Some("rkt"), language_type: LanguageType::Programming, color: Some("#3c5caa"), group: None }),
        ("HTML+PHP", Language { name: "HTML+PHP", ext: Some("phtml"), language_type: LanguageType::Markup, color: None, group: Some("HTML") }),
        ("Sage", Language { name: "Sage", ext: Some("sage"), language_type: LanguageType::Programming, color: None, group: Some("Python") }),
        ("Darcs Patch", Language { name: "Darcs Patch", ext: Some("darcspatch"), language_type: LanguageType::Data, color: None, group: None }),
        ("Tea", Language { name: "Tea", ext: Some("tea"), language_type: LanguageType::Markup, color: None, group: None }),
        ("Modelica", Language { name: "Modelica", ext: Some("mo"), language_type: LanguageType::Programming, color: None, group: None }),
        ("Vala", Language { name: "Vala", ext: Some("vala"), language_type: LanguageType::Programming, color: Some("#fbe5cd"), group: None }),
        ("Maven POM", Language { name: "Maven POM", ext: None, language_type: LanguageType::Data, color: None, group: None }),
        ("wisp", Language { name: "wisp", ext: Some("wisp"), language_type: LanguageType::Programming, color: Some("#7582D1"), group: None }),
        ("Prolog", Language { name: "Prolog", ext: Some("pl"), language_type: LanguageType::Programming, color: Some("#74283c"), group: None }),
        ("Python traceback", Language { name: "Python traceback", ext: Some("pytb"), language_type: LanguageType::Data, color: None, group: Some("Python") }),
        ("Dart", Language { name: "Dart", ext: Some("dart"), language_type: LanguageType::Programming, color: Some("#00B4AB"), group: None }),
        ("eC", Language { name: "eC", ext: Some("ec"), language_type: LanguageType::Programming, color: Some("#913960"), group: None }),
        ("sed", Language { name: "sed", ext: Some("sed"), language_type: LanguageType::Programming, color: Some("#64b970"), group: None }),
        ("CartoCSS", Language { name: "CartoCSS", ext: Some("mss"), language_type: LanguageType::Programming, color: None, group: None }),
        ("Kotlin", Language { name: "Kotlin", ext: Some("kt"), language_type: LanguageType::Programming, color: Some("#F18E33"), group: None }),
        ("Graph Modeling Language", Language { name: "Graph Modeling Language", ext: Some("gml"), language_type: LanguageType::Data, color: None, group: None }),
        ("HCL", Language { name: "HCL", ext: Some("hcl"), language_type: LanguageType::Programming, color: None, group: None }),
        ("NumPy", Language { name: "NumPy", ext: Some("numpy"), language_type: LanguageType::Programming, color: None, group: Some("Python") }),
        ("AngelScript", Language { name: "AngelScript", ext: Some("as"), language_type: LanguageType::Programming, color: Some("#C7D7DC"), group: None }),
        ("Svelte", Language { name: "Svelte", ext: Some("svelte"), language_type: LanguageType::Markup, color: None, group: Some("HTML") }),
        ("Twig", Language { name: "Twig", ext: Some("twig"), language_type: LanguageType::Markup, color: None, group: Some("HTML") }),
        ("Slice", Language { name: "Slice", ext: Some("ice"), language_type: LanguageType::Programming, color: Some("#003fa2"), group: None }),
        ("Git Attributes", Language { name: "Git Attributes", ext: None, language_type: LanguageType::Data, color: None, group: Some("INI") }),
        ("KRL", Language { name: "KRL", ext: Some("krl"), language_type: LanguageType::Programming, color: Some("#28430A"), group: None }),
        ("Ren\'Py", Language { name: "Ren'Py", ext: Some("rpy"), language_type: LanguageType::Programming, color: Some("#ff7f7f"), group: None }),
        ("SMT", Language { name: "SMT", ext: Some("smt2"), language_type: LanguageType::Programming, color: None, group: None }),
        ("CodeQL", Language { name: "CodeQL", ext: Some("ql"), language_type: LanguageType::Programming, color: None, group: None }),
        ("Processing", Language { name: "Processing", ext: Some("pde"), language_type: LanguageType::Programming, color: Some("#0096D8"), group: None }),
        ("Golo", Language { name: "Golo", ext: Some("golo"), language_type: LanguageType::Programming, color: Some("#88562A"), group: None }),
        ("XC", Language { name: "XC", ext: Some("xc"), language_type: LanguageType::Programming, color: Some("#99DA07"), group: None }),
        ("Nextflow", Language { name: "Nextflow", ext: Some("nf"), language_type: LanguageType::Programming, color: Some("#3ac486"), group: None }),
        ("Uno", Language { name: "Uno", ext: Some("uno"), language_type: LanguageType::Programming, color: None, group: None }),
        ("HolyC", Language { name: "HolyC", ext: Some("hc"), language_type: LanguageType::Programming, color: Some("#ffefaf"), group: None }),
        ("ABAP", Language { name: "ABAP", ext: Some("abap"), language_type: LanguageType::Programming, color: Some("#E8274B"), group: None }),
        ("Mercury", Language { name: "Mercury", ext: Some("m"), language_type: LanguageType::Programming, color: Some("#ff2b2b"), group: None }),
        ("Mirah", Language { name: "Mirah", ext: Some("druby"), language_type: LanguageType::Programming, color: Some("#c7a938"), group: None }),
        ("QMake", Language { name: "QMake", ext: Some("pro"), language_type: LanguageType::Programming, color: None, group: None }),
        ("MATLAB", Language { name: "MATLAB", ext: Some("matlab"), language_type: LanguageType::Programming, color: Some("#e16737"), group: None }),
        ("Rebol", Language { name: "Rebol", ext: Some("reb"), language_type: LanguageType::Programming, color: Some("#358a5b"), group: None }),
        ("Omgrofl", Language { name: "Omgrofl", ext: Some("omgrofl"), language_type: LanguageType::Programming, color: Some("#cabbff"), group: None }),
        ("Max", Language { name: "Max", ext: Some("maxpat"), language_type: LanguageType::Programming, color: Some("#c4a79c"), group: None }),
        ("NetLinx+ERB", Language { name: "NetLinx+ERB", ext: Some("axs.erb"), language_type: LanguageType::Programming, color: Some("#747faa"), group: None }),
        ("Objective-C++", Language { name: "Objective-C++", ext: Some("mm"), language_type: LanguageType::Programming, color: Some("#6866fb"), group: None }),
        ("Raw token data", Language { name: "Raw token data", ext: Some("raw"), language_type: LanguageType::Data, color: None, group: None }),
        ("Visual Basic .NET", Language { name: "Visual Basic .NET", ext: Some("vb"), language_type: LanguageType::Programming, color: Some("#945db7"), group: None }),
        ("Pony", Language { name: "Pony", ext: Some("pony"), language_type: LanguageType::Programming, color: None, group: None }),
        ("GAMS", Language { name: "GAMS", ext: Some("gms"), language_type: LanguageType::Programming, color: None, group: None }),
        ("Objective-C", Language { name: "Objective-C", ext: Some("m"), language_type: LanguageType::Programming, color: Some("#438eff"), group: None }),
        ("XPages", Language { name: "XPages", ext: Some("xsp-config"), language_type: LanguageType::Data, color: None, group: None }),
        ("Jison", Language { name: "Jison", ext: Some("jison"), language_type: LanguageType::Programming, color: None, group: Some("Yacc") }),
        ("Frege", Language { name: "Frege", ext: Some("fr"), language_type: LanguageType::Programming, color: Some("#00cafe"), group: None }),
        ("Pike", Language { name: "Pike", ext: Some("pike"), language_type: LanguageType::Programming, color: Some("#005390"), group: None }),
        ("CLIPS", Language { name: "CLIPS", ext: Some("clp"), language_type: LanguageType::Programming, color: None, group: None }),
        ("LoomScript", Language { name: "LoomScript", ext: Some("ls"), language_type: LanguageType::Programming, color: None, group: None }),
        ("OpenQASM", Language { name: "OpenQASM", ext: Some("qasm"), language_type: LanguageType::Programming, color: Some("#AA70FF"), group: None }),
        ("Xtend", Language { name: "Xtend", ext: Some("xtend"), language_type: LanguageType::Programming, color: None, group: None }),
        ("AMPL", Language { name: "AMPL", ext: Some("ampl"), language_type: LanguageType::Programming, color: Some("#E6EFBB"), group: None }),
        ("DataWeave", Language { name: "DataWeave", ext: Some("dwl"), language_type: LanguageType::Programming, color: Some("#003a52"), group: None }),
        ("CWeb", Language { name: "CWeb", ext: Some("w"), language_type: LanguageType::Programming, color: None, group: None }),
        ("IDL", Language { name: "IDL", ext: Some("pro"), language_type: LanguageType::Programming, color: Some("#a3522f"), group: None }),
        ("DirectX 3D File", Language { name: "DirectX 3D File", ext: Some("x"), language_type: LanguageType::Data, color: None, group: None }),
        ("ShellSession", Language { name: "ShellSession", ext: Some("sh-session"), language_type: LanguageType::Programming, color: None, group: None }),
        ("DTrace", Language { name: "DTrace", ext: Some("d"), language_type: LanguageType::Programming, color: None, group: None }),
        ("Opa", Language { name: "Opa", ext: Some("opa"), language_type: LanguageType::Programming, color: None, group: None }),
        ("Slash", Language { name: "Slash", ext: Some("sl"), language_type: LanguageType::Programming, color: Some("#007eff"), group: None }),
        ("WebVTT", Language { name: "WebVTT", ext: Some("vtt"), language_type: LanguageType::Data, color: None, group: None }),
        ("Ballerina", Language { name: "Ballerina", ext: Some("bal"), language_type: LanguageType::Programming, color: Some("#FF5000"), group: None }),
        ("SourcePawn", Language { name: "SourcePawn", ext: Some("sp"), language_type: LanguageType::Programming, color: Some("#5c7611"), group: None }),
        ("HTML+EEX", Language { name: "HTML+EEX", ext: Some("eex"), language_type: LanguageType::Markup, color: None, group: Some("HTML") }),
        ("Pod", Language { name: "Pod", ext: Some("pod"), language_type: LanguageType::Prose, color: None, group: None }),
        ("FLUX", Language { name: "FLUX", ext: Some("fx"), language_type: LanguageType::Programming, color: Some("#88ccff"), group: None }),
        ("Eiffel", Language { name: "Eiffel", ext: Some("e"), language_type: LanguageType::Programming, color: Some("#946d57"), group: None }),
        ("Terra", Language { name: "Terra", ext: Some("t"), language_type: LanguageType::Programming, color: Some("#00004c"), group: None }),
        ("Wavefront Object", Language { name: "Wavefront Object", ext: Some("obj"), language_type: LanguageType::Data, color: None, group: None }),
        ("Component Pascal", Language { name: "Component Pascal", ext: Some("cp"), language_type: LanguageType::Programming, color: Some("#B0CE4E"), group: None }),
        ("MoonScript", Language { name: "MoonScript", ext: Some("moon"), language_type: LanguageType::Programming, color: None, group: None }),
        ("Gentoo Eclass", Language { name: "Gentoo Eclass", ext: Some("eclass"), language_type: LanguageType::Programming, color: None, group: Some("Shell") }),
        ("VBA", Language { name: "VBA", ext: Some("bas"), language_type: LanguageType::Programming, color: Some("#867db1"), group: None }),
        ("M4Sugar", Language { name: "M4Sugar", ext: Some("m4"), language_type: LanguageType::Programming, color: None, group: Some("M4") }),
        ("Liquid", Language { name: "Liquid", ext: Some("liquid"), language_type: LanguageType::Markup, color: None, group: None }),
        ("Isabelle ROOT", Language { name: "Isabelle ROOT", ext: None, language_type: LanguageType::Programming, color: None, group: Some("Isabelle") }),
        ("NCL", Language { name: "NCL", ext: Some("ncl"), language_type: LanguageType::Programming, color: Some("#28431f"), group: None }),
        ("Click", Language { name: "Click", ext: Some("click"), language_type: LanguageType::Programming, color: Some("#E4E6F3"), group: None }),
        ("APL", Language { name: "APL", ext: Some("apl"), language_type: LanguageType::Programming, color: Some("#5A8164"), group: None }),
        ("SaltStack", Language { name: "SaltStack", ext: Some("sls"), language_type: LanguageType::Programming, color: Some("#646464"), group: None }),
        ("Jasmin", Language { name: "Jasmin", ext: Some("j"), language_type: LanguageType::Programming, color: None, group: None }),
    ]),
};

